### ISSUE TITLE
disable folder/indentation in lsp_finder

### ISSUE THREAD

**Issue by alextrastero** [nvimdev/lspsaga.nvim#1000]
Again, thank you for this awesome project.

Recently the lsp_finder changed the Definition/Implements/References view to show a folder layout with indentation, is there any way to disable this?

How I would like it:
![image](https://user-images.githubusercontent.com/4152819/230047635-2d8eb147-31df-4e20-ad0b-008a729371b3.png)

How it currently is:
![image](https://user-images.githubusercontent.com/4152819/230047751-00eea427-b948-431c-ab4a-c4eaef46a056.png)

**Comment by alextrastero** [comment]
It's nice to see the filename, but it's too many strokes to get to References (which is normally the only one I'm interested in)

**Comment by glepnir** [comment]
for a big project . if one file have many references of this word . the old ui will show this file name many times . do you like this ?  currently get the word is limit of window width . in next  change of finder will improve this and window layout .will make this better and more useful than only show filename.
