### ISSUE TITLE
'No information available' if there are two lsp clients 

### ISSUE THREAD

**Issue by rbereziuk** [nvimdev/lspsaga.nvim#1015]
### Describe the bug

If there are two lsp clients, and one of them "fails" the hover while the other succeeds, a hover will popup and "No information available" will be notified.

Already found [pr with fix](https://github.com/glepnir/lspsaga.nvim/pull/995), but the issue is still reproduced

### Steps to reproduce

- Open .tsx file with already installed typescript and tailwind servers
- Call saga hovers over any typescript variable/function

### Expected behavior

If one of LSP's clients succeeds, "No information available" doesn't display

### Neovim version (nvim -v)

0.8.3 and 0.9.0

### lspsaga commit

5099b46f9fd9747f8c69be228ff54c2cb8ce229f

### Terminal name/version

alacritty 0.11, iTerm 3.4.19

**Comment by diegoulloao** [comment]
```lua
  keymap.set("n", "<leader>K", "<cmd>Lspsaga hover_doc ++quiet<CR>", opts) -- show documentation for the cursor
```

Having the same issue when just pressing  the keybinding in tsx.

<img width="1440" alt="Screenshot" src="https://github.com/nvimdev/lspsaga.nvim/assets/45423661/6aef34e9-92f8-44db-bd20-613ecaf78211">
