### ISSUE TITLE
Having issue with folke's `trouble.nvim` for buffers created by `lspsaga`

### ISSUE THREAD

**Issue by farzadmf** [nvimdev/lspsaga.nvim#1019]
### Describe the bug

When I open a buffer from the Lspsaga's `peek_definition` or `finder` windows, and I try to open `trouble.nvim`, I get the following error:
```
E5108: Error executing lua ...my_lazy/data/nvim/lazy/trouble.nvim/lua/trouble/view.lua:51: Invalid buffer id: 328
stack traceback:
	[C]: in function 'nvim_buf_set_name'
	...my_lazy/data/nvim/lazy/trouble.nvim/lua/trouble/view.lua:51: in function 'wipe_rogue_buffer'
	...my_lazy/data/nvim/lazy/trouble.nvim/lua/trouble/view.lua:134: in function 'setup'
	...my_lazy/data/nvim/lazy/trouble.nvim/lua/trouble/view.lua:357: in function 'create'
	...my_lazy/data/nvim/lazy/trouble.nvim/lua/trouble/init.lua:76: in function 'open'
	...my_lazy/data/nvim/lazy/trouble.nvim/lua/trouble/init.lua:92: in function 'toggle'
	[string ":lua"]:1: in main chunk
```

My `lspsaga` config:
```lua
beacon = {
  enable = true,
  frequency = 16,
},
definition = {
  edit = '<C-c><cr>',
  quit = 'q',
  split = '<C-c><C-x>',
  tabe = '<C-c><C-t>',
  vsplit = '<C-c><C-v>',
},
finder = {
  keys = {
    expand_or_jump = '<C-c><cr>',
    vsplit = '<C-c><C-v>',
    split = '<C-c><C-x>',
    tabe = '<C-c><C-t>',
    quit = { 'q', '<ESC>' },
    close_in_preview = '<ESC>',
  },
},
outline = {
  win_width = 60,
  preview_width = 0.5,
  keys = { -- defaults; for reference
    expand_or_jump = 'o',
    quit = 'q',
  },
},
ui = {
  border = 'rounded',
}
```

### Steps to reproduce

1. Open a code file (say, a Python file)
2. Do `:Lspsaga peek_defintion` on a symbol
3. Do `<C-c><cr>` (I have this mapping configured)
4. Do `:TroubleToggle`
5. See the error

### Expected behavior

If I open the file/buffer "normally" (for example, through `neo-tree`), I can successfully open `trouble`, and it's only when then buffer is opened through `lspsaga` that the error happenZZs

### Neovim version (nvim -v)

0.9.0

### lspsaga commit

1ead4ce

### Terminal name/version

wezterm 20230408-112425-69ae8472

**Comment by glepnir** [comment]
error from trouble why create issue here

**Comment by farzadmf** [comment]
@glepnir  Because `trouble`, as I mentioned above, is working fine when I open the buffer in any other way, and it's only the buffers opened by `lspsaga` that have this issue
