### ISSUE TITLE
attempt to index field 'enriched_ctx' (a nil value)

### ISSUE THREAD

**Issue by zsmatrix62** [nvimdev/lspsaga.nvim#1020]
### Describe the bug

I encounters this error recently very often:

```
attempt to index field 'enriched_ctx' (a nil value)
```

![image](https://user-images.githubusercontent.com/2951879/231653699-d01165e1-f62c-472c-ba62-86e0c608ad06.png)

### Steps to reproduce

using code acitons

### Expected behavior

auto fix problems

### Neovim version (nvim -v)

NVIM v0.9.0 Build type: Release LuaJIT 2.1.0-beta3

### lspsaga commit

latest

### Terminal name/version

alacritty

**Comment by NickyTope** [comment]
I also get this error when trying to select an action, just started yesterday...

Neovim git latest
lspsaga latest
Alacritty

**Comment by zsmatrix62** [comment]
and another one: 🤔

```
 .../share/nvim/lazy/lspsaga.nvim/lua/lspsaga/codeaction.lua:203: attempt to call field 'deepcopty' (a nil value)
```

<img width="1533" alt="image" src="https://user-images.githubusercontent.com/2951879/231676952-bb88dabf-bad5-4acf-b264-94490b38874f.png">

**Comment by glepnir** [comment]
update . a typo sry

**Comment by zsmatrix62** [comment]
> update . a typo sry

the same error of `attempt to index field 'enriched_ctx' (a nil value)`  occurs at line 265 just now .. 🫠

**Comment by glepnir** [comment]
hmm I am on phone to edit these code .. can you update and test.

**Comment by zsmatrix62** [comment]
> hmm I am on phone to edit these code .. can you update and test.

no worries, take your time on this fix. 🫠

**Comment by alextrastero** [comment]
Yup, I can confirm that after updating it's fixed

**Comment by zsmatrix62** [comment]
true, confirmed fixed. 💋

**Comment by zsmatrix62** [comment]
I confirmed above error has been fixed, however, the code action window does not auto-close after i've chosen a action. 

Can i suppose that window was closed in history releases? 

<img width="703" alt="image" src="https://user-images.githubusercontent.com/2951879/231769063-1391683f-b3fa-4851-a2f5-c0e0d6dcd92a.png">

**Comment by zsmatrix62** [comment]
> hmm you mean after you type 1 the window not close ?

yes, exactly.

**Comment by glepnir** [comment]
can you update then test .. i try to add some patch. not sure can fix this i don' try to reproduce it.

**Comment by glepnir** [comment]
can you update then test .. i try to add some patch. not sure can fix this i don' try to reproduce it.

**Comment by zsmatrix62** [comment]
> can you update then test .. i try to add some patch. not sure can fix this i don' try to reproduce it.

No it doesn't. But it works fine while using `:Lspsaga code_action` command : (

**Comment by zsmatrix62** [comment]
i just disabled the code action on diagnostics:

```lua
diagnostic = {
	show_code_action = false
}
```

**Comment by glepnir** [comment]
fixed.
