### ISSUE TITLE
`peek_definition -> peek_definition` does not open a new float anymore

### ISSUE THREAD

**Issue by pyrho** [nvimdev/lspsaga.nvim#1022]
### Describe the bug

Hey,

I really liked the way you could navigate via `peek_definition` recursively, each call would open a new float (like a stack).
This does not work anymore.

![CleanShot 2023-04-13 at 13 03 17 2](https://user-images.githubusercontent.com/145502/231740500-0e1cec34-25d7-4b91-ba74-b3155cbe953a.gif)

And thanks for the awesome plugin!

### Steps to reproduce

minimal init.lua:

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git", "clone", "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git", "--branch=stable", -- latest stable release
    lazypath
  })
end
vim.opt.rtp:prepend(lazypath)

vim.g.mapleader = " " -- Make sure to set `mapleader` before lazy so your mappings are correct

require("lazy").setup({
  "glepnir/lspsaga.nvim",
  event = "LspAttach",
  commit = "1ead4ce8a20a8ac7e96aca038d54ceaa185be4e0",
  config = function() require("lspsaga").setup({}) end,
  dependencies = {
    {"nvim-tree/nvim-web-devicons"},
    -- Please make sure you install markdown and markdown_inline parser
    {"nvim-treesitter/nvim-treesitter"}
  }
})
require'lspconfig'.tsserver.setup {}
```

Open nvim.
Call `:Lspsaga peek_definition`, and call it again from the peek definition float.

### Expected behavior

When calling `:Lspsaga peek_definition` from the peek definition float, a new float should appear.

### Neovim version (nvim -v)

NVIM v0.9.0-dev-885+g8fbe75b3d-dirty

### lspsaga commit

1ead4ce8a20a8ac7e96aca038d54ceaa185be4e0

### Terminal name/version

kitty 0.27.0

**Comment by pyrho** [comment]
> yep now it reuse a float window instead of create many float window.

Oh ok. I really like this feature, is there a plan to make this configurable ?

**Comment by glepnir** [comment]
can be support . 0.3.0 is developing. plan to refactor some modules.

**Comment by pyrho** [comment]
Or I can close this and open a feature request instead.

**Comment by glepnir** [comment]
a feature request as a  trace.
