### ISSUE TITLE
Allow users to have a stack of "peek_definition" floating windows

### ISSUE THREAD

**Issue by pyrho** [nvimdev/lspsaga.nvim#1023]
**Describe the solution you'd like**
When you call `peek_definition` from the peek definition window, a new float would open and so on. Essentially making a stack of floating windows.
Pressing `q` inside the latest float would take you back to the previous float, etc until you have exited all the floats.

This feature used to exist, but has been removed lately and now there's only ever one peek_definition float open at any given time.

I'm not sure why this was changed in the first place, but maybe providing a user configurable option would make sense; like adding this to the `peek_definition` options:

```diff
  definition = {
    edit = "<C-c>o",
    vsplit = "<C-c>v",
    split = "<C-c>i",
    tabe = "<C-c>t",
    quit = "q",
+   stacked = true
  }
```

**Comment by glepnir** [comment]
context https://github.com/nvimdev/lspsaga.nvim/issues/1022

**Comment by tsakirist** [comment]
Yes, I would like this feature back. This is really important to be able to stack floating windows for peek definitions.
