### ISSUE TITLE
Why I can't change variable/class/struct name in all files?

### ISSUE THREAD

**Issue by back2childhood** [nvimdev/lspsaga.nvim#1025]
I just can change the name in the file that I'm writing. But when I open the definition file, I find the variable is still the old name. This made me tired, I need to modify each file individually.

**Comment by back2childhood** [comment]
I remember it working normally at beginning, but suddenly it doesn't work.

**Comment by back2childhood** [comment]
oh, do you mean this? 
```
-- configure lua server (with special settings)
-- lspconfig["sumneko_lua"].setup({
lspconfig["lua_ls"].setup({
  capabilities = capabilities,
  on_attach = on_attach,
  settings = { -- custom settings for lua
    Lua = {
      -- make the language server recognize "vim" global
      diagnostics = {
        globals = { "vim" },
      },
      workspace = {
        -- make language server aware of runtime files
        library = {
          [vim.fn.expand("$VIMRUNTIME/lua")] = true,
          [vim.fn.stdpath("config") .. "/lua"] = true,
        },
      },
    },
  },
})
```
i used sumneko_lua at first, but it couldn't work, so i changed it to lua_ls. could you please give me some advise? sad..

**Comment by back2childhood** [comment]
> the default `vim.lsp.buf.rename` works fine ? some server can rename whole project some server can't . which server do you used ?

oh, do you mean this?
```
-- configure lua server (with special settings)
-- lspconfig["sumneko_lua"].setup({
lspconfig["lua_ls"].setup({
  capabilities = capabilities,
  on_attach = on_attach,
  settings = { -- custom settings for lua
    Lua = {
      -- make the language server recognize "vim" global
      diagnostics = {
        globals = { "vim" },
      },
      workspace = {
        -- make language server aware of runtime files
        library = {
          [vim.fn.expand("$VIMRUNTIME/lua")] = true,
          [vim.fn.stdpath("config") .. "/lua"] = true,
        },
      },
    },
  },
})
```
i used sumneko_lua at first, but it couldn't work, so i changed it to lua_ls. could you please give me some advise? sad..

**Comment by glepnir** [comment]
I used `lua_ls` to rename a variable . whole project of this variable changed.  what i mean is `:lua vim.lsp.buf.rename()` if this works fine. lspsaga rename can't work is lspsaga bug. if both not work then no bug here maybe server bug.
