### ISSUE TITLE
Peek references

### ISSUE THREAD

**Issue by pluma9** [nvimdev/lspsaga.nvim#1027]
**Is your feature request related to a problem? Please describe.**
peek_definition is a great way to explore definitions when the definition hierarchy is deep, because from a preview window, you  can repetitively open another preview window. In a similar way, peek_reference will be really helpful.

**Describe the solution you'd like**
Just like peek_definition, but for references.

**Describe alternatives you've considered**
No alternatives I can think of

**Additional context**

**Comment by glepnir** [comment]
sound like duplicate with finder ?

**Comment by pluma9** [comment]
Seems like finder only takes me to the chosen location and immediately close the float window, but cannot show a stack of float windows like peek_definition

**Comment by glepnir** [comment]
nope you can edit in finder peek window. 

![image](https://user-images.githubusercontent.com/41671631/232195472-2e7d6d9c-03a8-4334-b728-22842f2c91c8.png)

**Comment by pluma9** [comment]
You're right. I was using an old version of the plugin.

I guess I'm focusing more on the code exploration aspect. In the old version, when I do a peek_definition, a floating preview window appears. In that floating window, I do another peek_definition, and another floating window appears. Image you have class with fields of different types which also have fields of different types. The ability to open multiple preview window allows me to easily jump into the rabbit hole to explore the classes in a hierarchical fashion.

And in this feature quest, I suggested that we should have such ability for references.

And I'm a bit sad that in the latest version, I cannot do that any more. When I do a peek_definition in the preview window, neovim jumps to the destination in that same window.

**Comment by glepnir** [comment]
look at #1023

**Comment by pluma9** [comment]
Thanks. I can't wait to see it again. I really appreciate your works.

**Comment by glepnir** [comment]
close then as duplicate.

**Comment by pluma9** [comment]
Sorry, just to clarify, I think this is not a duplicate. This is a request for peek_reference with stacked windows. I'm not sure if you have any plan for that. Presumably this is not possible with finder.

**Comment by glepnir** [comment]
work like before definition ? but it's different . maybe you want `callhierarchy`?

**Comment by pluma9** [comment]
I don't think it's ever implemented in this plugin. `callhierarchy` is a different thing. By `reference`, I mean something like this (but with preview windows):

```
buf_set_keymap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
```

**Comment by glepnir** [comment]
finder references also have preview window and support edit ? not same hmm ?

**Comment by pluma9** [comment]
but unlike peek_definitions, finder references is not capable of opening a stack of preview windows.

**Comment by glepnir** [comment]
because references request return all refs  it doesn't like definition .you can do it recursion.

**Comment by pluma9** [comment]
Sorry if I failed to give a clear description of the feature. [goto-preview](https://github.com/rmagatti/goto-preview) has exactly this. This is how it looks when I use goto-preview:

![goto-preview](https://user-images.githubusercontent.com/16544647/232276510-003ec642-be3d-4aa8-add5-b905f5fbc6be.gif)

With that, I believe it is technically possible to implement in lspsaga.nvim.

I love this feature so bad that I'm considering using goto-preview and lspsaga.nvim side by side so that I can get the best of both worlds.

**Comment by glepnir** [comment]
nope It just show referecnes to telescope then get it frome telescope window and create a new window.

**Comment by glepnir** [comment]
![test](https://user-images.githubusercontent.com/41671631/232277609-4d430276-7713-4391-8c40-04454becac86.gif)


You want to tell me that is more efficient than finder ..  Create an infinite number of stack windows. Unnecessary waste of memory. For definition, I will restore the previous calling method.

**Comment by pluma9** [comment]
Yes, I see, that is a bit different from peek_definitions. That is what I use for exploring references in a depth-first fashion. I could imagine that an improvement to that feature of goto-preview is to show a preview reference list (instead of fzf list) and when I choose one of the entry, it creates a new window and still keep the reference list window open so that when I jump out of the rabbit hole, I easily know where left off.

I'm not sure if that makes sense to you and if others find this way of exploring code helpful. I was wondering if you have any plan to support that.

I am a vim plugin noob. If there is no plan for this, I think I will try to make this feature come true in the far future.

**Comment by pluma9** [comment]
> You want to tell me that is more efficient than finder .. Create an infinite number of stack windows. Unnecessary waste of memory. For definition, I will restore the previous calling method.

Yes, that is exactly the point I'm trying to make. I work on codebases with multi layers, i.e. deep call hierarchy. I usually stand from the most inner layer and recursively find references until I'm taken to the outer layer (e.g. a web action controller). I personally find having multiple windows give me a clearer call hierarchy in my head.

**Comment by glepnir** [comment]
I think you have not try the current version finder.  your gif example is the least efficient behavior in my opinion.

![test](https://user-images.githubusercontent.com/41671631/232278323-23faff05-8723-4105-a3b5-b8e1e56a97a1.gif)

**Comment by pluma9** [comment]
Fair enough. The latest version of find looks pretty neat. I may be wrong about the efficiency of having a stack of multiple preview windows. Let's me just to try the finder for some time.

Again, I really appreciate your support. Keep up the good work!
