### ISSUE TITLE
code actions return deepcopy error when call in certain lines

### ISSUE THREAD

**Issue by Kongpob-R** [nvimdev/lspsaga.nvim#1030]
### Describe the bug

When call code actions on Importing dependency, create class, sort members, convert to blocks body works as expected the code actions popup shows.
When expected code actions is about wrap with widget or remove widget etc. it will return this error without the code actions popup shows.
<img width="635" alt="image" src="https://user-images.githubusercontent.com/51488908/232772864-279c18dd-2169-4a7d-abf2-d3aa8a226ebd.png">

Error executing vim.schedule lua callback: vim/shared.lua:0: Cannot deepcopy object of type userdata
stack traceback:
[C]: in function 'error'
vim/shared.lua: in function 'deepcopy'
vim/shared.lua: in function 'deepcopy'
vim/shared.lua: in function 'deepcopy'
vim/shared.lua: in function 'deepcopy'
vim/shared.lua: in function 'deepcopy'
vim/shared.lua: in function 'deepcopy'
...ack/packer/start/lspsaga.nvim/lua/lspsaga/codeaction.lua:203: in function 'callback'
...w/Cellar/neovim/0.8.2/share/nvim/runtime/lua/vim/lsp.lua:1951: in function 'handler'
...w/Cellar/neovim/0.8.2/share/nvim/runtime/lua/vim/lsp.lua:1383: in function ''
vim/_editor.lua: in function <vim/_editor.lua:0>
Press ENTER or type command to continue

### Steps to reproduce

call lspsaga code action in any Widget build()
see deepcopy error

### Expected behavior

I expected it the code actions to works for all cases.

### Neovim version (nvim -v)

v0.8.2

### lspsaga commit

c7cc005ba2600c3eaf2bddb2b631ecc9d63b2ba8

### Terminal name/version

macOS iterm2

**Comment by glepnir** [comment]
and can you provide a min code that reproduce this error. i need check the what action is . it should a lua type

**Comment by Kongpob-R** [comment]
I've try run code actions on some lines in default `flutter create project` command
import 'package:flutter/material.dart'; //works
//works
void main() { //works
  runApp(const MyApp()); //works
} //works
 //works
class MyApp extends StatelessWidget {//works
  const MyApp({super.key});//works
  //works
  @override //error
  Widget build(BuildContext context) {//error
    return MaterialApp(//error
      title: 'Flutter Demo',//error
      theme: ThemeData(//error
        primarySwatch: Colors.blue,//error
      ),//error
      home: const MyHomePage(title: 'Flutter Demo Home Page'),//error
    );//works
  }//works
}//works

bellow are the setup I've use
  -- configuring lsp servers
  use({ "glepnir/lspsaga.nvim", branch = "main" }) -- enhanced lsp uis
  use("dart-lang/dart-vim-plugin")
  use({
    "akinsho/flutter-tools.nvim",
    requires = "nvim-lua/plenary.nvim",
  }) --flutter-tools

**Comment by glepnir** [comment]
thanks  I will check what action is.
