### ISSUE TITLE
Appearance of `:Lspsaga hover_doc`

### ISSUE THREAD

**Issue by Alexis12119** [nvimdev/lspsaga.nvim#1031]
### Describe the bug

![Screenshot (177)](https://user-images.githubusercontent.com/74944536/232793928-f37197c5-1907-46d8-8cda-2d45b39fc77d.png)

**NOTE:** I also tried it with other themes.

### Steps to reproduce

Just install this plugin and use `:Lspsaga hover_doc`.

### Expected behavior

The appearance should be the same as it shows on the showcase.

### Neovim version (nvim -v)

0.9.0 and nightly

### lspsaga commit

c7cc005ba2600c3eaf2bddb2b631ecc9d63b2ba8

### Terminal name/version

Windows terminal 1.16.230126001

**Comment by glepnir** [comment]
install treesitter markdown and markdown_inline parser please run `:checkhealth`

**Comment by Alexis12119** [comment]
![Screenshot (191)](https://user-images.githubusercontent.com/74944536/232939339-98852b36-1ddf-408e-b50b-d14f0ffa21c0.png)

![Screenshot (192)](https://user-images.githubusercontent.com/74944536/232939348-de6a9670-59e2-4b0a-9d9a-59c77056d745.png)

I reinstalled the two parser. It's not totally the same, but it's better than before.

**Comment by glepnir** [comment]
run command twice jump into the hover window then `:setlocal conceallevel?`  and `:setlocal concealcursor` what's the output of these two commands

**Comment by glepnir** [comment]
looks like you dont install `tree-sitter`

![image](https://user-images.githubusercontent.com/41671631/232940633-ea676cbc-1e4c-494b-843a-9cf40395468f.png)

**Comment by Alexis12119** [comment]
`:setlocal conceallevel?` -> 2
`:setlocal concealcursor` -> niv

Oh, I see that must be the reason. Thanks anyways.

**Comment by Alexis12119** [comment]
I Installed `tree-sitter-cli` through `npm`, but still the same.
 
![Screenshot (193)](https://user-images.githubusercontent.com/74944536/232950932-f33d32e8-6f77-45da-95f9-eb8a592c781f.png)
![Screenshot (194)](https://user-images.githubusercontent.com/74944536/232950939-e1d755f0-8ad7-48fe-ae2e-a39535168311.png)

**Comment by glepnir** [comment]
`nvim-treesitter` checkhealth report is what ? the code block should be hide by conceal ..

**Comment by Alexis12119** [comment]
![Screenshot (195)](https://user-images.githubusercontent.com/74944536/232952562-5acfc282-2a8a-40c3-a087-315c2e340388.png)

And it didn't detect any errors.

**Comment by glepnir** [comment]
everything looks good . it should works fine.  jump to hover window and try `:set filetype=makrdown` `:set conceallevle =2` `:set concealcursor=niv` then how it change?

![image](https://user-images.githubusercontent.com/41671631/232953360-a2be539b-4688-40a0-8a61-a05f84205c35.png)

**Comment by Alexis12119** [comment]
Still the same :(

**Comment by glepnir** [comment]
not relate terminal i think .

**Comment by glepnir** [comment]
I tried a min config only lspsaga and nvim-lspconfig it works fine.

![image](https://user-images.githubusercontent.com/41671631/232954936-a2e59d2b-43b5-4636-be69-cd7965e0859a.png)

**Comment by Alexis12119** [comment]
![Screenshot (196)](https://user-images.githubusercontent.com/74944536/232955771-9de9229a-2936-4c83-b063-123c087eb8ed.png)

maybe it's still showing because even in a markdown file it's still visible.

**Comment by glepnir** [comment]
override by other plugin or something else ?  you need debug your config i think . when `:set conceallevel =2` it should hide some symbols.

**Comment by Alexis12119** [comment]
Then I'll disable my other plugins and find who causes it.

**Comment by Alexis12119** [comment]
Sadly, other plugins aren't the cause.

**Comment by Alexis12119** [comment]
This is a weird issue.
