### ISSUE TITLE
`peek_definition` mappings are broken (again)?

### ISSUE THREAD

**Issue by farzadmf** [nvimdev/lspsaga.nvim#1033]
### Describe the bug

Hi, I just did the usual update of my plugins, and now my bindings for `peek_definition` window don't work anymore; there was no change in my config.

The responsible commit seems to be [commit b8d210f](https://github.com/nvimdev/lspsaga.nvim/commit/b8d210f6d1a0a33f4b585194e500453c371aa4bf), since if I go back to the commit before that, things work as expected.

My config:
```lua
beacon = {
  enable = true,
  frequency = 16,
},
definition = {
  edit = '<C-c><cr>',
  quit = 'q',
  split = '<C-c><C-x>',
  tabe = '<C-c><C-t>',
  vsplit = '<C-c><C-v>',
},
finder = {
  keys = {
    expand_or_jump = '<C-c><cr>',
    vsplit = '<C-c><C-v>',
    split = '<C-c><C-x>',
    tabe = '<C-c><C-t>',
    quit = { 'q', '<ESC>' },
    close_in_preview = '<ESC>',
  },
},
outline = {
  win_width = 60,
  preview_width = 0.5,
  keys = { -- defaults; for reference
    expand_or_jump = 'o',
    quit = 'q',
  },
},
ui = {
  border = 'rounded',
},
```

### Steps to reproduce

1. Update `lspsaga` to the latest version
2. Open a `peek_definition` window
3. Try to use your custom keybindings and they don't work

### Expected behavior

I expect my configured keybindings to work as before.

Can we please have some tests for this as it keeps braking. I REALLY, really like this plugin, but it's hard to troubleshoot things every time there's an update.

### Neovim version (nvim -v)

0.9.0

### lspsaga commit

83d78e2

### Terminal name/version

wezterm 20230408-112425-69ae8472

**Comment by farzadmf** [comment]
I tried `<C-c><cr>` (open) and `<C-c><C-v>` (vertical split) and none of them seemed to work

**Comment by glepnir** [comment]
open peek_window then `:verb nmap <C-c><CR>`

**Comment by farzadmf** [comment]
> sry I can't reproduce it . works fine in my test .

Sad 🙁 

> open peek_window then `:verb nmap <C-c><CR>`

It gives `no mapping found` for some reason. Even if I do `:verb nmap q` it shows that it's bound to `record macro`

**Comment by glepnir** [comment]
because that commit just do delete map when window close.  you opened window then do ` verb` command then the map not  mapped to lspsaga .so it's wired.  and a test on my local like gif it works fine. so idk . another tip is the definition is refactored in next version.  The current implementation has some confusion.

**Comment by farzadmf** [comment]
> the definition is refactored in next version

So, I guess that's not live yet, is it?

**Comment by farzadmf** [comment]
@glepnir I tried the following:

https://gist.github.com/farzadmf/3f922d8ec7aaafe09854763b060b7649

And it seems to solve the issue. Didn't create a PR since I'm not totally sure if that's the right fix, but let me know what you think

**Comment by AngelontheRoad** [comment]
I had the same question. What's interesting is that the same config and Neovim version I use in both Windows and WSL but Windows works properly but WSL not.

**Comment by briskajanis1** [comment]
I'm having the same issue. After update my keybindings don't seem to work.

**Comment by farzadmf** [comment]
@glepnir Seems like 2 other people have confirmed the same issue (and that the change works for them). I'm going to create a PR for it
