### ISSUE TITLE
Crash with relativenumber=false

### ISSUE THREAD

**Issue by boydkelly** [nvimdev/lspsaga.nvim#1034]
### Describe the bug

When using lspsaga and moving the cursor over a terminating brace, if relativenumber=false I will get the error below  when editing a lua file. (if relative number is set to true the error will not occur.)

Error detected while processing CursorMoved Autocommands for "<buffer=1>":
Error executing lua callback: ...im-modern/lazy/lspsaga.nvim/lua/lspsaga/symbolwinbar.lua:271: Vim:E36: Not enou
gh room
stack traceback:
        [C]: in function 'nvim_set_option_value'
        ...im-modern/lazy/lspsaga.nvim/lua/lspsaga/symbolwinbar.lua:271: in function 'render_fn'
        ...im-modern/lazy/lspsaga.nvim/lua/lspsaga/symbolwinbar.lua:336: in function 'init_buf_symbols'
        ...im-modern/lazy/lspsaga.nvim/lua/lspsaga/symbolwinbar.lua:358: in function <...im-modern/lazy/lspsaga.
nvim/lua/lspsaga/symbolwinbar.lua:357>

### Steps to reproduce

This can be confirmed in the 'modern neovim' (distro) located at https://github.com/alpha2phi/modern-neovim  by @alpha2phi.  Just change the option in this 'distro' to relativenumber=false, and open one of the plugin files such as telescope.lua, lazy.lua etc. 

Move the cursor to the end of the file.   As it moves over the { , it will produce the error.

Change relativenumber back to true and the error will disappear.

### Expected behavior

No errors with relativenumber=false

### Neovim version (nvim -v)

 v0.9.0-dev+1137-ged05d38d9

### lspsaga commit

latest

### Terminal name/version

foot version: 1.13.1 -pgo +ime +graphemes -assertions

**Comment by glepnir** [comment]
I think it not relate relativenumber   ? and it's neovim bug .duplicate https://github.com/nvimdev/lspsaga.nvim/issues/812

**Comment by boydkelly** [comment]
> I think it not relate relativenumber ? and it's neovim bug .duplicate #812

Agreed this must be related.   And I am no expert....   But isnt it strange or significant that the relativenumber setting will also detrmine if the problem occurs?    At least in the above configuraton set    to true.  No problem.   Set it to false.  The issue will occur.  (It took me 3 days to find that out)

**Comment by glepnir** [comment]
maybe you can use `statuscolumn` instead use that. and that pr wait for review so wait that pr merge.

**Comment by boydkelly** [comment]
> maybe you can use `statuscolumn` instead use that. and that pr wait for review so wait that pr merge.

No prob.  i have relative number set to true and all ok.   Just commented to point out 1)   The wierd behaviour and 2) possible work around.  ;)
