### ISSUE TITLE
Open docs in browser

### ISSUE THREAD

**Issue by patrickaldis** [nvimdev/lspsaga.nvim#1037]
### Describe the bug

When using the documentation link inside the `Lspsaga hover_doc`, via the binding set [here](https://github.com/nvimdev/lspsaga.nvim#lspasga-hover_doc), no new window opens, despite the open_browser being set to `!firefox`.

I have manually set the conceal level to 0 and checked the link, which views fine, so the link is okay

### Steps to reproduce

Here is my current config:
```
    require('lspsaga').setup({
      hover = {
        max_width = 0.6,
        open_link = 'gf',
        open_browser = '!firefox',
      }
    })
```

### Expected behavior

Pressing `gf` should open the docs in firefox

### Neovim version (nvim -v)

0.9.0

### lspsaga commit

latest

### Terminal name/version

kitty

**Comment by glepnir** [comment]
your system and which language

**Comment by patrickaldis** [comment]
I'm on NixOS 23.05 and the docs are for Haskell

**Comment by glepnir** [comment]
try config `!xdg-open`

**Comment by patrickaldis** [comment]
That doesn't seem to do anything either.

Is there a way to see the command output

**Comment by glepnir** [comment]
don't know how to open url in nix. you can try some command in your terminal if that command can work then also can work in there. in macos just `open url`  some linux can `xdg-open url`

**Comment by patrickaldis** [comment]
`xdg-open` works fine in the terminal. If I copy across the link from the hover docs it opens fine. It just doesn't seem to work when in neovim

**Comment by glepnir** [comment]
in neovim `:!xdg-open your-doc-link` not work?

**Comment by patrickaldis** [comment]
For some reason no.

The documentation is located at `file:///nix/store/za24s6d8dy5b6y1ns4d5yl1aydg1p84y-ghc-9.0.2-doc/share/doc/ghc/html/libraries/base-4.15.1.0/GHC-Base.html#t:String`

After running `xdg-open <path>` in command line this runs fine. However, in neovim `!xdg-open <path>` gives:
```
:!xdg-open file:///nix/store/za24s6d8dy5b6y1ns4d5yl1aydg1p84y-ghc-9.0.2-doc/share/doc/ghc/html/libraries/base-4.15.1.0/GHC-Base.htmlapp/Main.hst:String.html              
[No write since last change]                                                         
xdg-open: file '/nix/store/za24s6d8dy5b6y1ns4d5yl1aydg1p84y-ghc-9.0.2-doc/share/doc/ghc/html/libraries/base-4.15.1.0/GHC-Base.htmlapp/Main.hst:String.html' does not exist
```

**Comment by glepnir** [comment]
it's a native file link not url link.  `:e /nix/store/za24s6d8dy5b6y1ns4d5yl1aydg1p84y-ghc-9.0.2-doc/share/doc/ghc/html/libraries/base-4.15.1.0/GHC-Base.htmlapp/Main.hst:String.html` it should use this command I think

**Comment by patrickaldis** [comment]
Thanks for all the help! I've done some further testing and realised that there are some issues that crop up because of the location tag `#<location>` at the end of the url:

With link `file:///nix/store/za24s6d8dy5b6y1ns4d5yl1aydg1p84y-ghc-9.0.2-doc/share/doc/ghc/html/libraries/base-4.15.1.0/System-IO.html#v:putStrLn`

# Using Neovim's `:!`
Running the command: `:!firefox file:///<rest of link>.html#v:putStrLn` opens firefox with an empty window, and command output:
![image](https://user-images.githubusercontent.com/46719614/234368297-905ffc18-1cb7-4ff4-b081-4a0a64979b3f.png)


The link has changed for some weird reason - `A1/Lib/Wunsch.hs` has been inserted in place of the `#`. This is significant because this is the name of the currently active LSP buffer.

To get around this, I have had to escape the `#` via `\#`, which works perfectly. So running:
```
`:!firefox file:///<rest of link>.html\#v:putStrLn`
```
Works, loading the page at the correct location.

Is there some significance of `#` in vim commands?

**Comment by glepnir** [comment]
need use `vim.fn.escape`

**Comment by patrickaldis** [comment]
Is this something that I need to add to my config?

**Comment by glepnir** [comment]
nope I need add a patch for this.
