### ISSUE TITLE
View Document

### ISSUE THREAD

**Issue by AndreM222** [nvimdev/lspsaga.nvim#1047]
### Describe the bug

Opening link from view document on hover not working when press gx on top of view documents.

![image](https://user-images.githubusercontent.com/98118238/234964231-bf256b1b-90a7-4f87-98d4-2a964d84f3c4.png)

### Steps to reproduce

OS: Windows

Steps:
press f to use lspsaga hover, press f again to get inside hover, set cursor on top of view documents and press gx to open link

### Expected behavior

Open link of view documents in browser

### Neovim version (nvim -v)

0.9.0

### lspsaga commit

none

### Terminal name/version

Powershell

**Comment by glepnir** [comment]
I don't use windows so I am not sure the open link function in windows can works well. by default it use 

```
!start cmd /cstart /b  link
```

**Comment by AndreM222** [comment]
so gx works but it can not read the link from the markdown. so If I have the link like this http://www.lua.org/manual/5.4/manual.html#pdf-pcall then it can load it but if it is like view documents then it can not read it. or so that Is what I saw after trying gx in many ways hahahahaha.

**Comment by glepnir** [comment]
I tried this on `pcall` it works fine on my local  mac
