### ISSUE TITLE
Open peek definition break transparency

### ISSUE THREAD

**Issue by Fedex159** [nvimdev/lspsaga.nvim#1049]
### Describe the bug

When you open a window with peek_definition the transparency is broken, is full black background.

Video:

https://user-images.githubusercontent.com/44141208/235259672-38a19344-2bc3-43b8-a1f2-26c87757d5ee.mp4

Config:

```lua
saga.setup({
  ui = {
    winblend = 10,
    border = 'rounded',
    colors = {
      normal_bg = "NONE",
    }
  },
  beacon = {
    enable = false,
  }
})
```

### Steps to reproduce

- Open a file
- Move cursor over a function
- Use hover_doc and validate transparency is ok
- Use Lspsaga peek_definition over the function and close
- Validate background color is not more transparent

### Expected behavior

When open peek_definition and close the window transparency don't change

### Neovim version (nvim -v)

0.8.3

### lspsaga commit

32a9dca

### Terminal name/version

Kitty 0.26.5

**Comment by glepnir** [comment]
hmm yep I guess it will have problem with transparent bg ...wait a refactor in next version thanks
