### ISSUE TITLE
Can't customize outline's highlight

### ISSUE THREAD

**Issue by huge-pancake** [nvimdev/lspsaga.nvim#1050]
### Describe the bug

Setting `OutlinePreviewNormal` and `OutlinePreviewBorder` doesn't make any change to the outline panel.

### Steps to reproduce

1. Go to your theme's config file
2. Set `OutlinePreviewNormal` and `OutlinePreviewBorder`
3. Relaunch nvim
4. Open outline panel

### Expected behavior

Outline panel's color changes.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-241+g26cc946226

### lspsaga commit

349b3d4

### Terminal name/version

foot version: 1.14.0 +pgo +ime +graphemes -assertions

**Comment by glepnir** [comment]
update then use `OutlineNormal` to change outline window background.

**Comment by huge-pancake** [comment]
Thanks a lot!

**Comment by huge-pancake** [comment]
Also, how can I customize the highlight of this divider?

**Comment by glepnir** [comment]
`OutlineIndent`

**Comment by huge-pancake** [comment]
Sorry, I mean the bar between my code and the outline panel but not the indent line

![Uploading image.png…]()

**Comment by glepnir** [comment]
`:help VertSplit`

**Comment by huge-pancake** [comment]
Thx I got it!
