### ISSUE TITLE
Lspsaga diagnostic_jump_prev bug

### ISSUE THREAD

**Issue by EvgeniyRRU** [nvimdev/lspsaga.nvim#1052]
### Describe the bug

When I try to jump to prevous/next diagnostic (by my onw keymap, based on README) error occurs. 
<img width="1609" alt="lsp_saga_bug_01" src="https://user-images.githubusercontent.com/3672367/235629528-1e7b9216-43d5-4020-b28f-9c6509ddae00.png">

I found broken commit via `git bisec`
<img width="966" alt="lsp_saga_bisec" src="https://user-images.githubusercontent.com/3672367/235629698-c1ccb9af-00b7-43bf-ad0f-a8fb1babb166.png">

Broken commit is
`298009c345d1d519d7b6e60013817bbf549c19bc`

### Steps to reproduce

Just try to jump to prev/next diagnostic place.

### Expected behavior

Work wothout any bugs

### Neovim version (nvim -v)

0.9.0

### lspsaga commit

298009c345d1d519d7b6e60013817bbf549c19bc

### Terminal name/version

tmux/kitty

**Comment by glepnir** [comment]
provide min code . I can't reproduce .

**Comment by EvgeniyRRU** [comment]
Hello, do you mean config code?

**Comment by glepnir** [comment]
language code. it works for me always. need a wrong to reproduce .

**Comment by EvgeniyRRU** [comment]
Well
```typescript
import React from 'react';
import { ThemeProvider } from 'theming';
import { SnackbarProvider } from 'notistack';

import GraphqlProvider from '@components/GraphqlProvider';
import LayoutContextProvider from '@components/Layout/ContextProvider';


import theme from './theme';

type Props = {
  issues?: string;
  positionId?: string;
};

const App = (props: Props) => {
  const { issues, positionId } = props;

  return (
    <ThemeProvider theme={theme}>
      <GraphqlProvider>
        <SnackbarProvider
          maxSnack={3}
          anchorOrigin={{ vertical: 'top', horizontal: 'right' }}
        >
          <LayoutContextProvider
            issuesIdsFromAttr={issues}
            positionId={positionId}
          />
        </SnackbarProvider>
      </GraphqlProvider>
    </ThemeProvider>
  );
};

export default App;
```

<img width="582" alt="apptsx" src="https://user-images.githubusercontent.com/3672367/235634575-4f8113aa-6f59-43ae-901f-305e63e12c22.png">

**Comment by glepnir** [comment]
just test with my react project it works fine.  the server you configed for react is what ? in my env just tsserver.

![test](https://user-images.githubusercontent.com/41671631/235636570-807f5a5e-9b53-4770-b866-70e3643706e0.gif)

**Comment by EvgeniyRRU** [comment]
Here my lsp config:

```lua
local map = require('utils').map

local nvim_lsp = require('lspconfig')
local on_attach = function(client, bufnr)
  vim.api.nvim_buf_set_option(bufnr, 'omnifunc', 'v:lua.vim.lsp.omnifunc')
end


local lsp_flags = {
  -- This is the default in Nvim 0.7+
  debounce_text_changes = 150,
}

nvim_lsp.pyright.setup{
    on_attach = on_attach,
    flags = lsp_flags,
}
nvim_lsp.tsserver.setup{
    on_attach = on_attach,
    flags = lsp_flags,
}
nvim_lsp.rust_analyzer.setup{
    on_attach = on_attach,
    flags = lsp_flags,
    -- Server-specific settings...
    settings = {
      ['rust-analyzer'] = {}
    }
}
nvim_lsp.eslint.setup{
    on_attach = on_attach,
    flags = lsp_flags,
}
```
Utils:
```lua
local M = {}

function M.map(mode, lhs, rhs, opts)
    local options = { noremap = true }
    if opts then
        options = vim.tbl_extend('force', options, opts)
    end
    vim.keymap.set(mode, lhs, rhs, options)
end

return M
```

**Comment by glepnir** [comment]
looks like same ? I also use eslint and tsserver it works fine for me . can you create a simple code snippet that can reproduce this error ? then i can use it on my local for test.

**Comment by EvgeniyRRU** [comment]
https://github.com/EvgeniyRRU/dotfiles - my nvim config. Maybe I make some errors?

**Comment by EvgeniyRRU** [comment]
@glepnir Thank you for assistance. I found culprit. It was a incorrect `nvim_lsp` config. 
```lua
local lsp_flags = {
  debounce_text_changes = 150, -- I deleted this line and all works fine.
}
```

I suppose it was something like race condition and hard to reproduce and diagnostic.
