### ISSUE TITLE
Noisy "No code actions available" notifications on diagnostic jumps

### ISSUE THREAD

**Issue by taketwo** [nvimdev/lspsaga.nvim#1053]
### Describe the bug

When jumping to the next diagnostic using `diagnostic_jump_next', an "INFO" notification is created if there are no code actions available. Arguably, this is not a particularly useful notification, given that the user anyway sees that there are no actions in the diagnostic popup. Moreover, if a fancy notification visualization plugin is configured (e.g. nvim-notify), then jumping over diagnostics without actions results in lots of visual noise:

![image](https://user-images.githubusercontent.com/1241736/235709725-59ebcc22-3d5a-4f48-bd71-90968fc353e9.png)
 

### Steps to reproduce

Open a buffer with diagnostics without code actions and jump through them.

### Expected behavior

I'd expect the notification to either have DEBUG level, or not exist at all.

### Neovim version (nvim -v)

nightly

### lspsaga commit

f576fae

### Terminal name/version

tmux-3.3a

**Comment by taketwo** [comment]
Thanks for the quick resolution; the notifications are gone. Unfortunately, with your last commit the early return does not happen anymore, leading to an empty "Actions" list in the diagnostic popup.

Before:

![image](https://user-images.githubusercontent.com/1241736/235855367-fcd843aa-6f26-4c33-8e4f-06f895cd5bd3.png)

After:

![image](https://user-images.githubusercontent.com/1241736/235855521-d81a6533-d78b-4578-a1a4-5a3e23d8d29e.png)

**Comment by glepnir** [comment]
should be fixed . update.

**Comment by taketwo** [comment]
Works as expected now, thank you!

**Comment by taketwo** [comment]
It looks like https://github.com/nvimdev/lspsaga.nvim/commit/a17c975ac2eaa96736458d0a2cdd6abeb8f7811f undid the fixes and caused a regression to the old behavior. Could you please re-apply the fix?

https://github.com/nvimdev/lspsaga.nvim/blame/adfd5533e4e5627f74bc9896ca8936cede3a26ce/lua/lspsaga/codeaction/init.lua#L194-L197
