### ISSUE TITLE
Using 'goto_definition' in Java results in an error.

### ISSUE THREAD

**Issue by iamxiao01** [nvimdev/lspsaga.nvim#1056]
### Describe the bug

Error executing vim.schedule lua callback: ...te/pack/lazy/opt/lspsaga.nvim/lua/lspsaga/defin
ition.lua:333: Cursor position outside buffer
stack traceback:
        [C]: in function 'nvim_win_set_cursor'
        ...te/pack/lazy/opt/lspsaga.nvim/lua/lspsaga/definition.lua:333: in function 'handler
'
        ...plications/nvim-macos/share/nvim/runtime/lua/vim/lsp.lua:1392: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>

### Steps to reproduce

<cmd>Lspsaga goto_definition<CR>

### Expected behavior

The location of the jump's definition.

### Neovim version (nvim -v)

v0.9.0-dev-1175+g89a525de9

### lspsaga commit

76696be

### Terminal name/version

Alacritty  v0.11.0

**Comment by glepnir** [comment]
can you provide a min java code?

**Comment by iamxiao01** [comment]
public class Demo {
  public static void main(String[] args) {
    int i1 = 100;

    System.out.println(i1);
  }
}

With the cursor hovering over 'System', execute 'goto_definition'

**Comment by glepnir** [comment]
which java server you used ? nvim-jdtls or lspconfig jdtls

**Comment by glepnir** [comment]
I can't reproduce with your min code.

**Comment by iamxiao01** [comment]
> which java server you used ? nvim-jdtls or lspconfig jdtls . I get an empty response with lspconfig jdtls on `System` word
