### ISSUE TITLE
Outline not working with rescript project

### ISSUE THREAD

**Issue by ashton** [nvimdev/lspsaga.nvim#1057]
### Describe the bug

Nothing happens using the `Lspsaga outline` command in a Rescript project.

If the command is executed again the message `[lspsaga.nvim] there is already a request for outline please wait` shows in the status line. 

### Steps to reproduce

Using rescriptls as language server, run `Lspsaga outline` in a rescript file with any kind of data inside.

### Expected behavior

The outline to shows up

### Neovim version (nvim -v)

0.9.0 release

### lspsaga commit

76696bed4397c3b58563c246dc1f7856ed4af023

### Terminal name/version

Iterm 2 in macos Ventura

**Comment by glepnir** [comment]
does it works well with other projects in your local ?
