### ISSUE TITLE
Code actions get stuck (due to new preview window)

### ISSUE THREAD

**Issue by textzenith** [nvimdev/lspsaga.nvim#1058]
### Describe the bug

I've just had to restart Neovim completely due to an unrecoverable issue with Lspsaga.

The good news is that it shouldn't be too difficult to fix!

I'm working in Dart on a Flutter project. I've noticed that Lspsaga has a nice new feature that kicks in with code actions — when you a ready to perform a code action, there's a little preview window that pops up showing what the effects of the action will be.

It's nice, but the few bugs in this new system need dealing with:

Issues:

1) When the main "code actions" window is closed *manually* (e.g. using `<C-w>q`) , this popup window persists.

Desired behaviour: It should be closed along with the code action window.

**Bonus feature request**: Let's have the ability to cancel code actions quickly and easily  by pressing `q`, similar to many other popup windows in the Neovim ecosystem. Maybe  by`<Esc>` as well.

(It's very important to be able to close the code action window quickly as often the code action you expect to see is not available. This is something I need several times per hour of work)

2) Once the secondary popup is stuck hovering solo over my screen, there's no way to close it—the window is unselectable.

Desired behaviour: I'm sure the fact that the window is unselectable is desired. Cause this window to sync with the main code actions window and this problem disappears. However, it's extremely disruptive and difficult to get rid of in its current state.

3) After aborting a code action this way, the code action interface is unusable Any attempts to use a code action with the same server return an error message: `[lspsaga.nvim] there is already a code action request please wait`

Desired behaviour: It should be extremely hard to reach this state using normal LSP usage. While fixing the popup window problem may solve this, I can't really think of a case where a code action request or return could legitimately get 'stuck' save for the UI being left open by the user.

**Bonus feature request**: Some kind of `Lspsaga reset` command that would close all windows and reset Lspsaga to its default state in case of such an emergency

### Steps to reproduce

See above — closing the code action window while leaving the its sibling 'preview' window open.

### Expected behavior

See above — Lspsaga shouldn't get in any kind of 'stuck' state.

### Neovim version (nvim -v)

0.9

### lspsaga commit

main: 76696be chore(doc): auto generate docs

### Terminal name/version

kitty

**Comment by glepnir** [comment]
can you try the ref branch . and test this ? I think it fixed in ref branch. note this branch not complete. lots of code will change  and maybe is broken change. so not sugeest use this branch daily just for test this behavior

**Comment by glepnir** [comment]
the preview window should be auto closed follow main action window.

**Comment by textzenith** [comment]
Yes, it's only if you manually close the window with `<C-w>q` that it stays open, I'll quickly check the 'ref' branch

**Comment by textzenith** [comment]
> can you try the ref branch . and test this ? I think it fixed in ref branch.

Yes, with the new functionality in the ref branch, I can continue using Neovim even if I screw up and leave the second window running — doing `Lspsaga code_action` cleans up the old window and starts a new action, without getting stuck!

The secondary window staying open is a minor issue — maybe I'll see if I can fix it one day.

I'lll see if I can speed up the `q` shortcut on my configuration by removing the other keymaps.
