### ISSUE TITLE
<CR> not working for lsp_finder expand_or_jump

### ISSUE THREAD

**Issue by SimonEggert** [nvimdev/lspsaga.nvim#1059]
### Describe the bug

After a recent lspsaga update the enter key does not open the selected files by default anymore. This might be related to https://github.com/nvimdev/lspsaga.nvim/issues/944 and https://github.com/nvimdev/lspsaga.nvim/issues/1033.

I tried to adjust the config and set the mapping explicitly, but it doesn't work for me. Other mappings I define for the finder work just fine.

### Steps to reproduce

```lua
require 'lspsaga'.setup {
  finder = {
    expand_or_jump = '<CR>'
  }
}
```

### Expected behavior

Enter should open the selected file in the finder window.

### Neovim version (nvim -v)

0.9.0

### lspsaga commit

0.2.3 76696bed4397c3b58563c246dc1f7856ed4af023

### Terminal name/version

wezterm 20230408-112425-69ae8472

**Comment by glepnir** [comment]
```lua
finder = {
    keys = {
       expand_or_jump ='<CR>
```
