### ISSUE TITLE
Highlighting of diagnostic_jump_[prev/next]

### ISSUE THREAD

**Issue by clbrunet** [nvimdev/lspsaga.nvim#1060]
### Describe the bug

The window opened when using diagnositc_jump_* looks like this :
![Window](https://github.com/nvimdev/lspsaga.nvim/assets/53996617/3a1dbb00-8951-4955-bdea-c27b1d258539)

Does the problem count as coming from my theme, or does lspsaga's use of the hl group 'DiagnosticError' for the border and line separator need to be changed?

Configuring `diagnostic.border_follow = false` in the setup fix the border but the line separator between the error and the code actions is still undercurled / ugly.

### Steps to reproduce

Use the theme from https://github.com/sainnhe/gruvbox-material.
Launch nvim in a file with lsp errors.
:Lspsaga diagnostic_jump_next

### Expected behavior

The border and the line seperator i(f a code_action is possible) are undercurled.

### Neovim version (nvim -v)

v0.9.0

### lspsaga commit

76696bed4397c3b58563c246dc1f7856ed4af023

### Terminal name/version

# GNOME Terminal 3.44.0 using VTE 0.68.0 +BIDI +GNUTLS +ICU +SYSTEMD

**Comment by glepnir** [comment]
your colorscheme make `DiagnosticError` have undercurl and no foreground color .  override these diagnositc group or change colorscheme.
