### ISSUE TITLE
Display LateX math formula on hover doc

### ISSUE THREAD

**Issue by zippeurfou** [nvimdev/lspsaga.nvim#1066]
**Is your feature request related to a problem? Please describe.**
I would like to be able to display math formula when I hover the documentation.
I am not sure this comes from this plugin or another one but I am starting here just in case. Please redirect me.
For example:
https://github.com/scikit-learn/scikit-learn/blob/364c77e04/sklearn/metrics/pairwise.py#L837-L839 has a math formula. I would love to be able to display it using like this plugin does https://github.com/jbyuki/nabla.nvim. I am not sure how to go about this.

**Comment by glepnir** [comment]
looks great. I need do some check how it works then implement it .

**Comment by glepnir** [comment]
hmm sorry for late reply I check it out. it's hard to integration to lspsaga hover. and lsp can't handle it .

**Comment by zippeurfou** [comment]
thanks @glepnir all good.
I wonder if there is an issue we could open somewhere (neovim repo?) to come up to a potential solution. Would you know?
