### ISSUE TITLE
Using hover_doc problem with treesitter conceal

### ISSUE THREAD

**Issue by theRhasoldy** [nvimdev/lspsaga.nvim#1075]
### Describe the bug

hover_doc issues an error and the floating window shows the markdown not concealed 
![image](https://github.com/nvimdev/lspsaga.nvim/assets/77510922/62f7ab49-ff01-494a-af73-e185a9074b68)

`Error: attempt to call field 'set' (a nil value)` is issued

I think `vim.treesitter.query.set()` is deprecated and should instead use `vim.treesitter.query.set_query()`

### Steps to reproduce

`:LspSaga hover_doc` on relevant text

### Expected behavior

![image](https://github.com/nvimdev/lspsaga.nvim/assets/77510922/8851e5ea-d359-4b42-9545-506281afc905)

hover_doc window shows with correct highlighting and concealing

### Neovim version (nvim -v)

NVIM v0.9.0-dev-1223+g3e8955094

### lspsaga commit

426df99

### Terminal name/version

kitty

**Comment by DanielVolchek** [comment]
Did you figure out how to fix this? I'm getting this error as well

**Comment by theRhasoldy** [comment]
It fixed itself right after I uploaded the issue lol, I think when i
updated neovim or something

**Comment by glepnir** [comment]
with latest treesitter version ?
