### ISSUE TITLE
Hover bug when buffer have one more servers and both have hover request  resonse

### ISSUE THREAD

**Issue by glepnir** [nvimdev/lspsaga.nvim#1079]
### Describe the bug

as trace of #865

### Steps to reproduce

```lua
vim.opt.rtp:append('~/Workspace/lspsaga.nvim')
vim.opt.rtp:append('~/Workspace/nvim-lspconfig')
vim.opt.rtp:append('~/.local/share/nvim/lazy/nvim-treesitter/')
require('nvim-treesitter').setup({})

local lspconfig =require('lspconfig')
lspconfig.tsserver.setup({})
lspconfig.custom_elements_ls.setup({})

local keymap = vim.keymap.set
require("lspsaga").setup({})
keymap("n", "K", "<cmd>Lspsaga hover_doc<CR>")
```

### Expected behavior

works fine

### Neovim version (nvim -v)

head

### lspsaga commit

ref

### Terminal name/version

kitty

**Comment by glepnir** [comment]
fix in 0.3.0 . thanks @llllvvuu  fore report.

**Comment by llllvvuu** [comment]
Yeah if you hack in the lines
```
diff --git a/lua/lspsaga/hover.lua b/lua/lspsaga/hover.lua
index 680088b..6d5044f 100644
--- a/lua/lspsaga/hover.lua
+++ b/lua/lspsaga/hover.lua
@@ -139,6 +139,9 @@ function hover:open_floating_preview(res, option_fn)
     },
     bufnr = self.preview_bufnr,
   }
+  if self.preview_winid and api.nvim_win_is_valid(self.preview_winid) then
+    api.nvim_win_close(self.preview_winid, true)
+  end
   _, self.preview_winid = window.create_win_with_border(contents_opt, float_option)
   vim.bo[self.preview_bufnr].modifiable = false
```

You can see it's because the `preview_winid` doesn't get cleaned up (of course, this is not the ideal solution; have to come up with the right UX haha)

**Comment by glepnir** [comment]
because there use `lsp.buf_request` it run with both clients. and create window in callback . two ways here 
1. use `lsp.buf_request_all` get all result then handle it.
2. check already have a preview window in callback. then append result to a exist preview window. this way need check the preview window height with vim window height.
