### ISSUE TITLE
Error when executing Hover

### ISSUE THREAD

**Issue by TheodorRene** [nvimdev/lspsaga.nvim#1081]
### Describe the bug

This could be related to #1079, but it does not mention an error message with this form:

```
Error executing vim.schedule lua callback: ...ite/pack/packer/start/lspsaga.nvim/lua/lspsaga/hover.lua:155: attempt to call fi
eld 'set' (a nil value)
stack traceback:
        ...ite/pack/packer/start/lspsaga.nvim/lua/lspsaga/hover.lua:155: in function 'open_floating_preview'
        ...ite/pack/packer/start/lspsaga.nvim/lua/lspsaga/hover.lua:324: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1390: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

It is a Typescript project and I'm using Copilot, tsserver, tailwindcss and eslint as client attached to the lsp buffer. 

When I dismiss this error by pressing enter, the hover window is shown but with no rendering enabled. To dismiss the hover I have to enter the window and `:q` it. 

![image](https://github.com/nvimdev/lspsaga.nvim/assets/36312737/4fda3778-430a-4bba-85b2-c4d0c321c457)

### Steps to reproduce

Hover 

### Expected behavior

Hover window works

### Neovim version (nvim -v)

NVIM v0.9.0-dev-843+g860fea1a3

### lspsaga commit

01b9633aefd010f272d6c7e3d8293c44fcfe7696

### Terminal name/version

Alacritty

**Comment by glepnir** [comment]
because you build neovim with old code . use release stable neovim 0.9 or pull latest code of neovim build from 0.10
