### ISSUE TITLE
Invalid opt.height for action_preview

### ISSUE THREAD

**Issue by haru02w** [nvimdev/lspsaga.nvim#1082]
### Describe the bug

the function 
```lua
window.create_win_with_border(content_opts, opt)
```
is called with opt.height with value less then zero, so it get an error

### Steps to reproduce

- open neovim
- resize terminal window with very few lines
- run :Lspsaga code_actions<cr>

### Expected behavior

Do not show the action_preview

### Neovim version (nvim -v)

0.9.0

### lspsaga commit

01b9633

### Terminal name/version

foot 1.14.0

**Comment by haru02w** [comment]
I make [this](https://github.com/nvimdev/lspsaga.nvim/pull/1083) PR but I'm really new at lua, so correct me if I'm wrong

**Comment by glepnir** [comment]
that's a hack way. we should find why it will cause the height less than 0 . so lsp response is necessary. in next version we have a debug module can make it find bug easily . but for current version need some debug print by manually . please provide a reproduce step then i can reproduce it on my local

**Comment by haru02w** [comment]
Seems like it just gets wrong when cmdline=0 is set

**Comment by glepnir** [comment]
should be not related  . can you provide a reproduce step. i mean how you trigger this error

**Comment by haru02w** [comment]
> should be not related . can you provide a reproduce step. i mean how you trigger this error

1. open neovim in a terminal,
2.  resize the terminal window to be really small (like 4 lines),
3.  run `:Lspsaga code_action<cr>`

**Comment by haru02w** [comment]
when window is with exact 6 lines
![image](https://github.com/nvimdev/lspsaga.nvim/assets/74968611/be612de6-2677-4efa-9649-d24a3d03d346)

**Comment by glepnir** [comment]
looks like no enough space for code action preview window so through an errror.

**Comment by haru02w** [comment]
![image](https://github.com/nvimdev/lspsaga.nvim/assets/74968611/076a1224-adbf-4253-8ae0-8643031195cc)
![image](https://github.com/nvimdev/lspsaga.nvim/assets/74968611/0928b485-32c0-4aaa-bc3b-3b640165e009)
I'm still getting this error 🥲

**Comment by glepnir** [comment]
provide reproduce step and example min code
