### ISSUE TITLE
Using existing windows to open definition/reference/etc.

### ISSUE THREAD

**Issue by farzadmf** [nvimdev/lspsaga.nvim#1085]
**Is your feature request related to a problem? Please describe.**
It's not really a "problem", per se, but mostly, a nice-to-have feature.

**Describe the solution you'd like**
It happens to me a lot that I have something like this:
- I have 2 or 3 splits open
- In one of the splits, I open the peek definition window (or the finder window etc.)
- I want to open definition/reference etc, but:
  - I do not want to open it in the split I'm currently in
  - I want to open it in one of the other splits that I have open.

**Describe alternatives you've considered**
Right now, this is what I do:
- I go to the split I want to use for definition/reference
- I close it
- I go back to the split I want to see the definition for
- I then choose to open in horizontal/vertical split and `lspsaga` creates a new one

What I have in mind is something like `neo-tree`'s "open with window picker", but in the context of `lspsaga` and "open in split" for definitions/references

**Additional context**
Please let me know if what I descirbed makes sense, or if you need things such as screenshots

**Comment by glepnir** [comment]
make sense . more work to do then.

**Comment by farzadmf** [comment]
Great, really looking forward to this since, as far as I know, there isn't any plugin doing that.

And I REALLY like using `lspsaga` and this feature, if implemented, would make it even more amazing

**Comment by glepnir** [comment]
This behavior can only be used by certain people. Some people don't like to use windows that already have splits. Will break some of their habits. So the final implementation could be a command argument or an option  like `Lspsaga definition layout=normal_reuse`

**Comment by farzadmf** [comment]
Yeah, totally agree, I think the current behavior should stay as is, as people are already using it, and of course there are use cases for it

I really like the idea of an additional argument, but one thing:
Normally we configure the mappings in the `config`, like:
```lua
definition = {
  keys = {
    edit = '...',
    -- ...
  }
}
```

So, there could be additional things we can configure here, corresponding to the new behavior.

And, up to you, but I find `normal_reuse` to be a bit ambiguous, where, at first sight, you don't exactly know what it's supposed to represent

**Comment by glepnir** [comment]
just a draft name . if you have better name I will consider use it   :)

**Comment by farzadmf** [comment]
Quick thing that comes to my mind, something like `use_existing` maybe? (just a suggestion of course)

**Comment by farzadmf** [comment]
@glepnir may I ask why this one was closed as completed? I don't seem to be able to find anything related to "use an existing window" in the docs.

Probably I missed something?

**Comment by glepnir** [comment]
nope maybe i forget

**Comment by glepnir** [comment]
use `++inexist` flag. in command

**Comment by glepnir** [comment]
yep you need if you want split/vsplit in an exist window.

**Comment by farzadmf** [comment]
Hey @glepnir , I really appreciate you implementing this, but don't you think it would be nicer to have this as a `keys` configuration?

With the way it's set up right now, I need to think in advance; basically a thought process would be something like this:

"OK, I'm gonna open the go to definition window, but will I need to use existing split or create a new one? ... OK, gonna create a new one when going to the definition, so use the configured `keys` option, but then ... I'm like: Oh shoot, I meant to use an existing one, so I have to close and use my `vim.keymap.set` binding"

If this feature is similar to the other `keys`, I can make the decision "on the fly"; open the window and then decide easily whether to use existing split or create a new one

**Comment by farzadmf** [comment]
@glepnir that's nice, but still a couple of issues:
- The setting seems to be only applicable to the `finder` it seems (how about `definition` for example?)
- The setting is still a "global" one, meaning that it'd affect every `finder` that I open, and, in case I need the other behavior, I need to modify my config to set that option to `false` or `true`

Isn't it possible to have it in `keys`, say something like:
```lua
require('lspsaga').setup({
  definition = {
    keys = {
      -- ... existing options (edit, vsplit, split, etc.)
      inexist = '...', -- <-- new one
    }
  },
  finder = {
    keys = {
      -- ... existing options (edit, vsplit, split, etc.)
      inexist = '...', -- <-- new one
    }
  }
})
```

This way, there's no need to configure anything globally: I open `finder` or `definition`, and:
- If I want to open in a new split, I use the `split` and `vsplit` bindings
- If I want to use an exsiting window, I use the `inexist` binding

**Comment by glepnir** [comment]
create a new feature request of this new global option .

**Comment by farzadmf** [comment]
Sounds good, will do once I get a chance
