### ISSUE TITLE
showing error message when trying executing Lspsaga hover_doc

### ISSUE THREAD

**Issue by syukronarie** [nvimdev/lspsaga.nvim#1086]
### Describe the bug

When executing the Lspsaga hover_doc command, an error message is displayed before the hover documentation is shown correctly. The error message indicates an issue with a Lua callback in the lspsaga.nvim plugin.

### Steps to reproduce

Bug Reproduction Steps:

Latest lspsaga.nvim plugin installed.

1. Open a file that is compatible with the Language Server Protocol (LSP).
2. Move the cursor to a word or symbol in the file.
3. Execute the Lspsaga hover_doc command (you can use the corresponding keybinding if available).
4. Observe the error message displayed in the editor.

<img width="1199" alt="Screenshot 2023-05-26 at 7 36 01 PM" src="https://github.com/nvimdev/lspsaga.nvim/assets/36725290/dd7f950b-5b6c-46a0-bb40-bf687e4d12b4">

### Expected behavior

When executing the Lspsaga hover_doc command, the hover documentation should be shown correctly without any preceding error message. The plugin should handle the Lua callback properly and display the floating preview without any issues.

### Neovim version (nvim -v)

0.9.0-dev-869+9964a205a

### lspsaga commit

de4e632e259615dac7231392db02b5f4483751de

### Terminal name/version

iTerm2

**Comment by glepnir** [comment]
duplicate #1081
