### ISSUE TITLE
hover_doc window no close

### ISSUE THREAD

**Issue by xaotag** [nvimdev/lspsaga.nvim#1087]
### Describe the bug

https://github.com/nvimdev/lspsaga.nvim/assets/40427877/7d7ca246-1330-4abc-ba44-d92a38e3901f

### Steps to reproduce

```lua 
local saga = require('lspsaga')
saga.setup({
  symbol_in_winbar = {enable = false},
  ui = {border = 'single', colors = {normal_bg = 'NONE'}, title = false}
})

keymap("n", "<leader>k", ":Lspsaga hover_doc<CR>", opts)

```

### Expected behavior

close window

### Neovim version (nvim -v)

NVIM v0.10.0-dev-383+gaa9d46b672

### lspsaga commit

9265d3ab, ref branch

### Terminal name/version

wezterm

**Comment by glepnir** [comment]
close duplicate #1079
