### ISSUE TITLE
Add an option to show outline window in a popup

### ISSUE THREAD

**Issue by defr0std** [nvimdev/lspsaga.nvim#1088]
**Is your feature request related to a problem? Please describe.**
Sometimes the outline window shown in the split is not ideal. For example, I have 4 vertical splits open with different files, and I need to see an outline for the second split. The outline appears somewhere on the right, far from the original context. Now I need to navigate back and forth between the code split and the outline split, which is not convenient.

**Describe the solution you'd like**
An option to show the outline as a floating popup window. The window should be displayed over the original split with code.

**Comment by glepnir** [comment]
makse sense . easy to implement .
