### ISSUE TITLE
Separate highlight groups for winbar separator of folder and separator of filename and object within files

### ISSUE THREAD

**Issue by icyrainz** [nvimdev/lspsaga.nvim#1089]
**Is your feature request related to a problem? Please describe.**
I want to add custom highlight to clearly show the breadcrumbs of folder path and items within the file. Right now, lspsaga only has 1 highlight group which is SagaWinbarSep.

**Describe the solution you'd like**
Add additional separator type. Maybe separator_folder and separator_file_items, each with their own highlight group.

Right now my custom background looks ugly:
<img width="585" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/2420181/129258f9-817e-4a62-bcc5-3dbcd3fde13b">

**Comment by glepnir** [comment]
`SagaFilename` `SagaFolderName` if not work please let me know :)

**Comment by icyrainz** [comment]
Does not work for me:

![image](https://github.com/nvimdev/lspsaga.nvim/assets/2420181/35fc5ec5-0fdf-4624-b0ea-95f67856f6b6)

And SagaFilename highlight group does not exist in my 'Telescope highlights' list.

**Comment by glepnir** [comment]
sry it's `SagaWinbarFilename`

**Comment by icyrainz** [comment]
If I'm only using SagaWinbarFoldername, it's like this:
![image](https://github.com/nvimdev/lspsaga.nvim/assets/2420181/7eab3ea6-86b4-42a1-aa94-8c384cce9e32)

What I mean is I only want to change the separator in the folder part and not the separator on the file sub-items part.

**Comment by glepnir** [comment]
you  mean you want change before 3 separator highlight right ? not all ?

**Comment by icyrainz** [comment]
Correct. Right now the 3 separators on the left have same highlight group as the last separator so there is no way to separate them. It would be great visually if we can distinguish the folder part and the file & file sub-items.

**Comment by glepnir** [comment]
okay .

**Comment by glepnir** [comment]
use `require('lspsaga.symbol.winbar').get_bar` do it on your local
