### ISSUE TITLE
Outgoing calls functionality is buggy

### ISSUE THREAD

**Issue by npupko** [nvimdev/lspsaga.nvim#1094]
### Describe the bug

The current state of outgoing calls function makes it impossible to use.

Preview:

https://github.com/nvimdev/lspsaga.nvim/assets/5938539/e134772d-c75c-4003-a22c-97d59cd70b73

### Steps to reproduce

Open project with large history for outgoing calls

1. Enter command `Lspsaga outgoing_calls`
2. Press `u` on different entries multiple times (At this time highlighting should already be broken)
3. Press `o` to jump on floating file
4. Press `c-W, K` to jump outside floating window (At this time it's impossible to hide window)
5. If I enter `Lspsaga outgoing_calls` again and press Q it becomes even worse:

<img width="961" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/5938539/4c853c78-0e8c-4c6e-8479-0153004b9893">

### Expected behavior

1. Enter command `Lspsaga outgoing_calls`
2. Press `u` on different entries multiple times (At this time highlighting still working)
3. Press `o` to jump on the floating file
4. Press `c-W, K` to jump outside the floating window (At this time it's possible to hide the window)

### Neovim version (nvim -v)

NVIM v0.9.1 Build type: Release LuaJIT 2.1.0-beta3

### lspsaga commit

c475ace

### Terminal name/version

Aalcritty 0.12.1

**Comment by revelationnow** [comment]
I'm seeing the same problem, in its current state the outgoing calls functionality is unusable. Is anyone looking into it?

**Comment by glepnir** [comment]
a full rewrite in next version this will solved.
