### ISSUE TITLE
Attempt to call field 'set' (a nil value)

### ISSUE THREAD

**Issue by radovanne3** [nvimdev/lspsaga.nvim#1095]
### Describe the bug

Hello, 
I am trying to integrate Lspsaga with lsp zero package
I have installed markdown and markdown_inline parsers
I have treesitter and treesitter-cli
:healtcheck is okey

When I run Lspsaga lsp_finder everything works as intended but when I try hover_doc I get the following error:

Error executing vim.schedule lua callback: ...local/share/nvim/lazy/lspsaga.nvim/lua/lspsaga/hover.lua:155: attempt to call field 'set' (a nil value)                                                      
stack traceback:                                                           
        ...local/share/nvim/lazy/lspsaga.nvim/lua/lspsaga/hover.lua:155: in function 'open_floating_preview'
        ...local/share/nvim/lazy/lspsaga.nvim/lua/lspsaga/hover.lua:324: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1390: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
        

### Steps to reproduce

Here is my config
`local lsp = require("lsp-zero")

lsp.preset("recommended")

lsp.ensure_installed({
  "tsserver",
  "rust_analyzer",
  "pylsp",
  "lua_ls",
  "jsonls",
  "html",
  "cssls",
  "clojure_lsp"
})
-- Fix Undefined global 'vim'
lsp.nvim_workspace()

local cmp = require('cmp')
local cmp_select = {behavior = cmp.SelectBehavior.Select}
local cmp_mappings = lsp.defaults.cmp_mappings({
  ['<C-k>'] = cmp.mapping.select_prev_item(cmp_select),
  ['<C-j>'] = cmp.mapping.select_next_item(cmp_select),
  ['<C-f>'] = cmp.mapping.scroll_docs(-4),
  ['<C-d>'] = cmp.mapping.scroll_docs(4),
  ['<Tab>'] = cmp.mapping.confirm({ select = true }),
  ['<C-e>'] = cmp.mapping.abort(),
  ["<C-Space>"] = cmp.mapping.complete(),
})

-- cmp_mappings['<Tab>'] = nil
-- cmp_mappings['<S-Tab>'] = nil

lsp.setup_nvim_cmp({
  mapping = cmp_mappings,
  sources = {
    { name = 'buffer' },
    { name = 'path' },
}})

lsp.set_preferences({
    suggest_lsp_servers = false,
    sign_icons = {
        error = 'E',
        warn = 'W',
        hint = 'H',
        info = 'I'
    }
})

lsp.on_attach(function(_, bufnr)
  local opts = {buffer = bufnr, remap = false}

  vim.keymap.set("n", "gd", "<cmd>Lspsaga lsp_finder<CR>", opts)
  vim.keymap.set("n", "K", "<cmd>Lspsaga hover_doc<CR>", opts )
  -- vim.keymap.set("n", "gd", function() vim.lsp.buf.definition() end, opts)
  -- vim.keymap.set("n", "K", function() vim.lsp.buf.hover() end, opts )
  -- vim.keymap.set("n", "<leader>ws", function() vim.lsp.buf.workspace_symbol() end, opts)
  -- vim.keymap.set("n", "<leader>fd", function() vim.diagnostic.open_float() end, opts)
  -- vim.keymap.set("n", "[d", function() vim.diagnostic.goto_next() end, opts)
  -- vim.keymap.set("n", "]d", function() vim.diagnostic.goto_prev() end, opts)
  -- vim.keymap.set("n", "<leader>ca", function() vim.lsp.buf.code_action() end, opts)
  -- vim.keymap.set("n", "gD", function() vim.lsp.buf.references() end, opts)
  -- vim.keymap.set("n", "<leader>cr", function() vim.lsp.buf.rename() end, opts)
  -- vim.keymap.set("i", "<C-h>", function() vim.lsp.buf.signature_help() end, opts)
  -- vim.keymap.set('n', '<leader>q', vim.diagnostic.setloclist, { desc = 'Open diagnostics list' })
end)

lsp.setup()

vim.diagnostic.config({
    virtual_text = true
})

require("lspsaga").setup({
  preview = {
    lines_above = 0,
    lines_below = 10,
  },
  scroll_preview = {
    scroll_down = "<C-f>",
    scroll_up = "<C-b>",
  },
  request_timeout = 2000,
  lightbulb = {
    enable = false,
  },
})`

And the file where I install it:

`return {
  'VonHeikemen/lsp-zero.nvim',
  branch = 'v2.x',
  dependencies = {
    -- LSP Support
    {'neovim/nvim-lspconfig',
    dependencies = {{
      "glepnir/lspsaga.nvim",
      event = "LspAttach",
      -- config = function()
        --     require("lspsaga").setup({})
        -- end,
        dependencies = {
          {"nvim-tree/nvim-web-devicons"},
          --Please make sure you install markdown and markdown_inline parser
          {"nvim-treesitter/nvim-treesitter"}}
        }}},{
          'williamboman/mason.nvim',
          build = function()
            pcall(vim.cmd, 'MasonUpdate')
          end,
        },
        {'williamboman/mason-lspconfig.nvim'}, -- Optional

        -- Autocompletion
        {'hrsh7th/nvim-cmp'},     -- Required
        {'hrsh7th/cmp-nvim-lsp'}, -- Required
        {'L3MON4D3/LuaSnip'},     -- Required
        {'hrsh7th/cmp-path'},     -- Optional
        {'hrsh7th/cmp-buffer'},   -- Optional
      }}`

### Expected behavior

I expected it to work.. xD

### Neovim version (nvim -v)

0.9.0

### lspsaga commit

commit

### Terminal name/version

term

**Comment by glepnir** [comment]
close as duplicate https://github.com/nvimdev/lspsaga.nvim/issues/1081 please take a look at this
