### ISSUE TITLE
error on lsp_finder

### ISSUE THREAD

**Issue by zsmatrix62** [nvimdev/lspsaga.nvim#1097]
### Describe the bug

```
Error executing vim.schedule lua callback: Vim:E325: ATTENTION
stack traceback:
        [C]: in function 'bufload'
        ...ocal/share/nvim/lazy/lspsaga.nvim/lua/lspsaga/finder.lua:256: in function 'create_finder_data'
        ...ocal/share/nvim/lazy/lspsaga.nvim/lua/lspsaga/finder.lua:205: in function 'callback'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:2053: in function 'handler'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:1411: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

<img width="984" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/2951879/de55f6cb-0dc1-414f-b215-397e2855343b">

### Steps to reproduce

executing command: Lspsaga lsp_finder

### Expected behavior

no errors

### Neovim version (nvim -v)

NVIM v0.10.0-dev-b3d5138

### lspsaga commit

4f07545

### Terminal name/version

alacritty

**Comment by glepnir** [comment]
how do you trigger this error provide a step

**Comment by am79041** [comment]
I also got similar error. 
![lsp_finder](https://github.com/nvimdev/lspsaga.nvim/assets/70338712/4635b651-5fcb-4b3e-9720-5b92c19a52d6)
Terminal - Powershell
NVIM v0.9.0-dev

**Comment by glepnir** [comment]
error not same .for your issue your build with a too old commit. please try use the latest stable 0.9 or build with last commit is `0.10`

**Comment by am79041** [comment]
Thanks. It's working fine now after update.
