### ISSUE TITLE
Setting up lspsaga using opts instead of config with Lazy.nvim

### ISSUE THREAD

**Issue by lsig** [nvimdev/lspsaga.nvim#1101]
I was wondering why it is not possible to setup lspsaga using the opts property in Lazy.nvim. I feel
like using a function in the middle of the lazy config is much less clean than just using the opts property. 

What I am suggesting: 

![Screenshot 2023-06-17 at 18 04 20](https://github.com/nvimdev/lspsaga.nvim/assets/89947902/1a0e9e99-8eb4-47e3-b68c-781fbff429db)

How it looks now:

![Screenshot 2023-06-17 at 18 03 10](https://github.com/nvimdev/lspsaga.nvim/assets/89947902/7ee6fbd3-690f-42eb-b4f8-0d563421505a)

**Comment by MariaSolOs** [comment]
@lsig I'm able to setup `lspsaga` using `opts` ([here](https://github.com/MariaSolOs/dotfiles/blob/ea6bc00cb2b8571143f26f17c5370c738a852c7f/.config/nvim/lua/plugins/lspsaga.lua)'s my config). Are you getting any errors or what's the issue?

**Comment by lsig** [comment]
The problem seems to be something related to the require keyword or the catppuccing integrations. When I remove the kind = require("catpuccing...").custom_kind(). It works as expected. Thanks for showing me your config.

**Comment by MariaSolOs** [comment]
@lsig that’s because `lazy` will read all `ops` before loading anything, so `catppuccin` isn’t even defined by then. You can try using the callback version of `opts`.

**Comment by lsig** [comment]
Ahh I understand, thank you so much for your help! 👍
