### ISSUE TITLE
close_in_preview key not working in lsp_finder

### ISSUE THREAD

**Issue by MariaSolOs** [nvimdev/lspsaga.nvim#1103]
### Describe the bug

With the default configuration, pressing `<esc>` does nothing when inside the preview window of the finder.

### Steps to reproduce

1. In any applicable file, invoke the `:Lspsaga lsp_finder` command.
2. Press `p` to jump to the preview window.
3. Press `esc`. Notice how the window isn't closed.

### Expected behavior

As the documentation says, I expect `esc` to close all windows from the finder.

Also, when looking at the source code I discovered that the mapping is [just removed](https://github.com/nvimdev/lspsaga.nvim/blob/4f075452c466df263e69ae142f6659dcf9324bf6/lua/lspsaga/finder.lua#L922), but I didn't find a place where it is actually set (like it is done for the [other mappings](https://github.com/nvimdev/lspsaga.nvim/blob/4f075452c466df263e69ae142f6659dcf9324bf6/lua/lspsaga/finder.lua#L620)).

### Neovim version (nvim -v)

NVIM v0.10.0-dev-523+gbbb934e77-Homebrew

### lspsaga commit

4f07545

### Terminal name/version

iterm2 3.4.19

**Comment by glepnir** [comment]
oh thanks for report .there is missing a map for `close_all_in_preview` . will fix in next version .

**Comment by MariaSolOs** [comment]
Happy to help!

**Comment by glepnir** [comment]
because recently next version is full rewrite so most time I am working on it not main .sorry for this .  currently just need go back to main window press q .
