### ISSUE TITLE
Save all buffers affected by `rename`

### ISSUE THREAD

**Issue by alex35mil** [nvimdev/lspsaga.nvim#1105]
**Is your feature request related to a problem? Please describe.**
When I rename something across a project, I need to save all affected buffers manually.

**Describe the solution you'd like**
Provide an option to auto-save all affected buffers after renaming.

**Describe alternatives you've considered**
Providing an option to execute custom callback after the `rename` action.

**Comment by glepnir** [comment]
can support

**Comment by glepnir** [comment]
done in next version there have a new option `rename.auto_save` it will save all the buffers you opened after change.
