### ISSUE TITLE
Code Action doesn't work for C# with Omnisharp

### ISSUE THREAD

**Issue by shaksiper** [nvimdev/lspsaga.nvim#1107]
### Describe the bug

Code actions through lspsaga works for other languages except C# using Omnisharp.
Either through number selection or by <CR>
since I have it set like this.
```
	code_action = {
		num_shortcut = true,
		keys = {
			quit = "<ESC>",
			exec = "<CR>",
		},
	},
````

Code actions through telescope work just fine for all languages including C#, so I thought it might be an issue with lspsaga itself.

### Steps to reproduce

Go do a location with code action available.
`:Lspsaga code_action`
Select code action (by number shortcut or <CR>)

### Expected behavior

Code action applies

### Neovim version (nvim -v)

NVIM v0.10.0-dev-590+ge85e7fc7b

### lspsaga commit

4f075452c466df263e69ae142f6659dcf9324bf6 HEAD -> main

### Terminal name/version

kitty 0.28.1

**Comment by glepnir** [comment]
sry currently all lspsaga fully rewrite in next version so I don't fix main branch bug now. let's see what happen in next version.

**Comment by shaksiper** [comment]
Oh ok I see. That sounds like a difficult job, I respect that decision. 

Good luck, have a nice day

**Comment by glepnir** [comment]
keep it as trace thanks
