### ISSUE TITLE
Navigation in finder window randomly covered

### ISSUE THREAD

**Issue by mikehaertl** [nvimdev/lspsaga.nvim#1111]
### Describe the bug

Sometimes when I open the finder the navigation panel is covered by the preview:

![image](https://github.com/nvimdev/lspsaga.nvim/assets/675062/66f83906-55ad-4f71-91f2-1b6235606d6a)

### Steps to reproduce

No procedure as the problem seems to appear randomly. It even happens if I open the finder from the same method a couple of times.

### Expected behavior

The navigation panel should be visible. Here is the finder opened on the exact same method as above:
![image](https://github.com/nvimdev/lspsaga.nvim/assets/675062/3d7d6af8-d6f6-4544-83aa-6a2232b60ef7)

### Neovim version (nvim -v)

0.9.0 commit 040f14598

### lspsaga commit

4f07545

### Terminal name/version

Gnome Terminal 3.44.0

**Comment by glepnir** [comment]
see version3
