### ISSUE TITLE
Option to make the finder window fixed full screen at the bottom or top

### ISSUE THREAD

**Issue by mikehaertl** [nvimdev/lspsaga.nvim#1112]
**Is your feature request related to a problem? Please describe.**
The finder window often is too small especially if the original method is far to the right of the screen:
![image](https://github.com/nvimdev/lspsaga.nvim/assets/675062/8ad8fcfb-33ac-4e75-895b-1f94187af29b)

**Describe the solution you'd like**
Would be nice to have an option to put the results fixed at the bottom of the screen, with full width. The width of the navigation panel should also be configurable (e.g. 30%).

It should behave similar e.g. to this (file selector with preview, based on fzf plugin):

![image](https://github.com/nvimdev/lspsaga.nvim/assets/675062/544c1c59-17b4-4bd9-be34-e7e837a5f285)

**Additional context**

I see no advantage that the popup is always opened at the cursor position: The result window already contains your search term so you always know the search context.

**Comment by glepnir** [comment]
see https://github.com/nvimdev/lspsaga.nvim/pull/1108

**Comment by mikehaertl** [comment]
Hmm, so will this be "normal" layout then? 

To be honest the description [here](https://dev.neovim.pro/lspsaga/finder/) is not really clear:

> layout = 'float' available value is normal or float
>   * normal will use normal layout window priority is lower than command layout

I thinks it's also missing the option to configure sizes (height in %, size of left and right panel).

**Comment by glepnir** [comment]
you mean these options ?
```lua
  finder = {
    max_height = 0.5,
    left_width = 0.3,
}
```

**Comment by mikehaertl** [comment]
I don't know - there's not documentation for 0.3 yet?

I also just found that my request is the same as #985.

**Comment by mikehaertl** [comment]
> you mean these options ?

Sorry, it's documented on the URL I linked before :). So yes, that's probably what I missed.

**Comment by glepnir** [comment]
maybe some delay ?

![image](https://github.com/nvimdev/lspsaga.nvim/assets/41671631/b40de102-967b-4786-bafe-8f4a323ef70b)
