### ISSUE TITLE
Rename doesn't check if result.changes or if result.documentChanges

### ISSUE THREAD

**Issue by al-ce** [nvimdev/lspsaga.nvim#1114]
### Describe the bug

Hello! Prior to the rewrite, the `rename_handler_function` had this check for `result.changes` (appropriate for Lua) vs `result.documentChanges` (appropriate for Go and Python). Here it is in 4f07545

https://github.com/nvimdev/lspsaga.nvim/blob/4f075452c466df263e69ae142f6659dcf9324bf6/lua/lspsaga/rename.lua#L211C12-L235

I haven't taken a very deep look to see if you're handling this differently now, but it appears that we're only checking `result.changes` here (I noticed this when I tried to use the rename command today).

https://github.com/nvimdev/lspsaga.nvim/blob/1aad133f94c8c75bb498560b25d2579199cffd1d/lua/lspsaga/rename/init.lua#L170C1-L179

Rename works great for Lua but the window just closes without making the changes in Go or Python. This check for `documentChanges` exists in the rewrite elsewhere:

https://github.com/nvimdev/lspsaga.nvim/blob/1aad133f94c8c75bb498560b25d2579199cffd1d/lua/lspsaga/codeaction/preview.lua#L27C1-L40

Should it be added back in for the rename command? Other commands like go to definition, reference, finder, etc. work as expected in Python/Go. One final note, this behavior is the same on nightly (NVIM v0.10.0-dev-3119+ge27377e33) as it is in 0.9.1.

Thanks so much for saga! The documentation on the website is excellent.

### Steps to reproduce

Using a minimal LazyVim [starter config](https://github.com/LazyVim/starter), installing `pyright` or `pylsp` and `gopls` and `luals`. Then installing lspsaga using the default setup:

```lua
return {
  {
    "glepnir/lspsaga.nvim",
    lazy = false,
    config = true,
  },
}
```

Then executing `:Lspsaga rename` over functions, variables, etc.

### Expected behavior

Renaming of elements with LSPs that use `documentChanges` instead of `changes`. Example video below of expected behavior with Lua but not Python

https://github.com/nvimdev/lspsaga.nvim/assets/23170004/9fc631aa-67bb-4da2-8125-002fca30b498

### Neovim version (nvim -v)

NVIM v0.9.1

### lspsaga commit

a17c975

### Terminal name/version

kitty 0.28.0

**Comment by al-ce** [comment]
For example, this hasty rewrite lets me rename in Go and Python as well as Lua:

```lua
 local function rename_handler(project, curname, new_name)
  ---@diagnostic disable-next-line: duplicate-set-field
  lsp.handlers['textDocument/rename'] = function(err, result, ctx)
    if err then
      vim.notify(
        '[Lspsaga] rename failed err in callback' .. table.concat(err),
        vim.log.levels.ERROR
      )
      return
    end
    local client = lsp.get_client_by_id(ctx.client_id)

    -- Some helper function
    local function apply_edits(edits, uri)
      local bufnr = vim.uri_to_bufnr(uri)
      lsp.util.apply_text_edits(edits, bufnr, client.offset_encoding)
      if config.rename.auto_save then
        api.nvim_buf_call(bufnr, function()
          vim.cmd('noautocmd write!')
        end)
      end
    end

    if result.changes then
      for uri, edits in pairs(result.changes or {}) do
        apply_edits(edits, uri)
      end
    elseif result.documentChanges then
      for _, change in ipairs(result.documentChanges) do
        if change.textDocument and change.textDocument.uri then
          apply_edits(change.edits, change.textDocument.uri)
        end
      end
    end

    if project then
      require('lspsaga.rename.project'):new({ curname, new_name })
    end
  end
end
```

**Comment by al-ce** [comment]
Thank you very much @glepnir , works great

**Comment by glepnir** [comment]
thanks for point it out .
