### ISSUE TITLE
Issue with plugin neo-tree

### ISSUE THREAD

**Issue by LAST7** [nvimdev/lspsaga.nvim#1115]
### Describe the bug

When neo-tree installed with lspsaga, `Lspsaga peek_definition` twice will cause an error:
当 neo-tree 插件和 Lspsaga 插件一起使用时，第二次使用 `Lspsaga peek_definition` 会导致如下报错
```
Error: Error executing vim.schedule lua callback: .../share/nvim/lazy/lspsaga.nvim/lua/lspsaga/definition.lua:117: Invalid window id: 1050
stack traceback:
    [C]: in function 'nvim_win_get_config'
    .../share/nvim/lazy/lspsaga.nvim/lua/lspsaga/definition.lua:117: in function 'create_win'
    .../share/nvim/lazy/lspsaga.nvim/lua/lspsaga/definition.lua:209: in function 'handler'
    /usr/share/nvim/runtime/lua/vim/lsp.lua:1394: in function ''
    vim/_editor.lua: in function <vim/_editor.lua:0>
```

And also `Lspsaga lsp_finder` is unavailable, but `Lspsaga goto_definition` works well.
 `Lspsaga lsp_finder` 也同样无法使用，报错如下：
```
 Error executing Lua callback: ...cal/share/nvim/lazy/lspsaga.nvim/lua/lspsaga/command.lua:71: attempt to call a nil value
stack traceback:
	...cal/share/nvim/lazy/lspsaga.nvim/lua/lspsaga/command.lua:71: in function 'load_command'
	...t/.local/share/nvim/lazy/lspsaga.nvim/plugin/lspsaga.lua:8: in function <...t/.local/share/nvim/lazy/lspsaga.nvim/plugin/lspsaga.lua:7>
```

### Steps to reproduce

**Neovim version:**
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

**[neo-tree](https://github.com/nvim-neo-tree/neo-tree.nvim) version:**
2.70.0 (7f6fa04)

**neo-tree.lua:**
```
return {
    "nvim-neo-tree/neo-tree.nvim",
    event = "VeryLazy",
    branch = "v2.x",
    dependencies = {
        "nvim-tree/nvim-web-devicons",
        "MunifTanjim/nui.nvim",
    },

    config = function ()
        require("neo-tree").setup()
    end
}
```

**lspsaga.lua:**
```
return {
    "glepnir/lspsaga.nvim",
    event = "VeryLazy",
    branch = "main",
    config = function()
        require("lspsaga").setup()
    end,
} -- enhanced lsp uis
```

### Expected behavior

Should function well.

### Neovim version (nvim -v)

0.9.1 commit 7d4bba7

### lspsaga commit

1aad133

### Terminal name/version

alacritty 0.12.2 (9d9982df)

**Comment by CnsMaple** [comment]
I have the same problem.

**Comment by haringsrob** [comment]
lsp_finder is renamed to finder I think.

**Comment by al-ce** [comment]
@LAST7 @CnsMaple does this happen if you use the default keybinding to *close* the peek definition window, which is `<C-c>k`, rather than `q` to quit it?

**Comment by glepnir** [comment]
I can't reproduce your issue. `quit` mean just quit current . `close` will `close` all peek window when you have many . when press quit it will trigger `WinClosed` autocmd to execute clean job.  `close_all` clean all data and ignore this autocmd. `lsp_finder` -> `finder` . I think website had point it out.

provide reproduce step if you have.

![Untitled](https://github.com/nvimdev/lspsaga.nvim/assets/41671631/5de42fda-a36e-4edf-ae02-2b9ac827ff01)

**Comment by LAST7** [comment]
> @LAST7 @CnsMaple does this happen if you use the default keybinding to _close_ the peek definition window, which is `<C-c>k`, rather than `q` to quit it?
> 
> Edit: (I don't know what the intended behavior is here) I think this happens with 'quit' over 'close' because at [these lines](https://github.com/nvimdev/lspsaga.nvim/blob/1aad133f94c8c75bb498560b25d2579199cffd1d/lua/lspsaga/definition.lua#L75-L78), during the 'quit' action, we early return out of the function and so [close_all](https://github.com/nvimdev/lspsaga.nvim/blob/1aad133f94c8c75bb498560b25d2579199cffd1d/lua/lspsaga/definition.lua#L45) is never called.

I was using `q` to quit the peek definition window. You remind me of this keybinding, and it does get rid of the isssue to some degree.
Closing the window with `<C-c>k` could allow me to peek definition more than once, however, the `<C-c>k` keybinding is causing me another trouble: the window which `Lspsaga peek_definition` opens does not close (or disappear) after pressing `<C-c>k`, though the cursor does escape the window.(I currently have only one lsp server running)

Once after using `q` to close a peek window, I was never be able to open one again.

*Screenshot with multiple 'peek' window opened, while the cursor is in the editor window:*
![image](https://github.com/nvimdev/lspsaga.nvim/assets/96737659/f60d351a-8a05-4dfa-908b-204c32b146fa)

As I mentioned in the title of this issue, this issue is caused by the combination of the two plugins. After removing neo-tree, Lspsaga works perfectly.(Though `<C-c>k` would still leave the window opened) This indicates that the problem might be with the other plugin, causing it difficult to resolve the issue here. So my solution might be switching back to nvim-tree.
If anyone who could not reproduce this issue with these config fragments, but want to dig into the problem, my repo contains the full configuration.

Anyway, thanks for your help, have a good day!

**Comment by glepnir** [comment]
First i think maybe caused by ohter plugins?  what i suggest please try a min config for test and if you reproduce it then tell me.

**Comment by LAST7** [comment]
https://github.com/nvimdev/lspsaga.nvim/assets/96737659/67ac0caa-f6a4-4fdd-91b1-b5071f12df34

nearly all other plugins are at minimun config, and I have clean the prev-installed plugins thoroughly.

*lspconfig.lua*
```
return {
    "neovim/nvim-lspconfig",
    event = "VeryLazy",
    dependencies = {
        "hrsh7th/cmp-nvim-lsp",
    },
    config = function ()
        local capabilities = require("cmp_nvim_lsp").default_capabilities()

        require("lspconfig")["lua_ls"].setup({
            capabilities = capabilities,
        })
    end
}
```

*lspsaga.lua*
```
local config = { }

return {
    "glepnir/lspsaga.nvim",
    event = "VeryLazy",
    branch = "main",
    config = function()
        require("lspsaga").setup(config)
    end,
}
```

*mason.lua*
```
local config = { }

local mason_lspconfig = {
    ensure_installed = {
        "lua_ls",
    },
    automatic_installation = true,
}

return {
    "williamboman/mason.nvim",
    event = "VeryLazy",
    dependencies = { },
    config = function ()
        require("mason").setup(config)
    end
}
```

*neo-tree.lua*
```
local config = { }

return {
    "nvim-neo-tree/neo-tree.nvim",
    event = "VeryLazy",
    branch = "v2.x",
    dependencies = {
        -- "nvim-tree/nvim-web-devicons",
        -- "nvim-lua/plenary.lua",
        "MunifTanjim/nui.nvim",
    },

    config = function ()
        require("neo-tree").setup(config)
    end
}
```

*plenary.lua*
```
return {
    "nvim-lua/plenary.nvim",
    lazy = false,
}
```

Appreciate any efforts.

**Comment by glepnir** [comment]
hmm i don't call this min config , i will provide a min template later

**Comment by LAST7** [comment]
> hmm i don't call this min config , i will provide a min template later

Sorry about that.

BTW `<C-c>k` is functioning well after the newly update while the issue with `q` still exists.

**Comment by CnsMaple** [comment]
I use the default key binding and then:
`vim.keymap.set("n", "gh", "<cmd>Lspsaga lsp_finder<CR>")`->`vim.keymap.set("n", "gh", "<cmd>Lspsaga finder<CR>")`
set the `lsp_finder` to the `finder`.
it run normal.

**Comment by glepnir** [comment]
a min config . download the test plugin to somewhere then use the path in rtp.  usage `nvim --clean -u min.lua`

```lua
vim.opt.rtp:append('~/workspace/nvim-lspconfig')
vim.opt.rtp:append('~/workspace/neo-tree.nvim')
vim.opt.rtp:append('~/workspace/plenary.nvim/')
vim.opt.rtp:append('~/workspace/nui.nvim/')
vim.opt.rtp:append('~/workspace/lspsaga.nvim')
require('neo-tree').setup({})
local lspconfig = require('lspconfig')
lspconfig.lua_ls.setup({})
require('lspsaga').setup({})

lspconfig.rust_analyzer.setup({})
lspconfig.jdtls.setup({})
lspconfig.tsserver.setup({})
lspconfig.pyright.setup({})
lspconfig.custom_elements_ls.setup({})
vim.keymap.set({
  'n',
}, 'gd', '<cmd>Lspsaga peek_definition<CR>')
```

**Comment by LAST7** [comment]
I've done the test with the `min.lua` u provided and the cloned plugin repos locally. Here's the video:

https://github.com/nvimdev/lspsaga.nvim/assets/96737659/b98de7c5-2d54-400b-898d-8f93c605a910


Using `q` to quit the 'peek' window would still cause the bug, while `<C-c>k` wouldn't.
After removing the neo-tree plugin, everything works fine.

**Comment by glepnir** [comment]
fixed
