### ISSUE TITLE
Lightbulb error with the latest release

### ISSUE THREAD

**Issue by MariaSolOs** [nvimdev/lspsaga.nvim#1116]
### Describe the bug

I get the following error message with the latest version of the plugin:
<img width="1239" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/62502207/dd5b2098-57fa-4e2d-a085-a023b9dcbcd4">

### Steps to reproduce

Open a Rust file where just `rust_analyzer` and Copilot attach.

My `lspsaga` configuration is:
```lua
return {
    {
        'nvimdev/lspsaga.nvim',
        event = 'LspAttach',
        opts = {
            ui = {
                border = 'rounded',
                code_action = '',
            },
            -- Using barbecue for this instead.
            symbol_in_winbar = {
                enable = false,
            },
            lightbulb = {
                sign = false,
            },
            outline = {
                win_width = 50,
                keys = {
                    toggle_or_jump = '<cr>',
                },
            },
        },
    },
}
```

### Expected behavior

For the error message to not appear.

### Neovim version (nvim -v)

v0.10.0-dev-653+gfbeef0d4e

### lspsaga commit

1aad133f94c8c75bb498560b25d2579199cffd1d

### Terminal name/version

kitty 0.28.1

**Comment by MariaSolOs** [comment]
In addition, I noticed that the `lightbulb.enable_in_insert` setting was removed. Is this intentional, or is there another way to configure it?

**Comment by parmardiwakar150** [comment]
I am also getting similar error with the latest release 
<img width="1086" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/31608288/16527413-8bfa-4535-95f9-c4c6796f5eaa">

**Comment by MariaSolOs** [comment]
It's an interesting error because according to `:h LspAttach`, the callback should receive a non-null argument...

**Comment by MariaSolOs** [comment]
Oh okay, this was an error from the package manager which was fixed in https://github.com/folke/lazy.nvim/issues/922 (in the case of `lazy`). Closing this issue then.

**Comment by glepnir** [comment]
it's lazy issue you need update to latest lazy.nvim . ( I remmeber write in doc)

**Comment by MariaSolOs** [comment]
@glepnir oops sorry! I said I was going to close the issue and then forgot to 🤦🏻‍♀️ Thanks for your work!
