### ISSUE TITLE
winbar interface and kind cannot be set

### ISSUE THREAD

**Issue by CnsMaple** [nvimdev/lspsaga.nvim#1117]
### Describe the bug

when i update.i receive many error.

There is an interface that cannot be used, which I have placed on the status bar:
`require('lspsaga.symbolwinbar'):get_winbar()`

the ui.kind can not to set icon.some icon don't show to my window

### Steps to reproduce

only update plugins

### Expected behavior

be normal

### Neovim version (nvim -v)

0.10.0-dev

### lspsaga commit

1aad133

### Terminal name/version

pwsh + wsl

**Comment by glepnir** [comment]
```lua
require('lspsaga').setup({
         symbols_in_winbar = { enable = false, custom = true}
})

**Comment by CnsMaple** [comment]
if the config :
        symbol_in_winbar = {
            enable = false,
}
`require('lspsaga.symbol.winbar').get_bar()` not return any thing.

if set enabled = true,it work normal,but i don't need winbar.

**Comment by glepnir** [comment]
`symbol_in_winbar.enable =false, custom =true`

**Comment by CnsMaple** [comment]
它可以运行正常了，但是ui.kind设置的符号没有起作用。这是换了接口还是设置的方式不一样了？

**Comment by CnsMaple** [comment]
没有在文档中看到怎么去设置它。

**Comment by glepnir** [comment]
没怎么动。你怎么设置的 kind

**Comment by CnsMaple** [comment]
kind = {
                    ['File'] = { ' ', 'Tag' },
                    ['Module'] = { ' ', 'Exception' },
                    ['Namespace'] = { ' ', 'Include' },
                    ['Package'] = { ' ', 'Label' },
                    ['Class'] = { ' ', 'Include' },
                    ['Method'] = { ' ', 'Function' },
                    ['Property'] = { ' ', '@property' },
                    ['Field'] = { ' ', '@field' },
                    ['Constructor'] = { ' ', '@constructor' },
                    ['Enum'] = { ' ', '@number' },
                    ['Interface'] = { ' ', 'Type' },
                    ['Function'] = { ' ', 'Function' },
                    ['Variable'] = { ' ', '@variable' },
                    ['Constant'] = { ' ', 'Constant' },
                    ['String'] = { ' ', 'String' },
                    ['Number'] = { ' ', 'Number' },
                    ['Boolean'] = { ' ', 'Boolean' },
                    ['Array'] = { ' ', 'Type' },
                    ['Object'] = { ' ', 'Type' },
                    ['Key'] = { ' ', 'Constant' },
                    ['Null'] = { ' ', 'Constant' },
                    ['EnumMember'] = { ' ', 'Number' },
                    ['Struct'] = { ' ', 'Type' },
                    ['Event'] = { ' ', 'Constant' },
                    ['Operator'] = { ' ', 'Operator' },
                    ['TypeParameter'] = { ' ', 'Type' },
                    -- ccls
                    ['TypeAlias'] = { ' ', 'Type' },
                    ['Parameter'] = { ' ', '@parameter' },
                    ['StaticMethod'] = { ' ', 'Function' },
                    ['Macro'] = { ' ', 'Macro' },
                    -- for completion sb microsoft!!!
                    ['Text'] = { ' ', 'String' },
                    ['Snippet'] = { ' ', '@variable' },
                    ['Folder'] = { ' ', 'Title' },
                    ['Unit'] = { ' ', 'Number' },
                    ['Value'] = { ' ', '@variable' },
                },

**Comment by glepnir** [comment]
你这个很多都是一样的没必要全改。 更新试试。

**Comment by CnsMaple** [comment]
还是没有作用，我的nerd font有些图标不显示，我给那边提了一个issues，可能没有这么快修好。
![image](https://github.com/nvimdev/lspsaga.nvim/assets/92523839/9fa17657-41e8-44b5-a41d-7783e629c7bc)

**Comment by CnsMaple** [comment]
不好意思，可以了，现在没有问题了，刚刚有点延迟

**Comment by glepnir** [comment]
很多都一样。。没必要改。 用的都是标准的md_code 系列。
