### ISSUE TITLE
Window preview character misalignment when there is an uncommon symbol in the code

### ISSUE THREAD

**Issue by CnsMaple** [nvimdev/lspsaga.nvim#1120]
### Describe the bug

![image](https://github.com/nvimdev/lspsaga.nvim/assets/92523839/0d318148-1c7c-4a0b-ab35-3d029e7581b2)

![image](https://github.com/nvimdev/lspsaga.nvim/assets/92523839/728cea79-bc56-4b04-a5b0-670ac35a3c15)

### Steps to reproduce

only use `finder`

### Expected behavior

show normal

### Neovim version (nvim -v)

0.10.0-dev

### lspsaga commit

8a05cb1

### Terminal name/version

pwsh+wsl

**Comment by CnsMaple** [comment]
and the title name ,it lose the first char
![image](https://github.com/nvimdev/lspsaga.nvim/assets/92523839/e741a683-d020-453d-a49d-ce686d31f7e3)

**Comment by CnsMaple** [comment]
我更新到了 https://github.com/nvimdev/lspsaga.nvim/commit/64892e2eb5f8b2a7fd045546ac24702a229f28cb
但是问题还在：
视频：
[2023-07-10 15-34-48.zip](https://github.com/nvimdev/lspsaga.nvim/files/11999073/2023-07-10.15-34-48.zip)
这是导致异常的字符：{ "", "" }

问题主要有：
1. 进行finder的时候，如果行中有上面两个字符，就偏移，使用默认快捷键“o”打开的时候，也不能正确定位到变量名。
2. float的窗口名字缺少第一个字符，比如视频中的文件夹名字：plugins中p就不见了。

**Comment by glepnir** [comment]
提供个最小的lua代码 我需要重现一下。

**Comment by CnsMaple** [comment]
例如：
```lua
local temp1 = "111"

local function es()
    local str = "" + temp1 + ""
end
```
对函数中的temp1进行finder就可以了：
![image](https://github.com/nvimdev/lspsaga.nvim/assets/92523839/0837635e-ea2d-43c5-b3ae-9b6ce20b27a8)

**Comment by glepnir** [comment]
文件sub 你更新下试试 应该行了

**Comment by glepnir** [comment]
重现了。 但是返回的结果是这样 temp 应该是 22 返回的是20.
```
{
  bufnr = 1,
  range = {
    ["end"] = {
      character = 25,
      line = 22
    },
    start = {
      character = 20,
      line = 22
    }
  },
  uri = "file:///Users/mw/workspace/test/test.lua"
}
```

**Comment by CnsMaple** [comment]
文件名我不明白是什么原因，放的位置不同缺的字符数量就不同：
没有其他符号在plugins中了。
当文件在根目录下：
![image](https://github.com/nvimdev/lspsaga.nvim/assets/92523839/cc8a18b1-b554-47cc-90a3-f75713372e2d)
当文件在根目录下的一个子目录中：
![image](https://github.com/nvimdev/lspsaga.nvim/assets/92523839/098cf19d-34fd-4ba9-8646-82f1cc9136cc)

**Comment by glepnir** [comment]
LspInfo. 看下root_dir  应该是不对劲。

**Comment by CnsMaple** [comment]
是的，root_dir在/home/maple/.config/nvim/lua。并非在/home/maple/.config/nvim

**Comment by CnsMaple** [comment]
但是我打开的目录是/home/maple/.config/nvim
