### ISSUE TITLE
lspsaga when meet xml use treesitter

### ISSUE THREAD

**Issue by Decodetalkers** [nvimdev/lspsaga.nvim#1125]
### Describe the bug

![image](https://github.com/nvimdev/lspsaga.nvim/assets/60290287/e49dc0e8-47f2-4640-aa37-de1b6ef9b023)

### Steps to reproduce

edit an xml file and move cursor

### Expected behavior

not use treesitter when the filetype not support it

### Neovim version (nvim -v)

v0.9.1

### lspsaga commit

8a05cb18092d49075cf533aaf17d312e2ad61d77

### Terminal name/version

wezterm

**Comment by glepnir** [comment]
I think you enabled `symbols_in_winbar.hide_keyword` ?  so it cause an error now even enabled without parser it also work.

**Comment by Decodetalkers** [comment]
> I think you enabled `symbols_in_winbar.hide_keyword` ? so it cause an error now even enabled without parser it also work.

Yes.  I enabled it. Thank you for the tip.
