### ISSUE TITLE
method textDocument/codeAction is not supported by any of the servers registered for the current buffer

### ISSUE THREAD

**Issue by CnsMaple** [nvimdev/lspsaga.nvim#1127]
### Describe the bug

使用`:LspRestart`后，不断报错。
![image](https://github.com/nvimdev/lspsaga.nvim/assets/92523839/9db50cd2-b627-4aa5-a73e-2fd45686b6d8)

### Steps to reproduce

1. 打开一个lua文件
2. 使用`:LspRestart`
3. 移动光标。

### Expected behavior

none

### Neovim version (nvim -v)

0.10.0-dev

### lspsaga commit

c8789fa

### Terminal name/version

wsl

**Comment by glepnir** [comment]
是lspsaga 的bug

**Comment by glepnir** [comment]
无法重现。 消息是来自neovim的文件。 或者你用了其他lsp相关的插件

**Comment by CnsMaple** [comment]
我明白了，是我另一个lsp的参数提示和lspsaga的插件一起使用引起的，现在没有问题了。

**Comment by CnsMaple** [comment]
谢谢你的提醒，我发现了，确实是lspsaga的问题，好像和其他插件没关系。
1. 启动一个lua文件，在文件分析的时候使用：`:LspRestart`:
![image](https://github.com/nvimdev/lspsaga.nvim/assets/92523839/7dd9c717-47f8-47bf-beb9-24c8dc5922a3)
2. 然后快速移动光标。就可以重现

在没有lspsaga情况下，这个操作是直接不会重启lua_ls，开了lspsaga下，这个操作，会导致lua_ls再次启动。

**Comment by CnsMaple** [comment]
[屏幕录制 2023-07-10 173934.zip](https://github.com/nvimdev/lspsaga.nvim/files/12000376/2023-07-10.173934.zip)

因为代码文件不止是开始的时候进行分析。写代码的过程中也有可能出现，这个问题有时会导致不断的显示消息，你看看能不能复现一下。

**Comment by glepnir** [comment]
重现不了加了个patch 你试试吧。

**Comment by glepnir** [comment]
明天我在试试能不能重现
