### ISSUE TITLE
lspsaga symbol error at the startup

### ISSUE THREAD

**Issue by parmardiwakar150** [nvimdev/lspsaga.nvim#1128]
### Describe the bug

Whenever I open neovim, I am getting this error at the startup.
<img width="1089" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/31608288/db7a7642-f176-44b6-a4b2-c3ae8490a24b">

### Steps to reproduce

Just open a neovim instance, the error will be shown at the startup.

My lspsaga config
```lua
require("lspsaga").setup({
	symbol_in_winbar = {
		enable = false,
	},
	lightbulb = {
		enable = false,
	},
})
``` 

My plugin Manager - Packer

### Expected behavior

No Error should be shown at the startup.

### Neovim version (nvim -v)

NVIM v0.9.1 Build type: Release LuaJIT 2.1.0-beta3

### lspsaga commit

ea053be

### Terminal name/version

Iterm 2

**Comment by glepnir** [comment]
lazy issue update your lazy.

**Comment by parmardiwakar150** [comment]
I am using Packer

**Comment by glepnir** [comment]
then report to `packer` should pass `data` from `LspAttach` event.

**Comment by parmardiwakar150** [comment]
It might take some time for them to fix this. Is there any other way to fix it?

**Comment by glepnir** [comment]
layload `lspsaga` by using `ft` keyword or `after`  lspconfig.

**Comment by parmardiwakar150** [comment]
I have tried it. I am still getting same error.
this is my new config.

```lua
use({
		"glepnir/lspsaga.nvim",
		opt = true,
		branch = "main",
		event = "LspAttach",
		config = function()
			require("lspsaga").setup({
				symbol_in_winbar = {
					enable = false,
				},
				lightbulb = {
					enable = false,
				},
			})
		end,
		requires = {
			{ "nvim-tree/nvim-web-devicons" },
			--Please make sure you install markdown and markdown_inline parser
			{ "nvim-treesitter/nvim-treesitter" },
		},
		after = {
			"nvim-lspconfig",
		},
	})
```

**Comment by glepnir** [comment]
remove `event = 'LspAttach`

**Comment by parmardiwakar150** [comment]
removing event = 'LspAttach' fixed the issue, but none of the commands from lspsaga is working after this.

**Comment by glepnir** [comment]
also remove `opt =true`
