### ISSUE TITLE
Disable folder icons in the winbar

### ISSUE THREAD

**Issue by bfulop** [nvimdev/lspsaga.nvim#1130]
Hello, 

Is it possible to disable the display of the folder icons in the winbar?

I find it a bit redundant to have them.
I tried to change the `kind.Folder` variable but it doesn't seem to have any effect on the winbar.

Thank you for all your work on this great plugin! ❤️

![folder icons](https://github.com/nvimdev/lspsaga.nvim/assets/1718128/53b8b119-2b15-4fd2-85ce-feed74e979c0)

**Comment by bfulop** [comment]
I have this in my `lspsaga.rc.lua` file:

```
saga.setup({
  ui = {
    title = false,
    border = 'solid',
    winblend = 10,
    kind = {
      File = { ' ', "@comment" },
      -- for completion sb microsoft!!!
      Folder = { ' ', "@comment" },
    }
  },
  symbol_in_winbar = {
    enable = true,
    separator = ' ⟩ ',
    hide_keyword = true,
    show_file = true,
    folder_level = 4,
    respect_root = false,
    color_mode = false,
    delay = 600,
  },
```

But I'm still seeing the folder icons. 


Is there something else to modify as well?

**Comment by glepnir** [comment]
which package management you used ? min config works well

```lua
vim.opt.rtp:append('~/workspace/lspsaga.nvim')
local lspconfig = require('lspconfig')
lspconfig.lua_ls.setup({})
require('lspsaga').setup({
  ui = {
    kind = {
      Folder = { ' ' },
    },
  },
})

```

**Comment by glepnir** [comment]
![image](https://github.com/nvimdev/lspsaga.nvim/assets/41671631/a73adaee-03e7-4ec0-865b-ab676d77d17d)

**Comment by bfulop** [comment]
> which package management you used ? min config works well

I'm using packer.

I had to reinstall lspsaga with packer for the new settings to take effect. Now it's all good! 👍

**Comment by bfulop** [comment]
thanks, I'll do that next time!
