### ISSUE TITLE
Outline show close icon even if there are no children

### ISSUE THREAD

**Issue by mikehaertl** [nvimdev/lspsaga.nvim#1134]
### Describe the bug

When I open the outline on a Java file I see close icons even if there are no children:

![image](https://github.com/nvimdev/lspsaga.nvim/assets/675062/fb1da80a-3a1d-4559-b9fc-82344fd186eb)

If I close and re-open the item, the item below gets duplicated each time:

Closed:
![image](https://github.com/nvimdev/lspsaga.nvim/assets/675062/96e137a4-5d6a-4d01-a66d-33dc343cc208)

Re-Opened:
![image](https://github.com/nvimdev/lspsaga.nvim/assets/675062/922a51d1-18ae-4f14-9e26-e1517bd57404)

After more toggling:
![image](https://github.com/nvimdev/lspsaga.nvim/assets/675062/22bf592c-caaf-4945-863f-1e0f31f9bac6)

### Steps to reproduce

Open the outline on a java file and toggle closeable items.

### Expected behavior

No error.

### Neovim version (nvim -v)

0.9.0 commit 040f14598

### lspsaga commit

44f2bea

### Terminal name/version

Gnome Terminal 3.44.0

**Comment by glepnir** [comment]
I need java code to reproduce.
