### ISSUE TITLE
Request to Revert to Previous UI Version of finder

### ISSUE THREAD

**Issue by shairbekov-bakyt** [nvimdev/lspsaga.nvim#1135]
<img width="804" alt="Screenshot 2023-07-11 at 02 29 53" src="https://github.com/nvimdev/lspsaga.nvim/assets/90038945/2c6f6bf6-7cfe-4ae0-a6a4-4537ba849c6d"> 
<img width="1475" alt="Screenshot 2023-07-11 at 02 31 09" src="https://github.com/nvimdev/lspsaga.nvim/assets/90038945/6af94719-e967-403f-b505-f471514ba359">

### Problem Description
I kindly request the developers to review the recent changes made to the UI. I suggest reverting to the previous version as I believe the previous UI was more user-friendly and intuitive.

### Explanation of Changes
The new UI has the following drawbacks compared to the previous version:
- Changes in the placement of elements and navigation, making it more difficult to use
- Reduction in visual appeal and readability
- Changes in the color scheme, making it harder to distinguish elements and reducing contrast

### Proposal
I propose reverting to the previous UI version to maintain the usability and user satisfaction. I believe it will enhance the overall user experience and alleviate the difficulties encountered with the current UI.

Thank you for considering my request. I'm happy to provide further feedback or clarification if needed.

**Comment by glepnir** [comment]
provide suggest on new ui will be consider. back not consider.
