### ISSUE TITLE
Lspsaga finder command throw a error

### ISSUE THREAD

**Issue by xieping5555** [nvimdev/lspsaga.nvim#1137]
### Describe the bug

Error executing Lua callback: ...e/pack/packer/start/lspsaga.nvim/lua/lspsaga/command.lua:71: attempt to call a nil value
stack traceback:
        ...e/pack/packer/start/lspsaga.nvim/lua/lspsaga/command.lua:71: in function 'load_command'
        ...m/site/pack/packer/start/lspsaga.nvim/plugin/lspsaga.lua:8: in function <...m/site/pack/packer/start/lspsaga.nvim/plugin/lspsaga.lua:7>

### Steps to reproduce

use keymap **gf** trigger Lspsaga finder command, then the error throws.

### Expected behavior

no error throw

### Neovim version (nvim -v)

NVIM v0.9.1

### lspsaga commit

3d396d41

### Terminal name/version

iterm2

**Comment by steffenkehler** [comment]
Having the same issue

**Comment by glepnir** [comment]
`Lspsaga lsp_finder ` -> `Lspsaga finder` and new usage https://dev.neovim.pro/

**Comment by syfless1999** [comment]
change to `Lspsaga finder` still get error

```
Error detected while processing CursorMoved Autocommands for "<buffer=14>":
Error executing lua callback: ...ck/packer/start/lspsaga.nvim/lua/lspsaga/finder/init.lua:221: invalid key: title_pos
stack traceback:
        [C]: in function 'nvim_win_set_config'
        ...ck/packer/start/lspsaga.nvim/lua/lspsaga/finder/init.lua:221: in function <...ck/packer/start/lspsaga.nvim/lua/l
spsaga/finder/init.lua:193>
```

**Comment by glepnir** [comment]
your neovim version is old
