### ISSUE TITLE
[Regression] Unable to exit insert mode in rename

### ISSUE THREAD

**Issue by amittamari** [nvimdev/lspsaga.nvim#1139]
### Describe the bug

https://github.com/nvimdev/lspsaga.nvim/pull/1080

broke this

https://github.com/nvimdev/lspsaga.nvim/pull/1040

### Steps to reproduce

1. Open rename
2. Go to insert mode
3. Click <esc>

### Expected behavior

Goes to normal mode, rename float isn't closed

### Neovim version (nvim -v)

NVIM v0.9.1

### lspsaga commit

1fff4a4cd5933b57eaa7a106a820a252fcc9e1ba

### Terminal name/version

kitty

**Comment by glepnir** [comment]
what i confused is can we use another map for close . `ESC` is mode change keymap . it's better bind this in rename window.

**Comment by glepnir** [comment]
or you can use `<CTRL-[>` and `<CTRL-C` back to normal mode..

**Comment by glepnir** [comment]
I had changed defaule quit keymap to `<Ctrl-k>` avoid confict
