### ISSUE TITLE
Pressing ESC quits rename window 

### ISSUE THREAD

**Issue by fgazat** [nvimdev/lspsaga.nvim#1140]
### Describe the bug

When i press ESC it quits rename window. Previously it was quitting insert mode only and i could replace/append a character to the name.

### Steps to reproduce

1. Hover on a variable.
2. `:Lspsaga rename`.
3. Press ESC.

### Expected behavior

Pressing ESC quits Insert mode but not rename window

### Neovim version (nvim -v)

v0.9.0

### lspsaga commit

118da3c69af27f1343ca86481bcc0546bce4d3b3

### Terminal name/version

macOS terminal version 2.13 (447)

**Comment by glepnir** [comment]
duplicate #1139

**Comment by glepnir** [comment]
I had changed defaule quit keymap to `<Ctrl-k>` avoid confict

**Comment by fgazat** [comment]
Created PR to the docs: https://github.com/nvimdev/nvimdev.github.io/pull/3
