### ISSUE TITLE
Attempt to index a nil value (omnisharp)

### ISSUE THREAD

**Issue by lucasquin** [nvimdev/lspsaga.nvim#1141]
### Describe the bug

![image](https://github.com/nvimdev/lspsaga.nvim/assets/65108092/a106d630-747d-4366-b7db-5377dcfc6639)

### Steps to reproduce

Lsp: Omnisharp

try 
`peek_definition` 
or 
`lsp_finder`

My Omnisharp config:

```
lspconfig["omnisharp"].setup({
	analyze_open_documents_only = true,
	capabilities = capabilities,
	enable_editorconfig_support = false,
	enable_import_completion = false,
	enable_ms_build_load_projects_on_demand = false,
	enable_roslyn_analyzers = false,
	organize_imports_on_format = false,
	sdk_include_prereleases = true,
	filetypes = { "cs", "vb" },
	on_attach = on_attach,
	flags = {
		debounce_text_changes = 150,
	},
})
```

### Expected behavior

Display preview

### Neovim version (nvim -v)

0.9.1

### lspsaga commit

bed04d0

### Terminal name/version

Windows Terminal

**Comment by glepnir** [comment]
could you add a debug print and paste result in there ? thanks

```diff
diff --git a/lua/lspsaga/definition.lua b/lua/lspsaga/definition.lua
index 8a74c8f..5bba252 100644
--- a/lua/lspsaga/definition.lua
+++ b/lua/lspsaga/definition.lua
@@ -188,6 +188,7 @@ function def:peek_definition(method)

   self.pending_request = true
   lsp.buf_request(current_buf, method_name, params, function(_, result, context)
+    print(vim.inspecet(result))
     self.pending_request = false
     if not result or next(result) == nil then
       vim.notify(
```

**Comment by glepnir** [comment]
line 201 is a return. so this picture make me can't find the bug

**Comment by lucasquin** [comment]
@glepnir using `print(vim.inspecet(result))` in `definition.lua` this is result:
![image](https://github.com/nvimdev/lspsaga.nvim/assets/65108092/81cf3733-c50f-4aa9-97b5-b51870ddad08)

![image](https://github.com/nvimdev/lspsaga.nvim/assets/65108092/342eae30-a285-4fc5-9df4-da82a58dee17)

**Comment by glepnir** [comment]
hello is `vim.inspect` a typo in your print . `e`

**Comment by lucasquin** [comment]
@glepnir sorry, new print:

![image](https://github.com/nvimdev/lspsaga.nvim/assets/65108092/aa4b70ed-9929-4137-9a35-79a22736b191)
