### ISSUE TITLE
Definition Edit not workinfg

### ISSUE THREAD

**Issue by isaac-scarrott** [nvimdev/lspsaga.nvim#1143]
### Describe the bug

After updating Lspsaga today I noticed the `edit` keybind `<CR>` set in my config was no longer working when running `:Lspsaga peek_type_definition`.

Reverted to commit https://github.com/nvimdev/lspsaga.nvim/commit/4f075452c466df263e69ae142f6659dcf9324bf6 and seems to be working as expected so bug was introduced sometime between https://github.com/nvimdev/lspsaga.nvim/commit/4f075452c466df263e69ae142f6659dcf9324bf6 and latest commit

### Steps to reproduce

1. Use config

```lua
-- import lspsaga safely
local saga_status, saga = pcall(require, "lspsaga")
if not saga_status then
	return
end

saga.setup({
	-- keybinds for navigation in lspsaga window
	scroll_preview = { scroll_down = "<C-f>", scroll_up = "<C-b>" },
	-- use enter to open file with definition preview
	definition = {
		edit = "<CR>",
	},
	ui = {
		colors = {
			normal_bg = "#022746",
		},
	},
})
```

2. Run `:Lspsaga peek_type_definition` command
3. Press `<CR>` key
4. Notice cursor moves down 

### Expected behavior

When I press the `<CR>` key after running the command `:Lspsaga peek_type_definition` and I have the correct keybindings set it opens full window

### Neovim version (nvim -v)

0.9.1

### lspsaga commit

latest

### Terminal name/version

tmux 3.3a + iTerm2 3.4.19

**Comment by glepnir** [comment]
`definition.keys`
