### ISSUE TITLE
Some windows base width from earlier context when should resize

### ISSUE THREAD

**Issue by digitallyserviced** [nvimdev/lspsaga.nvim#1144]
### Describe the bug

Code action windows seem to hold a size from the list of code actions, the action preview should resize if there are actions longer than original code action names...

![Screenshot_2023-07-11-17-04-32_3520x1080](https://github.com/nvimdev/lspsaga.nvim/assets/1828125/cc41273f-91de-4886-a458-08a469a0a4a6)
![Screenshot_2023-07-11-17-01-30_3520x1080](https://github.com/nvimdev/lspsaga.nvim/assets/1828125/e3d24e69-e6cb-45da-ad9d-eecdc4f09b4f)

```lua
  {
    "nvimdev/lspsaga.nvim",
    dependencies = { "neovim/nvim-lspconfig" },
    event = "LspAttach",
    config = function()
      local present, lspsaga = pcall(require, "lspsaga")

      if not present then
        return
      end

      lspsaga.setup {
        lightbulb = {
          enable = false,
          enable_in_insert = true,
          sign = true,
          sign_priority = 40,
          virtual_text = true,
        },
      }
    end
  }
```

I have to turn off lightbulb because it causes lines with diagnostics in editor to shift left a column or two...

### Steps to reproduce

request code actions that dont seem to have an immediate preview available on the initially selected action?

This was reproduced on gopls, lua_ls, and vtsls

### Expected behavior

resize on action preview width changes...

define a fixed width for the action preview window?  

![image](https://github.com/nvimdev/lspsaga.nvim/assets/1828125/9f919a10-59a8-487b-a41a-45765d7e61fc)

THis screen is from hardcoding 60 for the action_preview window `opts.width`

### Neovim version (nvim -v)

0.10.0

### lspsaga commit

master

### Terminal name/version

wezterm

**Comment by glepnir** [comment]
It's nothing to be sorry about. This is my plugin. When something goes wrong it's my responsibility to fix it. lsp and neovim have too many cases to handle. This is normal.

**Comment by digitallyserviced** [comment]
@glepnir 

I just know that in the OSS space it is rare for someone to jump onto issues/requests/features or even respond to users because it's not their first priority/moneymaker. 

When I find that an open source developer has better response/SLA/relation with their users than companies with software support contracts in the $$$$$$ of dollars... it definitely should be shown appreciation!

**Comment by glepnir** [comment]
Not quite. More because of love :). For example I don't get paid for my work at neovim.

**Comment by digitallyserviced** [comment]
@glepnir hah! yes, but not all have your sense of responsibility.

I am also not trying to apologize.

I am trying to praise you!

**Comment by glepnir** [comment]
lol thanks for praise. have a good day :)
