### ISSUE TITLE
Preview window positioning

### ISSUE THREAD

**Issue by topaxi** [nvimdev/lspsaga.nvim#1150]
**Is your feature request related to a problem? Please describe.**
I'm using [edgy.nvim](https://github.com/folke/edgy.nvim) to pin the outline window to the left sidebar below my nvim-tree.

This results in the outline not taking up the whole height of the window and all preview windows by the outline are positioned wrong (I assume the window is positioned via cursor offset from within the outline window).

Example edgy config:

```lua
  {
    'folke/edgy.nvim',
    event = 'VeryLazy',
    keys = {
      { '<C-n>', '<cmd>lua require("edgy").toggle("left")<cr>', desc = 'Edgy' },
    },
    opts = {
      left = {
        {
          title = 'NvimTree',
          ft = 'NvimTree',
          pinned = true,
          open = 'NvimTreeOpen',
        },
        {
          title = 'Outline',
          ft = 'sagaoutline',
          size = { height = 30 },
          pinned = true,
          open = 'Lspsaga outline',
        },
      },
    },
  },
```

**Describe the solution you'd like**
It would be nice to somehow influence the positioning of the preview window or for lspsaga to maybe figure out the position of it's window itself and then relatively position the preview window (although I'm not sure whether the latter is possible).

**Describe alternatives you've considered**
For now I just disabled the auto_preview and never use previews.

**Comment by glepnir** [comment]
```lua
  outline = {
    win_position = 'left',
  },
```

**Comment by topaxi** [comment]
I understand that I can set win_position to left (which I do have), but I want it to be combined with my file-tree in one single sidebar :)

**Comment by topaxi** [comment]
Here is a screenshot on how it looks like in my case at the moment:
![image](https://github.com/nvimdev/lspsaga.nvim/assets/213788/4ff51342-88e4-4f3d-a315-35b08f7f6c90)

**Comment by topaxi** [comment]
That was quick! Amazing! Thank you so much :partying_face: :heart:
