### ISSUE TITLE
重命名窗口支持vim键位操作

### ISSUE THREAD

**Issue by CnsMaple** [nvimdev/lspsaga.nvim#1151]
目前，重命名窗口，只能输入字符，并不能使用"h","j","k","l"进行移动还有其他的操作也不行。

期望效果：

https://github.com/nvimdev/lspsaga.nvim/assets/92523839/ff24c579-36c3-4647-9fe0-db0bb94c6313

**Comment by glepnir** [comment]
`in_select = false` 或者 `Lspsaga rename mode = n`
