### ISSUE TITLE
lsp_rename throws `attemp to call a nil value`

### ISSUE THREAD

**Issue by mickaelramanitrera** [nvimdev/lspsaga.nvim#1158]
### Describe the bug

When trying to do a `lsp_rename`, there is an error thrown for `attempt to call a nil value`. 

![image](https://github.com/nvimdev/lspsaga.nvim/assets/6593911/2bcf77b3-7f23-4ec0-b9e9-16c09cd84228)

### Steps to reproduce

1. Put the cursor on a variable or a method
2. Type command `:Lspsaga lsp_rename`

### Expected behavior

Should rename with no errors

### Neovim version (nvim -v)

0.9.1

### lspsaga commit

01f6117e535a1aa783b6d95c18628da4960df519

### Terminal name/version

warp/v0.2023.07.04.08.03.stable_02

**Comment by glepnir** [comment]
there is no `lsp_rename` just `rename`

**Comment by mickaelramanitrera** [comment]
I see. Thanks @glepnir ! 

Would you mind changing on the docs then ? 

![image](https://github.com/nvimdev/lspsaga.nvim/assets/6593911/a8f3ea3b-7ffb-40de-9268-cd0c4dabdc56)

As it is misleading when looking for a setup.

**Comment by glepnir** [comment]
thanks for catch it out. fixed.
