### ISSUE TITLE
after last update lspsaga not working and causing errors

### ISSUE THREAD

**Issue by kayuxcodes** [nvimdev/lspsaga.nvim#1159]
### Describe the bug

output: [https://i.imgur.com/HnCWj72.png](url)
i just reinstall lspsaga to reconfigure my nvchad config, last night the plugin works fine but today is causing issues, what ever `hover_doc` or `show_line_diagnostic` (all methods not working)
please fix the bug.

### Steps to reproduce

![lspsaga](https://github.com/nvimdev/lspsaga.nvim/assets/116302048/2f643896-941b-475e-a184-152c713cad89)

### Expected behavior

works as previous updates, is nothing works such as nvchad or custom config

### Neovim version (nvim -v)

NVIM 0.9

### lspsaga commit

08da11d83a545d899c11ea070903dfb26fce39b0

### Terminal name/version

Windows Terminal

**Comment by glepnir** [comment]
try `:Lspsaga hover_doc`  and new version is rewrite need reconfig see doc website

**Comment by kayuxcodes** [comment]
I tried all lspsaga commands with a fresh update, and nothing works

**Comment by glepnir** [comment]
then your env something wrong . because you use a preconfig so IDk what happen in nvchad.

**Comment by kayuxcodes** [comment]
@glepnir it should to work, I said last night works fine for me

**Comment by glepnir** [comment]
last night you used which version . last udpate is what time. I don't change `hover` yesterday and today.

**Comment by kayuxcodes** [comment]
@glepnir i will try to reinstall the hole config, is that okay?

**Comment by glepnir** [comment]
from your picture. I guess there has same name config file. so conflict load module. then you see `loop or previous load error module`

**Comment by diegoulloao** [comment]
> @gepbird thank you its works, there was a conflict load module this is why `lspsaga` not worked.

what was the solution? having the same issue with custom nvim config.

**Comment by kayuxcodes** [comment]
@diegoulloao just check your config, you probably have an conflict load module

**Comment by diegoulloao** [comment]
it doesn't seems like conflict loading modules, sometimes I'm just getting this error:
```
Error executing Lua callback: ...site/pack/packer/opt/lspsaga.nvim/lua/lspsaga/window.lua:3: attempt to index field 'config' (a nil value)
stack traceback:
        ...site/pack/packer/opt/lspsaga.nvim/lua/lspsaga/window.lua:3: in main chunk
        [C]: in function 'require'
        .../pack/packer/opt/lspsaga.nvim/lua/lspsaga/definition.lua:5: in main chunk
        [C]: in function 'require'
        ...ite/pack/packer/opt/lspsaga.nvim/lua/lspsaga/command.lua:8: in function <...ite/pack/packer/opt/lspsaga.nvim/lua/lspsaga/command.lua:7>
        ...ite/pack/packer/opt/lspsaga.nvim/lua/lspsaga/command.lua:71: in function 'load_command'
        ...vim/site/pack/packer/opt/lspsaga.nvim/plugin/lspsaga.lua:8: in function <...vim/site/pack/packer/opt/lspsaga.nvim/plugin/lspsaga.lua:7>
```

**Comment by kayuxcodes** [comment]
@diegoulloao can you share your `lspsaga` config, maybe i can help you to fix that isssue

**Comment by diegoulloao** [comment]
@kayuxcodes sure, is this: https://github.com/diegoulloao/nvim-diegoulloao

**Comment by kayuxcodes** [comment]
@glepnir it seems that you didn't load `lspsaga` configuration correctly or must be an conflict load

**Comment by diegoulloao** [comment]
> @glepnir it seems that you didn't load `lspsaga` configuration correctly or must be an conflict load

@kayuxcodes are you referring to me?

I have loaded lspsaga from an external file, `plugins/lsp/lspsaga.lua`

**Comment by diegoulloao** [comment]
@kayuxcodes when I move the setup call to the function inside the `config` property in packer it works, like this:
```lua
  use({
    "nvimdev/lspsaga.nvim",
    after = "nvim-lspconfig",
    config = function()
      require("lspsaga").setup({})
    end,
  }) -- enhanced lsp server autocompletion for cmp ui

```

but I want to have the setup in a different file.

**Comment by diegoulloao** [comment]
Ok I realized that removing: `after = 'nvim-lspconfig'` fixes the issue.
Also `:Lspsaga lsp_finder` was replaced by just `:Lspsaga finder`

Hope it be useful.
