### ISSUE TITLE
`lsp_finder` throws an error on latest

### ISSUE THREAD

**Issue by jgchristopher** [nvimdev/lspsaga.nvim#1161]
### Describe the bug

When running `:Lspsaga lsp_finder` I get the following error. This is using the typescript lsp in lazyvim. 

```
   Error  09:12:29 msg_show.lua_error Error executing Lua callback: .../share/LazyVim/lazy/lspsaga.nvim/lua/lspsaga/command.lua:71: attempt to call a nil value
stack traceback:
	.../share/LazyVim/lazy/lspsaga.nvim/lua/lspsaga/command.lua:71: in function 'load_command'
	...local/share/LazyVim/lazy/lspsaga.nvim/plugin/lspsaga.lua:8: in function <...local/share/LazyVim/lazy/lspsaga.nvim/plugin/lspsaga.lua:7>
```

### Steps to reproduce

I have tested using a default config of Lazyvim with typescript language server installed. 

Lazyvim config: https://github.com/jgchristopher/TestLazyVimConfig

This is one of the Typescript repos I was working in and getting the error. https://github.com/jgchristopher/obsidian-clipper

rolling back to lspsaga commit `4f075452c466df263e69ae142f6659dcf9324bf6` works. This was the previous version I was on. 

### Expected behavior

Before updating to latest the `lsp_finder` would come up as expected. 

### Neovim version (nvim -v)

0.9.1

### lspsaga commit

d8fca84e8cb9a53f5d511b90e47ff485c24aae20

### Terminal name/version

wezterm 20230408-112425-69ae8472

**Comment by alextrastero** [comment]
Now it's `finder`, not `lsp_finder`

**Comment by digitallyserviced** [comment]
@jgchristopher update your mappings what @alextrastero said

**Comment by jgchristopher** [comment]
ah, ok. Thanks!
