### ISSUE TITLE
使用finder，窗口异常，并报错

### ISSUE THREAD

**Issue by CnsMaple** [nvimdev/lspsaga.nvim#1162]
### Describe the bug

最小配置下：
![image](https://github.com/nvimdev/lspsaga.nvim/assets/92523839/24d393c2-2297-4a72-a093-bb0edeea8e15)

### Steps to reproduce

1. 使用finder

### Expected behavior

none

### Neovim version (nvim -v)

0.9.1

### lspsaga commit

d8fca84

### Terminal name/version

wsl

**Comment by CnsMaple** [comment]
回退了之前的版本，也清了配置重载一次，都不行了

**Comment by glepnir** [comment]
border 设置 `none` 了？

**Comment by glepnir** [comment]
用solid 替代none 比较好

**Comment by CnsMaple** [comment]
我是看文档的，设成了：`border = { '╭', '─', '╮', '│', '╯', '─', '╰', '│' }`
但是，一开始设置完是起效果的，但是，更新了一下就全部报错了。回退也无果

**Comment by glepnir** [comment]
这是rounded 。
