### ISSUE TITLE
Plugin UI is not as expected

### ISSUE THREAD

**Issue by kayuxcodes** [nvimdev/lspsaga.nvim#1165]
i want to change the `lspsaga` **UI** from this:
![diag](https://github.com/nvimdev/lspsaga.nvim/assets/116302048/30552fbf-7425-42fa-8f19-ae802a8d542f)
to this:
![wn6lgpmj6ve91](https://github.com/nvimdev/lspsaga.nvim/assets/116302048/99d31202-0a4d-413a-957c-664652c6b565)
and for finder from this:
![finder](https://github.com/nvimdev/lspsaga.nvim/assets/116302048/4234ffd7-1375-4cb7-894a-9c7f531cff96)
to this:
![tss](https://github.com/nvimdev/lspsaga.nvim/assets/116302048/22d1102f-a494-4f2e-a7c9-2f33cf2ff28c)

its seems this is the old **UI**, I suggested to provide this **UI** its looks amazing.

**Comment by glepnir** [comment]
compare I think now is more useful and clean


![image](https://github.com/nvimdev/lspsaga.nvim/assets/41671631/7c48ee22-c467-4c55-b635-7331f4583fdb)

**Comment by glepnir** [comment]
about jump it has been change long time. You like that arrow ? sometimes is not work if jump window too big or normal window a bit small.

**Comment by glepnir** [comment]
In recent versions I did remove a lot of ui elements. The overall look is very simple. So you're disappointed by that. I can understand.

**Comment by glepnir** [comment]
maybe i should open a new issue to listen how people think  the ui. then do some change

**Comment by glepnir** [comment]
it just show filename I don't think is useful ..you can't see detail of the line code .

**Comment by kayuxcodes** [comment]
@glepnir I  just want to know if there is any `UI` enhancement? I just notice that you've been updating the plugin.

**Comment by glepnir** [comment]
yep continue update . maybe one day i have new idea of ui . I will rewrite ui relate . or there have better ui design . you can show me .

**Comment by kayuxcodes** [comment]
@glepnir I found users looking to the previous UI to setting it up, it's super amazing and aesthetic you can scroll up and look at screenshots, maybe you want also edit the `hover_doc` UI now is so simple and have so much padding, it even tho you could ask the users how they want the UI
