### ISSUE TITLE
建议使用 tag 来管理稳定版本

### ISSUE THREAD

**Issue by liaohui5** [nvimdev/lspsaga.nvim#1167]
建议使用 多个 tag 来管理版本迭代, 因为在 lazy.nvim 或者 packer.nvim 中, 可以使用 `{version = "v1.*"}` 这样的方式来更新, 

而不是每修改一次代码就提交到 main 分支就更新一次, 这样很容易报错, 这样的话开发新功能不会影响到稳定版本, 而且喜欢最新功能的

也可以不用 `{version="v1.*"}`, 一直保持最新

**Comment by glepnir** [comment]
使用commit 。 tag 只会在稳定的版本打。
