### ISSUE TITLE
Bugs with jumping to symbol from outline

### ISSUE THREAD

**Issue by HungryJoe** [nvimdev/lspsaga.nvim#1168]
### Describe the bug

After jumping to a symbol from the Lspsaga outline, the preview window doesn't go away, and running `:Lspsaga outline` again opens a new outline window instead of closing the existing one.

### Steps to reproduce

Use minimum config here: https://github.com/HungryJoe/neovim_config/tree/minimal-repro-lspsaga-bug
```bash
nvim -u neovim_config/config/init.vim.minimal lua/lspsaga/symbol/outline.lua
```
1. Restart neovim to let Paq install plugins
2. `:Lspsaga outline`
3. Pick a symbol
4. Jump to that symbol (default keybinding is `e`)
5. `:Lspsaga outline`

### Expected behavior

The preview window goes away after step (3), and the original outline window closes after (4).

### Neovim version (nvim -v)

v0.9.0

### lspsaga commit

d8fca84e8cb9a53f5d511b90e47ff485c24aae20

### Terminal name/version

iTerm2 3.4.19

**Comment by HungryJoe** [comment]
Thanks so much for the quick fix @glepnir!

**Comment by glepnir** [comment]
usually just some small mistake in this version. so fix is easy.
