### ISSUE TITLE
Some explanations about "improve lsp experences in neovim"

### ISSUE THREAD

**Issue by CnsMaple** [nvimdev/lspsaga.nvim#1169]
看介绍，我只知，它对lsp有改善，从我这几天的使用体验上来看，好像只是对原来的lsp做一个ui和搜索集成，rename的项目级的重命名，好像也是多了一次模糊搜索。

我想知道详细改善的东西，如果只是做了一个ui和搜索集成，也可以说一下，这也是提供了不少的便利的功能。

**Comment by glepnir** [comment]
hover 支持多个server。code action 获取cursor diagnostic 等

**Comment by CnsMaple** [comment]
我有个问题，就是使用finder的时候，显示的文件都是预先打开的？我有个几g的python项目，我这几天也在使用这个插件，问题还挺多的，其中一个是：我对某个变量进行finder，像是打开了几千个buffer，内存和cpu全满了，有没有办法是预览形式什么的？

**Comment by glepnir** [comment]
几千个buffer 会被wipe掉当你关掉finder 。finder 的左边窗口导航需要获取所在行代码    为了清晰的浏览。 这里就会add buffer 。内存是因为load 太多buffer 读取了太多文件。能想到的解决办法是lazy render 。只渲染当前buffer 可见区域内。避免一次性load

**Comment by glepnir** [comment]
或者 ignore FileType event 。只加载文本当使用shuttle的时候trigger filetype

**Comment by CnsMaple** [comment]
我关掉finder的时候，虽然buffer关了，但是，它们正在进行分析，这个可关不掉。然后导致要等到所有buffer分析完了，才能断续用finder

**Comment by glepnir** [comment]
> 但是，它们正在进行分析，这个可关不掉。

IDK ? 什么叫进行分析？

**Comment by CnsMaple** [comment]
比如，每打开一个文件，pyright会进行分析，在这个文件分析的时候，不用不了其他操作了

**Comment by glepnir** [comment]
干掉FileType 就行了。 前几个版本是这么做的。 最近我吧lspconfig改了改 以为会好点。 pyright 本身性能就不行。。

**Comment by CnsMaple** [comment]
好像还有挺多问题的，对于小一些代码文件倒是没什么，我一开始用就是大文件，性能问题有点严重，我还不知怎么处理，也不知怎么让你复现，重命名的时候，更是有卡爆的可能。有时候会让cmp失效？，失效这个我不清楚是不是你这个插件导致的。之前都是不会发现cmp失效的，我对lsp还是比效看重的，想晚点来参与一下你这个项目。

**Comment by CnsMaple** [comment]
因为cmp失效了，我又会使用LspRestart，然后又有概率触发之前那个问题。#1127
重写后，前段时间可能是会比较多问题的，还是能理解一下的。

**Comment by glepnir** [comment]
rename 卡？ 默认不卡？ cmp 和我没什么关系。 这个插件不处理completion request

**Comment by CnsMaple** [comment]
默认的一个回车就改好了，使用插件的rename要等10几秒

**Comment by glepnir** [comment]
finder 提升了。 rename 提供重现的步骤 创建issue
