### ISSUE TITLE
Warn about breaking changes or use SemVer

### ISSUE THREAD

**Issue by lordvidex** [nvimdev/lspsaga.nvim#1172]
**Is your feature request related to a problem? Please describe.**
A mistake running :PackerSync updates the package up to the latest point and this breaks the package

**Describe the solution you'd like**
Every breaking change should be tagged

**Additional context**
I just discovered that `:Lspsaga lsp_finder` broke because it has been renamed to `:Lspsaga finder`

**Comment by glepnir** [comment]
not sure how many people use this plugin now. pr welcome.

**Comment by lordvidex** [comment]
@glepnir The plugin has about 2k+ stars, of course, people use it, you can fix changes on separate branches from main though, and let people know about anything you're pushing to main that might break.
For example: Packer can be used to only update versions of plugins like:
```lua
use {
  'myusername/example',        -- The plugin location string
  tag = 'v0.1.2', -- doesn't update on PackerSync
  }
```

For now, I've fixed it by using the commit key instead.

**Comment by glepnir** [comment]
tag just in stable version I think. you can pin a commit .
