### ISSUE TITLE
The `impl` icon is not appearing when an interface is implemented in different packages or files

### ISSUE THREAD

**Issue by mortymacs** [nvimdev/lspsaga.nvim#1174]
### Describe the bug

The `impl` icon is not appearing when an interface is implemented in different packages or files, while LSP can find them:

![image](https://github.com/nvimdev/lspsaga.nvim/assets/1261448/e95aabfc-889a-45ac-9f81-4fea236f9237)

### Steps to reproduce

You can clone a Go project, like https://github.com/atkrad/wait4x/, which contains an interface in `checker/checker.go`. When you open the file, it doesn't show that icon.

### Expected behavior

The icon is expected to appear.

### Neovim version (nvim -v)

v0.9.1

### lspsaga commit

8ea2afc

### Terminal name/version

alacritty 0.12.0

**Comment by glepnir** [comment]
is disable by default

**Comment by SimonYde** [comment]
@glepnir 

> is disable by default

[the docs](https://nvimdev.github.io/lspsaga/implement) do not reflect this.
