### ISSUE TITLE
Edit not going into buffer

### ISSUE THREAD

**Issue by lucasquin** [nvimdev/lspsaga.nvim#1175]
### Describe the bug

Edit not going into buffer

![image](https://github.com/nvimdev/lspsaga.nvim/assets/65108092/7ca687a1-f744-4f2a-8614-9264d7a1f56b)

I went back a few commits to check, and the commit "a224b2ac682fddd894f665a474a4c31fa0f138c2" worked fine

### Steps to reproduce

My lspsaga config:

```
saga.setup({
	definition = {
		edit = "<CR>",
	}
})
```

### Expected behavior

Open the buffer completely

### Neovim version (nvim -v)

0.10

### lspsaga commit

0add23a82288af0d81ddb6177496b49f3e247cfb

### Terminal name/version

Windows Terminal and Gnome Shell

**Comment by glepnir** [comment]
`definition.keys` . see https://dev.neovim.pro
