### ISSUE TITLE
Customise the width of the Finder preview.

### ISSUE THREAD

**Issue by Fausto-Korpsvart** [nvimdev/lspsaga.nvim#1176]
LSP Saga has been updated and after changing the settings and getting it working again, I don't like that preview in `Finder` spans the whole width of the window, it's practically having its 'new' normal mode in floating mode.

In the new documentation it only covers the basics, the finder can change its width with `left_width`, but the preview can't change the width, and it's a bit annoying that a floating window covers all the space.

I have seen a closed issue that said something about this and the way I proposed was to change this with the `max_width` option where required, but this doesn't work.

How can I change the width of this preview?

**Comment by glepnir** [comment]
it's not preview window. it's a peek window . you can do any edit on that window. right width is `current window width - left window width `

**Comment by Fausto-Korpsvart** [comment]
> it's not preview window. it's a peek window . you can do any edit on that window by using `keys.shuttle` jump in or jump to left . it's useful than open when you just want do once edit
> 
> right width is `current window width - left window width ` . before it just a preview so `max_width` might make sense. now i don't think there is necessary add `max_width`

Well, Peek Window, and I know, I know that in the peek window you can quickly edit and do many more things, I know that with `[w` you can jump between these windows, I have read the documentation, and it is great that you can have that editing option, but the problem is not that it is a peek or preview window, the problem is the customisation of the width of that window, whether it is peek or preview.

The closed problem I was referring to is this: [add max_width to all different views](https://github.com/nvimdev/lspsaga.nvim/issues/1102), in this closed problem it is proposed to use `max_width` for the different views.

I'm going to go a bit overboard with the example, but I think the screenshots will show very well what I mean, and I know it's possible you know what I mean.

![Saga-Finder-Floating](https://github.com/nvimdev/lspsaga.nvim/assets/47998118/dec4de76-2494-4fc5-9c93-27b823e68450)

All that empty space covering the whole width of the window is unnecessary, I mean, it's a floating window and you could have the option to customize the width.

I get it when it's in normal mode, obviously it should cover the whole width of the window, but in the floating window it's not necessary.

![Saga-Finder-Normal](https://github.com/nvimdev/lspsaga.nvim/assets/47998118/c6937948-53dd-4165-bf36-382b5b017212)

And you can see that it's only a few pixels that differentiate the floating window from the normal window, but it's practically the same width.

Don't take this the wrong way, it's not my intention, I really like this plugin, the only thing I want and would appreciate, is to know how to change that width so that it doesn't cover all the space.
For example, in [Mini Files](https://github.com/echasnovski/mini.files), you can configure this behaviour and the windows are fully editable.

I would appreciate a way to do this configuration, thanks.

**Comment by glepnir** [comment]
2

**Comment by Fausto-Korpsvart** [comment]
Thank you!
