### ISSUE TITLE
Facing this error

### ISSUE THREAD

**Issue by niksingh710** [nvimdev/lspsaga.nvim#1177]
### Describe the bug

![image](https://github.com/nvimdev/lspsaga.nvim/assets/60490474/c06ee2fd-e7c3-40cb-ab40-00d651dfe8e7)

### Steps to reproduce

just update to the latest commit and try to use code actions

### Expected behavior

should not show this error

### Neovim version (nvim -v)

NVIM v0.9.1 Build type: Release LuaJIT 2.1.0-beta3     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/share/nvim"  Run :checkhealth for more info

### lspsaga commit

2144a7a

### Terminal name/version

foot

**Comment by glepnir** [comment]
provide example language code

**Comment by niksingh710** [comment]
> provide example language code

use this
```python
print(Hello)
```

i use ruff for python.
so this print statement is not having `"` it should give error and then calling code_action on it shows popup with options and then scrolling in that popup shows this error
