### ISSUE TITLE
multiple textDocument/documentHighlight and textDocument/codeAction

### ISSUE THREAD

**Issue by qq123538** [nvimdev/lspsaga.nvim#1181]
### Describe the bug

In the plugin of lspsaga, i enable the lightbulb. And i always get multiple textDocument/documentHighlight and textDocument/codeAction when i move the cursor, such as: j, k.

My configuration is :
<img width="879" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/55847117/5947fd51-e5dd-46e9-81cc-8ade48d6b841">

LspLog:

[LspLog.txt](https://github.com/nvimdev/lspsaga.nvim/files/12072551/LspLog.txt)

Btw, it works well before i update plugins.

### Steps to reproduce

1. enable lightbulb;
2. move cursor in file.

### Expected behavior

Lsp don't always trigger codeAction and documentHighlight when moving cursor.

### Neovim version (nvim -v)

0.9.1

### lspsaga commit

95ec55d

### Terminal name/version

windows terminal and wsl2

**Comment by glepnir** [comment]
` textDocument/documentHighlight ` this method not in lspsaga.  check your  `au CursorMoved`  in cmdline.

**Comment by glepnir** [comment]
I can't reproduce this ..

**Comment by qq123538** [comment]
this is output of `au CursorMoved`
<img width="1115" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/55847117/0455600d-5d61-4f0b-b68f-baadd37be229">

**Comment by glepnir** [comment]
looks normal just for `SagaLightBulb` augroup .

**Comment by qq123538** [comment]
![Lspsaga](https://github.com/nvimdev/lspsaga.nvim/assets/55847117/c623c2fc-82ab-400d-bb1d-fde60ac81839)

Look at right bottom in the picture. When i move cursor, i always get the tips. 
Btw, I use the plugin of gitsigns and null-ls with lspsaga. I'm not sure what cause it.

**Comment by qq123538** [comment]
How can i check who sends `textDocument/documentHighlight` and `textDocument/codeAction`?

**Comment by glepnir** [comment]
it's print by null-ls . for lspsaga the lightbulb module works like before. it just send request and check result if have render sign and virtual text . don't execute these actions.

**Comment by glepnir** [comment]
IDK need check your lsp relate plugins.  maybe i will try with null-ls later if i can reproduce ..

**Comment by qq123538** [comment]
The message is less than before after I add `debounce = 500`

**Comment by qq123538** [comment]
I have another question why background color in finder window looks different with normal background color? It works fine before i update lspsaga.

<img width="1660" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/55847117/78a8374c-1a7e-4981-9b58-71730c0d87f6">

**Comment by glepnir** [comment]
now it use `Normalfloat` link by default. you can  set `SagaNormal`same as your `Normal `

**Comment by qq123538** [comment]
> now it use `Normalfloat` link by default. you can set `SagaNormal`same as your `Normal `

It doesn't work. Where is wrong with my setting?

![image](https://github.com/nvimdev/lspsaga.nvim/assets/55847117/0999ccf3-f116-4dbc-8ff3-3dd09e675873)

**Comment by glepnir** [comment]
config highlight in your colorscheme or config like 

```lua
vim.api.nvim_set_hl(0,'SagaNormal', {link ='Normal', default = true })
```
