### ISSUE TITLE
use relative path to project root path instead of absolute path in finder

### ISSUE THREAD

**Issue by xvvhang** [nvimdev/lspsaga.nvim#1183]
**Is your feature request related to a problem? Please describe.**
Absolute paths are often too long to read in finder floating window. 

**Describe the solution you'd like**
Using relative path to project root path instead of absolute path may improve user experiences. It's much easier to figure out related files.

**Describe alternatives you've considered**
Using relative path or not may be an option in configuration.

**Additional context**
![Screenshot 2023-07-18 at 11 04 20 AM](https://github.com/nvimdev/lspsaga.nvim/assets/46291413/af65ba20-6a29-4f7c-a601-3313639906a0)

**Comment by glepnir** [comment]
it will use project root to sub path first. so check lspinfo I think your root config has some problem ?

**Comment by glepnir** [comment]
it works well i think ? check your lua_ls root config

![image](https://github.com/nvimdev/lspsaga.nvim/assets/41671631/9aa45d3a-bf3e-4355-a9c3-80fa277bb431)

**Comment by xvvhang** [comment]
Thanks for reply. I use nvim-lspconfig's default configuration and lspinfo shows that the root directory is correct. I left `root_dir` empty in nvim-lspconfig and I don't know if this is caused by that.

![Screenshot 2023-07-18 at 4 49 12 PM](https://github.com/nvimdev/lspsaga.nvim/assets/46291413/914f4b60-2623-41c5-af4e-985ff1e68815)

**Comment by glepnir** [comment]
update and try it thanks

**Comment by xvvhang** [comment]
Problem solved in Lua files. But it still use absolute in a Vue project.

**Comment by glepnir** [comment]
what's the root like ?

**Comment by xvvhang** [comment]
It's a Vue3 app created by official command line tool (I think finder has the same behavior in Vue2 apps too). The structure looks like:

![Screenshot 2023-07-19 at 10 11 45 AM](https://github.com/nvimdev/lspsaga.nvim/assets/46291413/033032c5-c797-4a63-9a8f-8fa60c9c3940)
