### ISSUE TITLE
Lspsaga outline got an error after try to jump to a symbol in python.

### ISSUE THREAD

**Issue by nkta3m** [nvimdev/lspsaga.nvim#1185]
### Describe the bug

Lspsaga outline got an error after try to jump to a symbol in python.

lsp server is pylsp

![254104341-b8b365a4-cb40-4913-a97a-5eb6071829a5](https://github.com/nvimdev/lspsaga.nvim/assets/13484700/2d75fab2-3ba1-4a55-95f1-8fceb1fb41fd)

### Steps to reproduce

1. open python file
2. Lsp Toggle outline
3. select func and enter

### Expected behavior

correct jump to symbol

### Neovim version (nvim -v)

nvim 0.9.1

### lspsaga commit

95ec55dfd5355c90f1cee834bd415e1d2b5d9854

### Terminal name/version

Alacritty

**Comment by ayamir** [comment]
Can repro when python lsp is `pylsp`.
