### ISSUE TITLE
Error when opening code action window

### ISSUE THREAD

**Issue by MariaSolOs** [nvimdev/lspsaga.nvim#1191]
### Describe the bug

When opening the code action window with a lot of items, the following error appears:
<img width="968" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/62502207/10840b18-6f71-4b03-8793-9f2428be144b">

<img width="1199" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/62502207/c91a596c-27b6-4fdf-b4a1-bfc058b6073a">

### Steps to reproduce

1. Install Lspsaga with the default settings.
2. Open a Rust file with `rust_analyzer` activated. Request code actions in the field of a struct.

### Expected behavior

For there to be no error.

### Neovim version (nvim -v)

v0.10.0-dev-684+g80cf0f3d2

### lspsaga commit

adfd5533e4e5627f74bc9896ca8936cede3a26ce

### Terminal name/version

kitty 0.28.1

**Comment by glepnir** [comment]
there need give it max height i think...

**Comment by MariaSolOs** [comment]
> there need give it max height i think...

But such bound would be set by this plugin right?

**Comment by glepnir** [comment]
yep . there should give it an option `code_action.max_height` .I will fix it later.
