### ISSUE TITLE
Rename not work

### ISSUE THREAD

**Issue by johnny-mh** [nvimdev/lspsaga.nvim#1195]
### Describe the bug

Rename does nothing. I've tried with typescript

### Steps to reproduce

1. :Lspsaga rename
2. replace name
3. \<CR\>
4. Float closes but nothing happens

I tried `:lua vim.lsp.buf.rename()` but it works properly.

### Expected behavior

Module name properly changed.

### Neovim version (nvim -v)

v0.10.0-dev-653+gfbeef0d4e-Homebrew

### lspsaga commit

20eef6

### Terminal name/version

alacrittty 0.12.2

**Comment by duongapollo** [comment]
same for me.

**Neovim version (latest)**
v0.9.1

**LSPSaga (latest commit)**

**Languages used**
Typescript, Typescript React

**Terminal used**
Alacritty 0.12.2

**Comment by yorik1984** [comment]
Same for me
`:lua vim.lsp.buf.rename()` work fine, but after command `:Lspsaga rename` stop working.
**Neovim version (latest)**
v0.9.1

**LSPSaga (latest commit)**

**Languages used**
Lua

**Nvim-Qt**

**Comment by johnny-mh** [comment]
@glepnir Thanks! it works!

**Comment by body20002** [comment]
I'm on the latest commit https://github.com/nvimdev/lspsaga.nvim/commit/96d001721f5d4c47a6c5ed54124e3b604b7bbca8 and  `:Lspsaga rename` not working with typescript, but works with python

#### Neovim version (latest)
v0.9.1

#### LSPSaga (latest commit)
https://github.com/nvimdev/lspsaga.nvim/commit/96d001721f5d4c47a6c5ed54124e3b604b7bbca8

#### Languages used
Typescript, Typescript React, python

#### Terminal used
kitty 0.28.1

**Comment by glepnir** [comment]
can't reproduce. ts react works fine .

**Comment by body20002** [comment]
@glepnir when I try to rename I get this stack traceback after I press enter

`Error executing vim.schedule lua callback: ...share/nvim/lazy/lspsaga.nvim/lua/lspsaga/rename/init.lua:176: attempt to index local 'result' (a nil value)
stack traceback:
        ...share/nvim/lazy/lspsaga.nvim/lua/lspsaga/rename/init.lua:176: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp/buf.lua:321: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1394: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
        `
        
[config](https://gist.github.com/body20002/23cafe4b19906e02ba8493d6cbdc1995)

**Comment by glepnir** [comment]
how to reproduce . could you provide an example code  I can't reproduce it on ts or react .

**Comment by body20002** [comment]
@glepnir It's working now after updating, thank you

**Comment by gusallc** [comment]
Has anyone tried it in Java, because it doesn't work for me :(

:lua vim.lsp.buf.rename() working
:Lspsaga rename not working

Neovim version (latest)
v0.9.5

LSPSaga (latest commit - 0e2e116)

Languages used
Java

Terminal used
Alacritty 0.13.2
