### ISSUE TITLE
vsplit in finder throws error

### ISSUE THREAD

**Issue by fummeys** [nvimdev/lspsaga.nvim#1200]
### Describe the bug

finder throws an error whenever i try to vsplit in the finder float
`E5108: Error executing lua: ...pack/packer/opt/lspsaga.nvim/lua/lspsaga/finder/init.lua:401: attempt to index field 'range' (a nil value)
stack traceback:
        ...pack/packer/opt/lspsaga.nvim/lua/lspsaga/finder/init.lua:401: in function <...pack/packer/opt/lspsaga.nvim/lua/lspsaga/finder/init.lua:388>
`
![image](https://github.com/nvimdev/lspsaga.nvim/assets/53976947/4aa43a7b-af86-473b-bd95-2fd1fcfd1503)

### Steps to reproduce

step 1: move cursor to a function or a variable that is imported from another file
step 2: navigate in the finder float to the definition and try to vsplit it(my keybind is 's' use your keybind here)

### Expected behavior

It is supposed to jump to the definition in another pane.

### Neovim version (nvim -v)

NVIM v0.9.1

### lspsaga commit

f4bfc448a837bb913bd971676ebcd94e0f3134c0 

### Terminal name/version

GNOME Terminal 3.48.1 using VTE 0.72.2

**Comment by glepnir** [comment]
i think you need provide more information if you want your issue fix quickly .which language and how to reproduce ?

**Comment by fummeys** [comment]
> i think you need provide more information if you want your issue fix quickly .which language and how to reproduce ?

Language tested: PHP, typescript (React).

**to reproduce:**
  move the cursor on a function, class or method in another file and then run ': Lspsaga finder def'
this window pops up
![image](https://github.com/nvimdev/lspsaga.nvim/assets/53976947/05b0f2bb-80e4-4843-9d13-93ede529fdc4)

then press 's' for vsplit. it is suppose to open a new pane with the definition
note!: it works for references
