### ISSUE TITLE
are we supporting inlay hints?

### ISSUE THREAD

**Issue by Martinits** [nvimdev/lspsaga.nvim#1204]
As the title.

**Comment by glepnir** [comment]
neovim nightly support inlayhint.

**Comment by Martinits** [comment]
@glepnir Well I mean will lspsaga display things like function return type, variable type with inlay hint? I didn't see such and there seems no configuration about this.

**Comment by glepnir** [comment]
inlay hint need `visual text` support `inline` propterty and it implement in neovim 0.10 version (head /nightly)  and in 0.10 it has builtin inlay hint you can enable it by using `vim.lsp.inlay_hint.enable` . nothing to do on this plugin.

**Comment by Martinits** [comment]
OK! Thanks for help.

**Comment by Martinits** [comment]
OK! Thanks for help.
