### ISSUE TITLE
When using default diff, symbol_in_winbar only appears for the leftmost window

### ISSUE THREAD

**Issue by mang0bang0** [nvimdev/lspsaga.nvim#1206]
### Describe the bug

Using Neovim's default diff mode, enabling breadcrumbs in the winbar only gives the breadcrumbs to the leftmost window. No other window gets the breadcrumbs. It looks like this:
![Screenshot from 2023-07-23 03-38-13](https://github.com/nvimdev/lspsaga.nvim/assets/130512302/5939cdda-250e-4701-9212-5052a2ff3575)

As a side effect of this, the same line in both diffs are not aligned horizontally.

### Steps to reproduce

1. Use a typical configuration to set up LSP and LSPSaga, and enable breadcrumbs (symbol_in_winbar) in LSPSaga.
2. `nvim -d file1 file2` on any files that use LSP. I can also reproduce this with 3 files too.

### Expected behavior

The breadcrumbs should be present for all windows, and therefore the lines would be horizontally aligned again.

### Neovim version (nvim -v)

v0.10.0-dev-709+gce56ad2ba

### lspsaga commit

4c097f7

### Terminal name/version

kitty 0.29.1

**Comment by glepnir** [comment]
when you move cursor to another window. breadcrumbs not appear in it ?

**Comment by mang0bang0** [comment]
It does not appear. Does it work on your end?

**Comment by mang0bang0** [comment]
Looks fixed! It does not show up unless I move it to the other window, but it works great now!
