### ISSUE TITLE
Not working lsp saga find function

### ISSUE THREAD

**Issue by NykuluzC** [nvimdev/lspsaga.nvim#1207]
### Describe the bug
(Keybind is)

<img width="861" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/109895517/503b8014-0b81-41c6-a171-18e6ebaab02b">

<img width="1433" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/109895517/38d0058c-04ce-4c49-9223-087a39e129f0">

When I attempt to use <Leader> gf which I assigned get the functions implementation it does not it throws this error everytime gd which is get definition works and code actions.

### Steps to reproduce

<Leader> gf trigger
<img width="1440" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/109895517/0570294b-9b72-4aa1-b17c-3000a027c47b">

<img width="1440" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/109895517/88decb6f-15e5-4ad4-af55-0ffde00758d1">
<Leader> gd trigger works

<img width="1436" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/109895517/76431471-7257-4bdf-85a7-ddefb549d523">
<Leader> gf trigger doesn't work 

### Expected behavior

Shows the Function Implementation and Connection overall

![image](https://github.com/nvimdev/lspsaga.nvim/assets/109895517/4499995f-febb-42aa-a85e-e1266fbc5e8f)

### Neovim version (nvim -v)

0.9.1

### lspsaga commit

main

### Terminal name/version

Iterm2

**Comment by NykuluzC** [comment]
> ### Describe the bug
> (Keybind is)
> 
> <img alt="image" width="861" src="https://user-images.githubusercontent.com/109895517/255491806-503b8014-0b81-41c6-a171-18e6ebaab02b.png"> <img alt="image" width="1433" src="https://user-images.githubusercontent.com/109895517/255486752-38d0058c-04ce-4c49-9223-087a39e129f0.png">
> When I attempt to use gf which I assigned get the functions implementation it does not it throws this error everytime gd which is get definition works and code actions.
> 
> ### Steps to reproduce
> gf trigger <img alt="image" width="1440" src="https://user-images.githubusercontent.com/109895517/255487098-0570294b-9b72-4aa1-b17c-3000a027c47b.png">
> 
> <img alt="image" width="1440" src="https://user-images.githubusercontent.com/109895517/255487129-88decb6f-15e5-4ad4-af55-0ffde00758d1.png"> gd trigger works <img alt="image" width="1436" src="https://user-images.githubusercontent.com/109895517/255487182-76431471-7257-4bdf-85a7-ddefb549d523.png"> gf trigger doesn't work
> ### Expected behavior
> Shows the Function Implementation and Connection overall
> 
> ![image](https://user-images.githubusercontent.com/109895517/255487405-4499995f-febb-42aa-a85e-e1266fbc5e8f.png)
> 
> ### Neovim version (nvim -v)
> 0.9.1
> 
> ### lspsaga commit
> main
> 
> ### Terminal name/version
> Iterm2

<img width="1440" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/109895517/91e94d53-0f69-43be-8884-03cae9d84871">

Lspsaga finder in normal mode line works but the shortcut doesn't

**Comment by glepnir** [comment]
command is `Lspsaga finder` no longer `lsp_finder`
