### ISSUE TITLE
 Open outline with cursor at current element

### ISSUE THREAD

**Issue by lolpie244** [nvimdev/lspsaga.nvim#1211]
Currently, when running `:Lspsaga outline` the outline opens with the cursor at the beginning of the outline, but it would be nice if the cursor will be placed at the current element.

Example:
```
# 1
## 1.1
## 1.2
<cursor_here>
# 2
```
and run `:Lspsaga outline`, the cursor will be at `1.2`

**Comment by lolpie244** [comment]
Are there any parameters that should be applied in the setup? Because it seems to not work as expected
[Screencast from 2023-07-25 16-14-51.webm](https://github.com/nvimdev/lspsaga.nvim/assets/86479624/cca15e02-c068-4206-acb6-390121d0b0c1)

**Comment by glepnir** [comment]
update and retry

**Comment by lolpie244** [comment]
same as in the video from this [message](https://github.com/nvimdev/lspsaga.nvim/issues/1211#issuecomment-1649828892)

**Comment by glepnir** [comment]
you must in title line like `## 1.2`  . server just parse title head.  marksman does not parse those text .

**Comment by lolpie244** [comment]
oh, I see. It works, thanks!

**Comment by lolpie244** [comment]
Thanks! Now it works perfectly
