### ISSUE TITLE
Lspsaga goto_defination jump after, <C-o> and <C-i> can't not work properly 

### ISSUE THREAD

**Issue by Meigumikato** [nvimdev/lspsaga.nvim#1212]
### Describe the bug

use goto_definantion after, <C-o> and <C-i> can't jump to expected location, but use originally vim.lsp.goto_defination <C-o> and <C-i> work proper.

### Steps to reproduce

:Lspsaga goto_defination
<C-o>
<C-i>

### Expected behavior

use <C-o> <C-i> can jump to orginal file localtion 

### Neovim version (nvim -v)

NVIM v0.9.1

### lspsaga commit

 commit fa997cc

### Terminal name/version

Alacritty Version 0.12.2 (9d9982d)

**Comment by glepnir** [comment]
please provide reproduce step. if you want your issue get solved. I can't reproduce

**Comment by Meigumikato** [comment]
I use LazyVim and use require("lazyvim.util").on_attach() method replace origin gd keymap to Lspsaga goto_defination, but when i recent navigation in  C codebase use `<C-o>`  can't jump back to previous location where i press `gd` ,  whereas it's as expected when reset back to LazyVim orginal `gd` keymap.

**Comment by Meigumikato** [comment]
I first use gd to jump to defination  then use `<C-o>` will jump to arbitary file and code location.

**Comment by glepnir** [comment]
I can't reproduce , `goto_definition` just replace default handler . it still call `vim.lsp.buf.definition` and `tagstack` will set before handler run . so I don't get your problem.

![Untitled](https://github.com/nvimdev/lspsaga.nvim/assets/41671631/ce39a088-3663-410f-995b-3c2829559570)

**Comment by arxra** [comment]
I'm in the same situation; I believe this problem to be with how LazyVim sets the keybinds for LSP and not a issue with LspSaga. We should raise the issue with LazyVim instead, there is nothing to do here

**Comment by glepnir** [comment]
close then.

**Comment by arxra** [comment]
According [to lazyvim contributors](https://github.com/LazyVim/LazyVim/issues/1235),  @Meigumikato you'll [need to disable the default keybinds](https://www.lazyvim.org/plugins/lsp#%EF%B8%8F-customizing-lsp-keymaps). Was able to get it working after that
