### ISSUE TITLE
Make name in rename float editable

### ISSUE THREAD

**Issue by mikehaertl** [nvimdev/lspsaga.nvim#1214]
When I open the rename float, the current name is prefilled in the window:

![image](https://github.com/nvimdev/lspsaga.nvim/assets/675062/89ba9e9c-59bc-4878-ac7e-a60ff7f97b1d)

When I start typing, the prefilled name is deleted. Even when I jump to the end with <kbd>End</kbd> key and press <kbd>Del</kbd> the whole name is deleted:

![image](https://github.com/nvimdev/lspsaga.nvim/assets/675062/552cb9ef-6aa0-439d-9fa3-2330b9739b00)

![image](https://github.com/nvimdev/lspsaga.nvim/assets/675062/3f402518-7a20-42fa-a5ae-3d0ec81ca6ad)

It would be nice if I could edit the prefilled name.

**Comment by mikehaertl** [comment]
Nevermind. I found that there's an `in_select` option that does what I want.

**Comment by glepnir** [comment]
also you can pass mode from cmd `Lspsaga rename mode=i/n/v'
