### ISSUE TITLE
some code_actions not working on windows

### ISSUE THREAD

**Issue by geril2207** [nvimdev/lspsaga.nvim#1215]
### Describe the bug

I found that my eslint `disable next line` action does not do anything. I am using windows 10, same repro under wsl works fine.

https://github.com/nvimdev/lspsaga.nvim/assets/62308020/f2f3d82e-17e5-40d4-9a81-0d422f4b7181

### Steps to reproduce

1. Use windows
2. js/ts project with eslint
3. Make some error which could be resolved with eslint-disable-next-line
4. Try to execute code action with eslint-disable-next-line

### Expected behavior

Properly execute code action.

### Neovim version (nvim -v)

0.9.1

### lspsaga commit

557e6fd

### Terminal name/version

neovim-qt 0.2.18.9999

**Comment by glepnir** [comment]
does action preview can work move to that action. if works it will show action preview window

**Comment by glepnir** [comment]
no response close.

**Comment by glepnir** [comment]
because the diagnostics from lsp and eslint. the eslint action just fix eslint diagnostic the lsp diagnsotic still exist .

**Comment by geril2207** [comment]
@glepnir i am using eslint as lsp server from `nvim-lspconfig` and code_actions from eslint just dont apply(unlike `vim.lsp.buf.code_action`. Initially i thought that it was a Windows problem because of path(windows main separator is `\` instead of `/`) but when trying the same on linux, actions also didn't apply. How can i help you with repro?

**Comment by glepnir** [comment]
could you try neovim  head version

**Comment by geril2207** [comment]
yeah in `v0.10.0-dev-1011+g7bf0963d4` (todays version) the problem was gone.
