### ISSUE TITLE
E5108: Error executing lua vim/_editor.lua:341:

### ISSUE THREAD

**Issue by franklaranja** [nvimdev/lspsaga.nvim#1216]
### Describe the bug

When nvim starts i get this error message:

Error detected while processing LspAttach Autocommands for "*":
E5108: Error executing lua vim/_editor.lua:341: LspAttach Autocommands for "*"..s
cript nvim_exec2() called at LspAttach Autocommands for "*":0: Vim(echomsg):E114:
 Missing quote: "Error in packer_compiled: ...m/site/pack/packer/start/packer.nvi
m/lua/packer/load.lua:118: LspAttach Autocommands for \"*\"..LspAttach Autocomman
ds for \"*\": Vim(append):Error executing lua callback: **...pack/packer/opt/lspsag
a.nvim/lua/lspsaga/symbol/init.lua:199**: attempt to index field 'data' (a nil valu
e)
stack traceback:
        [C]: in function 'nvim_exec2'
        vim/_editor.lua:341: in function 'cmd'
        ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:179: in funct
ion <...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:175>
        [string ":lua"]:1: in main chunk
        [C]: in function 'nvim_exec_autocmds'
        .../com.termux/files/usr/share/nvim/runtime/lua/vim/lsp.lua:1531: in func
tion '_on_attach'
        .../com.termux/files/usr/share/nvim/runtime/lua/vim/lsp.lua:1358: in func
tion 'cb'
        vim/_editor.lua:263: in function <vim/_editor.lua:262>

I did nit change anything and it work correctly before. I have LspSaga installed with
packer and this config:

use ({
     'nvimdev/lspsaga.nvim',
     after = 'nvim-lspconfig',
     config = function()
     require('lspsaga').setup({
        lightbulb = { enable = false, },
       })
     end,
})

### Steps to reproduce

nvim <a file name>

### Expected behavior

i expect nvim to start without error messages

### Neovim version (nvim -v)

NVIM v0.9.0 Build type: Release LuaJIT 2.1.0-beta3

### lspsaga commit

what do you expect me to put in this field?

### Terminal name/version

termux

**Comment by glepnir** [comment]
packer issue with lazy load by using `event = 'LspAttach` use other event or `after` instead of

**Comment by franklaranja** [comment]
Hi Raphael,Thanks for your response.1. I use packer not lazy2. i used 'after = 'nvim-lspconfig' '3. I changed it to: requires =  "neovim/nvim-lspconfig"The problem continues...Regards,FrankPS why did you remove the documentation out of the github repo? It is a pain for people without a internet connection.-------- Original message --------From: Raphael ***@***.***>Date: Sat, Jul 29, 2023, 01:58To: "nvimdev/lspsaga.nvim" ***@***.***>Cc: Frank Laranja ***@***.***>, Author ***@***.***>Subject: Re: [nvimdev/lspsaga.nvim] E5108: Error executing lua vim/_editor.lua:341: (Issue #1216)
packer issue with lazy load by using event = 'LspAttach use other event or after instead of

**Comment by glepnir** [comment]
it's packer issue . so use after event like `BufReadPost` .when you do edit conig file you need PackerCompile to make it take effect.

**Comment by franklaranja** [comment]
that suggestion doesn't work either :(-------- Original message --------From: Raphael ***@***.***>Date: Tue, Aug 1, 2023, 07:24To: "nvimdev/lspsaga.nvim" ***@***.***>Cc: Frank Laranja ***@***.***>, Author ***@***.***>Subject: Re: [nvimdev/lspsaga.nvim] E5108: Error executing lua vim/_editor.lua:341: (Issue #1216)
it's packer issue . so use after event like BufReadPost .when you do edit conig file you need PackerCompile to make it take effect.
