### ISSUE TITLE
Error when using lspsaga with OmniSharp

### ISSUE THREAD

**Issue by LoneExile** [nvimdev/lspsaga.nvim#1220]
### Describe the bug

I'm currently using LSPSaga for my LSP needs in Neovim. However, I've encountered an issue when trying to use it with the [OmniSharp LSP](https://github.com/omnisharp/omnisharp-roslyn).

When I try to run `:Lspsaga peek_definition`, I get the following error:

![image](https://github.com/nvimdev/lspsaga.nvim/assets/82561297/1cc27cac-4c2f-42ee-b466-cd8397bb3e1d)
![image](https://github.com/nvimdev/lspsaga.nvim/assets/82561297/38cbd688-a0b0-4a36-8a0d-124ec75107e8)

The error seems to occur when the LSP client tries to jump to a definition in a `$metadata$` document. The file it's trying to jump to is `/$metadata$/Project/BuberBreakfast/Assembly/ErrorOr/Symbol/ErrorOr/ErrorOr`.

I found that the [OmniSharp Extended LSP](https://github.com/Hoffs/omnisharp-extended-lsp.nvim) plugin is designed to handle these `$metadata$` documents, so I tried to use it together with LSPSaga. However, it seems that LSPSaga is not working correctly with the OmniSharp Extended LSP plugin.

Interestingly, the `:lua vim.lsp.buf.definition()` command works fine. with OmniSharp Extended LSP.

### Steps to reproduce

Here's how I set up the OmniSharp LSP:

```lua
local config = {
  handlers = {
    ["textDocument/definition"] = require('omnisharp_extended').handler,
  }
}
require'lspconfig'.omnisharp.setup(config)
```

https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#omnisharp

https://github.com/Hoffs/omnisharp-extended-lsp.nvim

### Expected behavior

by running `:Lspsaga peek_definition` should show peek_definition

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2066+gf56c18480

### lspsaga commit

latest

### Terminal name/version

wezterm 20230501-084619-d0e9a034

**Comment by LoneExile** [comment]
Despite the recent fix you've implemented, the issue still persists. 

Currently, I need to run `:lua vim.lsp.buf.definition()` before executing `:Lspsaga peek_definition` for it to work properly. If I run `:Lspsaga peek_definition` first, it breaks in the same way as before.

**Comment by glepnir** [comment]
need a clean reproduce step with some example csharp code.

**Comment by LoneExile** [comment]
Here is how I create a new .net project

![image](https://github.com/nvimdev/lspsaga.nvim/assets/82561297/a4531831-4b2d-4291-bc3b-5a4c29f3c419)

```bash
dotnet new webapi -o demo-project
```

Setup [Omnisharp LSP](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#omnisharp) with [omnisharp-extended](https://github.com/Hoffs/omnisharp-extended-lsp.nvim)

```lua
local omnisharp_path = vim.fn.glob(vim.fn.stdpath('data') .. '/mason/') .. 'packages/omnisharp/libexec/OmniSharp.dll'

local config = {
  cmd = { 'dotnet', omnisharp_path },
  handlers = {
    ["textDocument/definition"] = require('omnisharp_extended').handler,
  }
}
require'lspconfig'.omnisharp.setup(config)
```

result `demo-project/Controllers/WeatherForecastController.cs`

![image](https://github.com/nvimdev/lspsaga.nvim/assets/82561297/7566c5a7-3475-4d5e-bdb0-f231150a8fa6)
![image](https://github.com/nvimdev/lspsaga.nvim/assets/82561297/7838bc22-9a81-4e4c-bcef-bfc4c559822a)

**Comment by glepnir** [comment]
this is server special . need send `o#/v2/gotodefinition'` method to server to get new result . see 
https://github.com/Hoffs/omnisharp-extended-lsp.nvim/blob/main/lua/omnisharp_extended.lua#L198C48-L198C69

if no this plugin intergration default and lspsaga both through error. you  set this so it works

```lua
 handlers = {
    ["textDocument/definition"] = require('omnisharp_extended').handler,
  }
```
what i am thinking does  omnisharp extended can provide a function then i can use it  ?

**Comment by LoneExile** [comment]
Thank you for your response, Glepnir. I understand your point about the need for the `omnisharp extended` plugin integration. 

To clarify, when I use the **omnisharp extended** plugin with the default command `:lua vim.lsp.buf.definition()`, it successfully jumps to the definition. After this, if I call `:Lspsaga peek_definition`, it works as expected. However, if I call `:Lspsaga peek_definition` before the default command `:lua vim.lsp.buf.definition()`, it does not work.

I'm wondering if there's a way to ensure that `:Lspsaga peek_definition` can work independently, without having to call `:lua vim.lsp.buf.definition()` first?

Here's an illustration of the issue when the default command is called first, followed by `:Lspsaga peek_definition`, which works as expected:

![image](https://github.com/nvimdev/lspsaga.nvim/assets/82561297/cc15c8a4-398b-4112-8704-afd862daad1d)

**Comment by glepnir** [comment]
because when you call first that plugin override the default handler

https://github.com/Hoffs/omnisharp-extended-lsp.nvim/blob/53edfb413a54c9e55dcddc9e9fa4977a897e4425/lua/omnisharp_extended.lua#L207

**Comment by glepnir** [comment]
if omnisharp_extend can provide a interface function i can do a integration . if not there need handle by ourself..

**Comment by LoneExile** [comment]
Thanks, Glepnir. I'll see what I can do and will get back to you.
