### ISSUE TITLE
https://dev.neovim.pro is not available

### ISSUE THREAD

**Issue by anopheles** [nvimdev/lspsaga.nvim#1221]
I would really like to read the lspsaga docs.

**Comment by glepnir** [comment]
Currently I don't have money to renew. You can use nvimdev.github.io to visit

**Comment by anopheles** [comment]
nvimdev.github.io redirects me to https://dev.neovim.pro

**Comment by eddyekofo94** [comment]
The docs are still not available, can't reach the site

**Comment by ivo-toby** [comment]
I donated a couple of bucks so you can renew.  Or buy a coffee

**Comment by glepnir** [comment]
thanks! @ivo-toby
