### ISSUE TITLE
Lspsaga goto_definition jump back issue.

### ISSUE THREAD

**Issue by AGou-ops** [nvimdev/lspsaga.nvim#1223]
### Describe the bug

Lspsaga goto_definition:

https://github.com/nvimdev/lspsaga.nvim/assets/57939102/761609a9-418e-4b68-a717-590d99150d20

via API:

https://github.com/nvimdev/lspsaga.nvim/assets/57939102/2fa8006c-36fc-4ee6-80d3-aa7d85dad6a3

### Steps to reproduce

1. gd
2. \<C-o\>

### Expected behavior

Jumping correctly in the same file.

### Neovim version (nvim -v)

❯ nvim -V1 -v NVIM v0.10.0-dev Build type: Release LuaJIT 2.1.0-beta3     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/local/share/nvim"  Run :checkhealth for more info

### lspsaga commit

ae6ad955

### Terminal name/version

iTerm2

**Comment by AGou-ops** [comment]
@glepnir 

`Lspsaga goto_definition` error below:

![image](https://github.com/nvimdev/lspsaga.nvim/assets/57939102/c4604b0f-c9ff-40ac-87ce-49062cfefae0)

**Comment by glepnir** [comment]
fixed.
