### ISSUE TITLE
Lspsaga outline got an error in python.

### ISSUE THREAD

**Issue by nkta3m** [nvimdev/lspsaga.nvim#1224]
### Describe the bug

![2023-08-03 10_11_44-](https://github.com/nvimdev/lspsaga.nvim/assets/13484700/977af66d-b8f4-4ad2-bf5a-afdc48606178)

### Steps to reproduce

    1. open python file
    2. lspsaga outline
   

### Expected behavior

correct display outline

### Neovim version (nvim -v)

nvim 0.9.1

### lspsaga commit

d22f7039f014a361605631543dd09df4581b4089

### Terminal name/version

alacritty

**Comment by glepnir** [comment]
can't reproduce .which server you used  ? 

![image](https://github.com/nvimdev/lspsaga.nvim/assets/41671631/3ab74be4-ebad-413f-ae83-0537d3b01032)

**Comment by nkta3m** [comment]
pylsp
