### ISSUE TITLE
Docs website down

### ISSUE THREAD

**Issue by ivo-toby** [nvimdev/lspsaga.nvim#1225]
### Describe the bug

I can't access the docs: dev.neovim.pro/lspsaga/  is down 

### Steps to reproduce

Go to https://dev.neovim.pro/lspsaga/ 

### Expected behavior

Be able to view the website :) 

### Neovim version (nvim -v)

NVIM v0.9.1

### lspsaga commit

not relevant

### Terminal name/version

Not relevant

**Comment by glepnir** [comment]
duplicate #1221   use `nvimdev.github.io`
