### ISSUE TITLE
如何在finder结果中排除node_modules

### ISSUE THREAD

**Issue by Jinl-k** [nvimdev/lspsaga.nvim#1227]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
如何在finder结果中排除node_modules
<img width="973" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/39037760/420876f4-8969-408b-bded-8f13196d874c">

**Describe alternatives you've considered**

**Additional context**

**Comment by glepnir** [comment]
```lua
finder = {
         filter = {
              ['textDocument/references'] = function(results)
                    --do filter 
               end

```
