### ISSUE TITLE
Selective preview of Read/Write references

### ISSUE THREAD

**Issue by kair8m** [nvimdev/lspsaga.nvim#1228]
**Problem:**
The LspSaga plugin for Neovim lacks the ability to selectively preview only read/write references for a selected symbol using `Lspsaga finder`. Such functionality would make code navigation and comprehension challenging for large projects.

**Solution:**
Add a feature to the LspSaga plugin that allows users to filter the LSP finder results to show only read/write references for the selected symbol. This will improve code navigation and make it easier to identify relevant parts of the codebase.

**Alternative:**
Manually using regular text search tools within Neovim or external tools to find specific read/write references, but this can be time-consuming and error-prone.

**Additional context:**
Ensure seamless integration with the existing LspSaga plugin, configurable options, and support for different programming languages and LSP servers.

**Comment by glepnir** [comment]
there support filter results.  and I think finder can works fine on a big project. I do some optimize on finder to make it works fine on big project.

```lua

finder = {
         filter = {
         ['textDocument/references'] = function(results)
         end

```
