### ISSUE TITLE
Lspsaga finder (ref & implementation) --> Empty Window

### ISSUE THREAD

**Issue by MrWelsch** [nvimdev/lspsaga.nvim#1229]
### Describe the bug

When I try to use the finder function like this:

`:Lspsaga finder`

I get an empty Floating Window as shown in the image below (Left side).

<img width="960" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/45096895/9e534752-b9c6-45c0-9515-15b1e3a74eaf">

Any idea why that is?

### Steps to reproduce

Link to my config:

https://github.com/MrWelsch/nvim

Plugin is configured in: /lua/lsp/lspsaga.lua

Keybind to call the finder function: /lua/general/mappings.lua

### Expected behavior

Showing me references or implementations inside the floating window when the keybind is pressed or the command is entered.

### Neovim version (nvim -v)

0.9.1

### lspsaga commit

2fea9e5

### Terminal name/version

kitty / 0.29.1

**Comment by glepnir** [comment]
`:message` does there has finder print ? i can't reproduce it works fine always ..

![image](https://github.com/nvimdev/lspsaga.nvim/assets/41671631/283c0cd0-4af6-437e-9f0d-17e782f79149)

**Comment by MrWelsch** [comment]
This is a screenshot when using :message.

<img width="1556" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/45096895/b8d64d50-c197-48fb-94e1-6b3aa95886d5">


I also tried it on another file, specifically the /lua/lsp/handlers. 
Line 74: lsp_highlight_document(client)

Expected behavior: As shown in the image below: `:NiceReference` (Another Plugin which i wanted to replace with Lspsaga)

<img width="964" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/45096895/a633863e-149d-41cd-9dae-9b72a6055c9e">


Definition works as expected:

<img width="1564" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/45096895/fadb53ef-3dd1-4a6b-8cc5-863b4942d80c">

Everything else works as well. e.g. Code Actions:

<img width="1259" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/45096895/aa3c8d23-b774-43f0-919c-e805a5f247c7">

**Comment by glepnir** [comment]
could you try the min config like  `nvim --clean -u min.lua`

```lua
vim.opt.rtp:append '~/workspace/nvim-lspconfig'
local lspconfig = require 'lspconfig'
lspconfig.lua_ls.setup {}
vim.opt.rtp:append '~/workspace/lspsaga.nvim'
require('lspsaga').setup {}
vim.keymap.set('n',  'gh', '<cmd>Lspsaga finder<CR>')
```

**Comment by MrWelsch** [comment]
Thank you for your time. 
Doesn't seem to work for me or something intereferes.
Sadly I do not have the time doe fiddle with it, especially since the alternative works seemlessly.
