### ISSUE TITLE
Default key mappings in definition window don't work

### ISSUE THREAD

**Issue by mikehaertl** [nvimdev/lspsaga.nvim#1230]
### Describe the bug

The default mappings that start with `<C-c>` don't work for me. E.g. when I press `<C-c>i` I'm in INSERT mode.

The only key that works is `q`.

I also tried to use a different prefix like `split = '<C-a>v'` but it doesn't work either.

It works, if I define it with a single key only like `split = '<C-a>'`

### Steps to reproduce

1. open definition with `:Lspsaga peek_definition`
2. Press `<C-c>i`

### Expected behavior

It should open a split windows with the definition.

### Neovim version (nvim -v)

0.10.0-dev-753+g4a06de40e

### lspsaga commit

535d28a

### Terminal name/version

Gnome Terminal 3.44.0

**Comment by glepnir** [comment]
the keymap just normal mode .

**Comment by mikehaertl** [comment]
The output of `:nmap` when the definition window is opened:
```
n  q           *@<Lua 312: ~/.local/share/nvim/plugged/lspsaga.nvim/lua/lspsaga/definition.lua:69>
n  <C-C>o      *@<Lua 297: ~/.local/share/nvim/plugged/lspsaga.nvim/lua/lspsaga/definition.lua:69>
n  <C-C>k      *@<Lua 291: ~/.local/share/nvim/plugged/lspsaga.nvim/lua/lspsaga/definition.lua:91>
n  <C-C>i      *@<Lua 281: ~/.local/share/nvim/plugged/lspsaga.nvim/lua/lspsaga/definition.lua:69>
n  <C-C>v      *@<Lua 310: ~/.local/share/nvim/plugged/lspsaga.nvim/lua/lspsaga/definition.lua:69>
n  <C-C>t      *@<Lua 311: ~/.local/share/nvim/plugged/lspsaga.nvim/lua/lspsaga/definition.lua:69>
```

**Comment by mikehaertl** [comment]
> the keymap just normal mode .

But I am in normal mode.

**Comment by mikehaertl** [comment]
Hmm, weird. As a workaround I've now defined single key maps (I don't edit in the definition window):

```
  definition = {
    keys = {
      edit = '<C-e>',
      vsplit = '<C-v>',
      split = '<C-x>',
      quit = 'q',
    }
  },
```

I can live with that. But if you want me to debug something let me know.

The mappings have never worked for me (also not in the older releases).

**Comment by glepnir** [comment]
which language ?

**Comment by mikehaertl** [comment]
Aah: I was typing to slow. It works if I type fast. Is this controlled by `timeoutlen` (which I have set to 200)?

Most other key sequences don't have a timeout (like `gd`), so I didn't expect it here.

**Comment by glepnir** [comment]
yup the value too small maybe try 500 ?
