### ISSUE TITLE
How to use default key map?

### ISSUE THREAD

**Issue by LovesAsuna** [nvimdev/lspsaga.nvim#1233]
Since the project migrated to nvimdev, the configuration removed the recommended keymap, and I tried to delete the original recommended keymap, but found that the current default keymap wouldn't work at all

**Comment by glepnir** [comment]
what keymap and how you config it ?

**Comment by LovesAsuna** [comment]
> what keymap and how you config it ?

nothing, I just follow the guide and install the new version of plugin, removing all of the old key map from the old readme. I think the default key map defined in plugin should work.

**Comment by glepnir** [comment]
which keymap you had tried  and what command you used ?

**Comment by LovesAsuna** [comment]
<img width="511" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/32810896/bea720b6-1cf0-461c-832d-d73c7b32f0be">
For example, finder has this default keymap, which I has no idea how to use it at all

**Comment by glepnir** [comment]
`:Lsp finder` then use these keymap on finder left window. `shuttle` works on left and right window.

**Comment by LovesAsuna** [comment]
原来这个keymap不是对应命令的快捷键，只是对于功能窗口下的子功能快捷键。那怎么主页把推荐的命令keymap移除了

**Comment by LovesAsuna** [comment]
对的，现在直接无了

**Comment by glepnir** [comment]
示例配置。可能忘记写了。 空了再写一遍
