### ISSUE TITLE
Different border styles are used for diagnostics than for other functions

### ISSUE THREAD

**Issue by fent** [nvimdev/lspsaga.nvim#1234]
### Describe the bug

When I navigate to a diagnostic, by running `:Lspsaga diagnostic_jump_next` I get the following red border

![image](https://github.com/nvimdev/lspsaga.nvim/assets/933490/499ae9c0-7bc8-4bbe-83ef-3f789228b636)

when I use one of the other Lspsaga functions, like `:Lspsaga finder_doc` or `:Lspsaga peek_definition`, I get a differently styled border

![image](https://github.com/nvimdev/lspsaga.nvim/assets/933490/d296d80c-faab-4dce-91d9-2240db862245)

this is on the `habamax` colorscheme that comes with nvim, but other colorschemes have similar borders. imo the borders used in diganostics look much better, and could be used for other functions too. but if you disagree, how can I change the border used on those functions to the one used for diagnostics?

### Steps to reproduce

1. This is on a fresh lspsaga.nvim install with default options and with the `habamax` colorscheme
2. open a file with lsp set up
3. edit the file to have the lsp generate a warning or error
4. Use `:Lspsaga diagnostic_jump_next` to jump the warning/error and see the float
5. Use `:Lspsaga finder_doc` to see another type of float
6. compare float borders

### Expected behavior

Border styles should be consistent across all the floating windows. the diagnostic borders have different colors to denote error/warn/hint. but even so, a default-colored border could be in the same style.

### Neovim version (nvim -v)

0.9.0

### lspsaga commit

5877e95

### Terminal name/version

Alacritty 0.11.0

**Comment by glepnir** [comment]
```
diagnostic.border_follow = false
```

**Comment by fent** [comment]
that makes the border of the diagnostic look like the border from the other functions. how can i do the opposite? make the border of the other functions look like the one from diagnostics?

**Comment by glepnir** [comment]
the value of `ui.border` is what ? they should be same

**Comment by fent** [comment]
this is using default options, with no explicit `ui.border` set

**Comment by glepnir** [comment]
wired. it should be both use `single` border ..have you tried clean config for test.

**Comment by fent** [comment]
Here's a config file fore reproduction, I'm using lazy.nvim so the path is set to where it installs the plugins. and I'm using mason.nvim for lua_ls

```lua
local datapath = vim.fn.stdpath("data")
vim.opt.rtp:append(datapath .. '/lazy/lspsaga.nvim')
vim.opt.rtp:append(datapath .. '/lazy/nvim-lspconfig')
vim.opt.rtp:append(datapath .. '/lazy/mason.nvim')
vim.opt.rtp:append(datapath .. '/lazy/mason-lspconfig.nvim')
local lspconfig = require('lspconfig')
lspconfig.lua_ls.setup({})
require('lspsaga').setup({})
require("mason").setup()
require("mason-lspconfig").setup()
vim.keymap.set('n', '[d', '<cmd>Lspsaga diagnostic_jump_prev<CR>')
vim.keymap.set('n', ']d', '<cmd>Lspsaga diagnostic_jump_next<CR>')
vim.keymap.set('n', 'gd', '<cmd>Lspsaga peek_definition<CR>')
vim.cmd("colorscheme habamax")
```

**Comment by glepnir** [comment]
colorscheme problem i guess

**Comment by fent** [comment]
yep, it's the habamax color scheme, it has a default ugly float border. for anyone wondering, you can change it with

```lua
 vim.api.nvim_set_hl(0, "FloatBorder", { fg = "#c4e2ff", bg = "#282828" })
```
