### ISSUE TITLE
Diagnostic jump does not close preview 

### ISSUE THREAD

**Issue by Curs3W4ll** [nvimdev/lspsaga.nvim#1237]
### Describe the bug

When having multiple diagnostics on the same line, jumping through diagnostic will not make the floating window disappear.

See the following example.

https://github.com/nvimdev/lspsaga.nvim/assets/72013831/9fe14692-59ca-47ae-8a07-efb202dd3fb5

This does not seem to be effective anymore when one or more other lines have diagnostics too.

### Steps to reproduce

1. Open a file with multiple diagnostics on the same line (ensure having an lsp for the filetype), see lua example below
2. Try jumping between diagnostics using lspsaga
3. See floating windows are not closing automatically

```lua
Fu

print("yes")
``` 

### Expected behavior

Floating windows should close, even if the cursor is not moving while jumping between diags.

### Neovim version (nvim -v)

0.9.1

### lspsaga commit

e552e9d

### Terminal name/version

terminator 1.91

**Comment by Curs3W4ll** [comment]
Thanks, I'm shocked by your responsiveness

**Comment by Curs3W4ll** [comment]
@glepnir It seems that this fix introduced a new bug while jumping through diagnostics.

When jumping from one diagnostic to another, you will need to do it twice to trigger the UI.

See the following example

https://github.com/nvimdev/lspsaga.nvim/assets/72013831/60521aa7-99a2-4a97-82af-5a5baad2075c

**Comment by glepnir** [comment]
fixed
