### ISSUE TITLE
Does not support function hierarchy highlighting

### ISSUE THREAD

**Issue by Robin329** [nvimdev/lspsaga.nvim#1242]
**Is your feature request related to a problem? Please describe.**
Links to previous question discussions:
(https://github.com/ayamir/nvimdots/issues/948)

**Describe the solution you'd like**

**Describe alternatives you've considered**
If the cursor is on a certain function, the window cannot highlight the function, it is difficult to find where the function is located, and this window blocks the source code window of the calling function.

**Additional context**
I can't find where is this function located? It is very unfriendly to me, when I view a certain code. Is it possible to support this function to highlight at a certain position at the same time?
![image](https://github.com/nvimdev/lspsaga.nvim/assets/22770951/0d785dbd-0b1e-4770-b782-51bcd67ee6e4)

**Comment by Jint-lzxy** [comment]
This is mentioned in https://github.com/ayamir/nvimdots/issues/948#issuecomment-1675991407 - you probably need to [open a feature request upstream](https://github.com/nvimdev/lspsaga.nvim/issues/new?assignees=&labels=enhancement&projects=&template=feature_request.md&title=). Please do not open similar issues multiple times.
