### ISSUE TITLE
Finder get def+ref error

### ISSUE THREAD

**Issue by Gitfz810** [nvimdev/lspsaga.nvim#1245]
### Describe the bug

```lua
local status, saga = pcall(require, "lspsaga")
if not status then
  return
end

saga.setup({
  lightbulb = {
    sign = false,
  },
  beacon = {
    enable = false,
  },
  finder = {
    keys = {
      toggle_or_open = "<CR>",
      quit = "q",
      close = "<ESC>",
    },
  },
  rename = {
    in_select = false,
  },
})
```

Error:

<img width="1154" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/38970394/1252a09a-46fc-40bd-a961-7c3035d39721">

### Steps to reproduce

Just do `:Lspsaga finder def+ref`

### Expected behavior

Get def+ref in float window.

### Neovim version (nvim -v)

NVIM v0.9.1

### lspsaga commit

a761bcebbacc49562c4e37337f1f8cc85e4483f9

### Terminal name/version

Terminal

**Comment by glepnir** [comment]
how do you load plugin and where the `setup` function call ?

**Comment by Gitfz810** [comment]
> how do you load plugin and where the `setup` function call ? this error mean setup function not take effect so `config` is nil .

I load plugin with `packer` as follow;

```lua
local status, packer = pcall(require, "packer")
if not status then
  return
end

-- add list of plugins to install
return packer.startup({
  function(use)
    use("neovim/nvim-lspconfig") -- easily configure language servers

    use({
      "nvimdev/lspsaga.nvim", -- enhanced lsp uis
      after = "nvim-lspconfig",
    })
  end,
  config = {
    package_root = vim.fn.stdpath("config") .. "/site/pack/",
  },
})
```

and in another file write `lspsaga` configurations.
