### ISSUE TITLE
Sticky split

### ISSUE THREAD

**Issue by fecet** [nvimdev/lspsaga.nvim#1248]
**Is your feature request related to a problem? Please describe.**
When I'm using my IDE or text editor and try to navigate to a definition, the system opens a new window in vsplit every time. This results in multiple redundant windows, cluttering my interface and reducing work efficiency.

**Describe the solution you'd like**
When I'm using my IDE or text editor and try to navigate to a definition, the system opens a new window in vsplit every time. This results in multiple redundant windows, cluttering my interface and reducing work efficiency.

**Describe alternatives you've considered**
I've thought about manually closing the redundant windows, but this approach is neither practical nor efficient. I also tried searching for existing plugins or tools that might satisfy this need but haven't found an appropriate solution.

**Additional context**
Such a feature would be very useful for developers who frequently need to navigate and view code definitions. Currently, the surplus of redundant windows creates a cluttered interface, but smart window management could greatly enhance a developer's efficiency.

**Comment by glepnir** [comment]
```lua
finder.sp_inexist = true,
```

**Comment by glepnir** [comment]
nope. but you can set finder show def on setup or command.
