### ISSUE TITLE
lua error when opening the outline: 'replacement string' item contains newlines

### ISSUE THREAD

**Issue by fent** [nvimdev/lspsaga.nvim#1251]
### Describe the bug

i'm getting the following error when displaying the outline using `:Lspsaga outline`

```
Error executing Lua callback: ...demo/plugins/lspsaga.nvim/lua/lspsaga/symbol/outline.lua:100: 'replacement string' item contains newlines
stack traceback:
        [C]: in function 'buf_set_lines'
        ...demo/plugins/lspsaga.nvim/lua/lspsaga/symbol/outline.lua:100: in function 'recursive_parse'
        ...demo/plugins/lspsaga.nvim/lua/lspsaga/symbol/outline.lua:171: in function 'recursive_parse'
        ...demo/plugins/lspsaga.nvim/lua/lspsaga/symbol/outline.lua:178: in function 'parse'
        ...demo/plugins/lspsaga.nvim/lua/lspsaga/symbol/outline.lua:553: in function 'outline'
        ...og-demo/plugins/lspsaga.nvim/lua/lspsaga/symbol/init.lua:229: in function 'outline'
```

the outline buffer still works. and if i close and re-open it, i get the error again. however, it's only on some files, i'm trying to find a pattern but hoping that the error is enough to know the cause

### Steps to reproduce

1. open a file and wait for the lsp server to attach
2. run `:Lspsaga outline`
3. get the error above

### Expected behavior

to not get an error

### Neovim version (nvim -v)

0.9.0

### lspsaga commit

a761bce

### Terminal name/version

Alacritty 0.11.0

**Comment by glepnir** [comment]
which server ? it return node name with `\n`
