### ISSUE TITLE
winbar api is not available

### ISSUE THREAD

**Issue by Gamonsi** [nvimdev/lspsaga.nvim#1252]
### Describe the bug

winbar api  `require("lspsaga.symbol.winbar").get_bar()`  is not available, got nil

### Steps to reproduce

1. open a go file and wait for lsp attach
2. input the command in cmd 
```lua
lua require("lspsaga.symbol.winbar).get_bar()
```

### Expected behavior

Get the winbar content( format symbol string ) described on the nvimdev website

### Neovim version (nvim -v)

NVIM v0.10.0-dev-800+g3d948a4dc

### lspsaga commit

93a2ae4c03d1f1c

### Terminal name/version

kitty 0.29.1

**Comment by glepnir** [comment]
hmm I can't reproduce 

![image](https://github.com/nvimdev/lspsaga.nvim/assets/41671631/5f54c267-95a6-4199-ae49-f3ca1cc475eb)

**Comment by Gamonsi** [comment]
I did a quick test and found something wrong here.
![133eae70bad8bb88dceac8e67ba710a1](https://github.com/nvimdev/lspsaga.nvim/assets/142766785/7e19b916-e549-48d2-a997-b32de798914d)
I got nil, so nothing is returned.

**Comment by Gamonsi** [comment]
Well, it should be my problem, I didn't use it correctly, the problem has been solved. Thank you for your help

**Comment by glepnir** [comment]
nil mean the symbols not cached. maybe you run this api too early

**Comment by Gamonsi** [comment]
> nil mean the symbols not cached. maybe you run this api too early , there also have `User SagaSymbolUpdate` event

I see, thanks for your reply. ![2T5E)$9{R _)R31DF0Y7OA3](https://github.com/nvimdev/lspsaga.nvim/assets/142766785/6b4974e1-5184-464b-828a-0b008e9ed3dc)
