### ISSUE TITLE
hover_doc fail to work on docker or wsl.

### ISSUE THREAD

**Issue by MKrbm** [nvimdev/lspsaga.nvim#1254]
### Describe the bug

When I try to invoke Lspsaga hover_doc, it returns errors.

![](https://user-images.githubusercontent.com/57752203/262036625-69e817e0-1cc2-42cd-a89c-ab5b1afc8006.png)

I found this can be fixed by changing
`  util.close_win(require('diagnostic').winid)` to `  util.close_win(require('lspsaga.diagnostic').winid)`.  at line 326 of `lua/hover.lua`. 

### Steps to reproduce

1. Call Lspsaga hover_doc on docker_desktop ( windows11) or wsl2. Both are ubuntu20.04

### Expected behavior

None

### Neovim version (nvim -v)

v0.9.1

### lspsaga commit

7106caa

### Terminal name/version

bash

**Comment by glepnir** [comment]
your version is old. please try update/

**Comment by MKrbm** [comment]
Thank you Kaguya-sama!
