### ISSUE TITLE
Calling peek_definition on tsserver shows textDocument/definition warning

### ISSUE THREAD

**Issue by andres-g-r** [nvimdev/lspsaga.nvim#1256]
### Describe the bug

When calling `peek_definition` on a `tsserver` file we get a warning `response of request method textDocument/definition is empty`

But the definition floating window opens and works as intended.

![Screen Shot 2023-08-22 at 10 29 55 a m](https://github.com/nvimdev/lspsaga.nvim/assets/135061924/408a0e6a-56c8-4f83-8322-a21d06036251)

### Steps to reproduce

1. `:Lspsaga peek_definition`
2. Opens definition floating window
3. Definition works as intended
4. Shows warning `[lspsaga] response of request method textDocument/definition is empty`

### Expected behavior

Should not show any warnings

### Neovim version (nvim -v)

0.9.2-dev-85+g46fc9d547

### lspsaga commit

3186d5a

### Terminal name/version

iTerm2 3.4.20

**Comment by glepnir** [comment]
you have one more server on this buffer right ?
