### ISSUE TITLE
Lspsage finder 

### ISSUE THREAD

**Issue by elauriault** [nvimdev/lspsaga.nvim#1258]
### Describe the bug

When doing]
```:Lspsaga finder```

I get the following message

```
[Lspsaga] finder no any results to show
```

### Steps to reproduce

:Lspsaga finder

### Expected behavior

The finder would be launched

### Neovim version (nvim -v)

NVIM v0.10.0-dev

### lspsaga commit

7106caa5

### Terminal name/version

alacrtty

**Comment by glepnir** [comment]
that's mean no lsp method result

**Comment by elauriault** [comment]
This worked fine under nvim 0.9.x.
