### ISSUE TITLE
show relative paths in float window buffer file path

### ISSUE THREAD

**Issue by fent** [nvimdev/lspsaga.nvim#1260]
**Is your feature request related to a problem? Please describe.**
When using functions that show a popup with filenames (peek_definition, peek_type_definition, finder), the window can display a file path that includes additional folders. example, in these windows, my `:pwd` is `~/dotfiles`

`Lspsaga peek_definition`
![image](https://github.com/nvimdev/lspsaga.nvim/assets/933490/1337eb10-97ff-4576-95b8-0cf5a07b0b1e)

`Lspsaga finder`
![image](https://github.com/nvimdev/lspsaga.nvim/assets/933490/614413e5-57d1-4c82-a58e-c901fd613698)

**Describe the solution you'd like**
Show relative paths, for above, it would mean removing `dotfiles/`. it could be an option too, like `show_relative_paths`

**Describe alternatives you've considered**
A `path_display` option that can be a function for further customization, kind of like what telescope.nvim has
```lua
 path_display = function(_, path)
  local tail = require("telescope.utils").path_tail(path)
  return string.format("%s (%s)", tail, path)
end
```
but i'm not sure that's necessary

**Comment by glepnir** [comment]
what's the root dir of lsp ?

**Comment by fent** [comment]
ah i see, you can specify the lsp root with the following
```lua
lspconfig.lua_ls.setup({
  root_dir = lspconfig.util.root_pattern('.git'),
})
```
but, in my case i work in an environment where the definitions/types/references can fall outside of the root_dir, so i could still use a way to format the path

**Comment by fent** [comment]
the 2nd check in the above commit isn't working for me, might be because my path contains characters used in lua patterns, which `string.find` tries to match. but the following works

```lua
  elseif fname:sub(1, #pwd) == pwd then
```

could there also still be a `path_display` option? i'd like to truncate a few common folders in my repo, or use icons for them

**Comment by glepnir** [comment]
try override the default function .
```lua
require('lspsaga.util').path_sub = function(fname, root)
-- your logic
end
```

**Comment by fent** [comment]
will do. however, the above change is still needed to properly detect pwd

**Comment by glepnir** [comment]
update changed.
