### ISSUE TITLE
outline floating not fully preview

### ISSUE THREAD

**Issue by shendypratamaa** [nvimdev/lspsaga.nvim#1264]
### Describe the bug

<img width="1382" alt="Screenshot 2023-08-27 at 15 49 54" src="https://github.com/nvimdev/lspsaga.nvim/assets/76093597/465e151c-f7b1-4e09-bdad-a78e17caa99f">

preview not fully seen

### Steps to reproduce

```
require('lspsaga').setup({
  symbol_in_winbar = {
    enable = true
  },
  outline = {
    layout = 'float',
  }
})
```

1. open a file and wait for the lsp server to attach    
2. run :Lspsaga outline
3. and preview not fully showing on preview win

### Expected behavior

preview outline should fully seen

### Neovim version (nvim -v)

0.9.1

### lspsaga commit

76f9464

### Terminal name/version

alacritty 0.12.2

**Comment by glepnir** [comment]
preview code just get from range not full file
