### ISSUE TITLE
`ctrl-o` functionality appears to break after using `peek_definition`

### ISSUE THREAD

**Issue by Sammyalhashe** [nvimdev/lspsaga.nvim#1265]
### Describe the bug

I love the `peek_definition` feature. It let's me quickly glance (fully) at a function definition to check exactly what I need and provides a solid reference of what a function will actually do. However, one thing I have noticed is that after using it, neovim's `ctrl-o` functionality (jump back to previous location) breaks and `ctrl-o` doesn't actually go anywhere.

Has anyone else experienced this sort of issue or is this just me? If this can't be repro'd feel free to close this issue.

### Steps to reproduce

- do some actions to establish a jump list
- `:Lspsaga peek_definition<CR>` (specifically in a c++ file if you want to emulate my situation perfectly).
- press `q` to exit this window
- `ctrl-o` to go back in your previously established jump list
- notice it doesn't go anywhere

### Expected behavior

I expect the previously established jump list to be preserved.

### Neovim version (nvim -v)

0.9.0

### lspsaga commit

HEAD

### Terminal name/version

screen-256color

**Comment by fecet** [comment]
I guess the design is to use `<C-t>` but it would be great if I can still use `<c-o>`

**Comment by Sammyalhashe** [comment]
I have honestly never used ctrl-t, looking it up in the help pages it's seems to be dependent on ctags which I don't use. Personally, I think ctrl-o has much wider use
