### ISSUE TITLE
Do not check for code actions if LS does not have that capability

### ISSUE THREAD

**Issue by carrascomj** [nvimdev/lspsaga.nvim#1267]
### Describe the bug

When I jump to next diagnostic, there is a delay where an error message is produced because the particular language server does not support code actions.

![image](https://github.com/nvimdev/lspsaga.nvim/assets/46683255/5e8b8a0f-643a-471c-a5a0-194f4455d409)

### Steps to reproduce

You need a language server which does _not_ support code actions. I am using an inhouse one, sorry for the lack of repro.

### Expected behavior

I would expect that lspsaga checks for server capabilities before trying to get the available code actions when jumping to a diagnostic. If `codeActionProvider` is not supported, no error should be displayed (especially the delayed should not occur).

### Neovim version (nvim -v)

NVIM v0.9.1

### lspsaga commit

76f9464

### Terminal name/version

kitty/0.29.2

**Comment by glepnir** [comment]
I remember I fixed this...

**Comment by carrascomj** [comment]
Thad definitely solved it, thanks!
