### ISSUE TITLE
Is it possible to temporarily remove the line (can we call it winbar?) at the top that shows class names, function names, etc.?

### ISSUE THREAD

**Issue by arafune** [nvimdev/lspsaga.nvim#1268]
Is it possible to temporarily remove the line (can we call it winbar?) at the top that shows class names, function names, etc.?

As shown in the attachment (see SS-1.png), after installing lspsaga, class names, function names, etc. are displayed. Normally this feature is very convenient, but there are times when I want to turn it off temporarily. For example, when using GitBlame or GitDiff with "dinhhuy258 / git.nvim",  the line is shifted by one (see SS-2.png).

Can you prepare a suitable function ? (Or has it already been prepared?, if so please let me know the way.)

<img width="1134" alt="SS-1" src="https://github.com/nvimdev/lspsaga.nvim/assets/6754804/57d32f68-a2ff-4bb2-8e7f-b116af6c1f81">

<img width="1132" alt="SS-2" src="https://github.com/nvimdev/lspsaga.nvim/assets/6754804/ad381280-82dd-4d7e-b3e0-ce57e78a9ff2">

**Comment by glepnir** [comment]
```lua
symbol_in_winbar = {
      ignore_patterns = string or table when filename find it winbar not show on this buffer

````
