### ISSUE TITLE
Getting error: attempt to call field 'get_clients'

### ISSUE THREAD

**Issue by vyorkin** [nvimdev/lspsaga.nvim#1271]
### Describe the bug

Getting this error when I try to call any of the Lspsaga functions (e.g. `hover_doc`)

<img width="1280" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/988849/3c1a7dad-c9fe-409d-83e3-dea6687d2105">

Here is my neovim config: https://github.com/vyorkin/nvim

### Steps to reproduce

clone my vim config, checkout d085a4b742542f8ae19b65fa093d857d9327bf66, run `:Lspsaga hover_doc`
<img width="305" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/988849/8a538a11-573c-48bc-aa2c-556a338334f6">

### Expected behavior

No error

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1780+g68e2d7229-Homebrew Build type: Release LuaJIT 2.1.0-beta3     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-68e2d72/share/nvim"

### lspsaga commit

main branch

### Terminal name/version

kitty, latest

**Comment by vyorkin** [comment]
After updating to the recommended installation settings I got a different error:
<img width="1261" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/988849/a92b609c-3393-444b-8108-cdd979530c9e">

**Comment by glepnir** [comment]
your neovim version is too old. please update . because you use head version.

**Comment by vyorkin** [comment]
Thank you! Which version of NeoVim is currently recommended for users of `lspsaga`? 
I can see that the latest is v0.9.1
<img width="282" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/988849/fd921e1e-6f26-4b92-bc64-6756ee2218b1">

**Comment by glepnir** [comment]
0.10 mean head version that need build the source code . if are running in mac you can try `brew install neovim --head` if you are in arch `yay -S neovim-nightly-bin`

**Comment by Spuxy** [comment]
@glepnir brew mainteners said, that they wont support nighlty builds
