### ISSUE TITLE
Broken URLs in hover window due to special symbols

### ISSUE THREAD

**Issue by rensftw** [nvimdev/lspsaga.nvim#1272]
### Describe the bug

Lspsaga prints the `\` character which breaks URLs and reduces readability.
I'm guessing this has to do with escaping special characters.

Here's an example with Lspsaga hover:
<img width="885" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/22574186/54a59415-0817-43d8-8dac-0413da086181">

Example with native hover:
<img width="893" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/22574186/da276bd0-31d6-418f-8d91-bc0618199056">

### Steps to reproduce

Hover over any symbol that has special characters (eg a URL) in the description.
In my examples above I am using `jsonls` and [b0o/SchemaStore.nvim](https://github.com/b0o/SchemaStore.nvim) and then hovering over [this schema](https://github.com/SchemaStore/schemastore/blob/master/.pre-commit-config.yaml)

However I am noticing now that lspsaga does not print URLs at all in other LSPs (eg lua LSP) 🤔 
<img width="1011" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/22574186/73bb2908-4b69-4392-82ef-b3862475f591">

I need to spend more time on specific steps to reproduce

### Expected behavior

URLs are not broken, and `\` does not get printed in front of special characters.

### Neovim version (nvim -v)

v0.9.1

### lspsaga commit

5073eda

### Terminal name/version

alacritty

### Related
https://github.com/b0o/SchemaStore.nvim/issues/21

**Comment by glepnir** [comment]
> However I am noticing now that lspsaga does not print URLs at all in other LSPs (eg lua LSP)

this is feature. it just like markdown render. and you can jump to url by press `gx` on `view xxxx` position
