### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by anhtung6950** [nvimdev/lspsaga.nvim#1276]
### Describe the bug

![image](https://github.com/nvimdev/lspsaga.nvim/assets/46744862/fc731fff-6d9c-4f6b-8e49-20450c416b80)
When I want to use `:Lspsaga hover_doc` that make me some notice like this, I found out that the commit `497baad42931c29b781ba0f0779423ba1693e81b` is the reason of this.

### Steps to reproduce

run command `:Lspsaga hover_doc`

### Expected behavior

some fix for this

### Neovim version (nvim -v)

v0.10.0-dev-530+g8376e8700

### lspsaga commit

497baad42931c29b781ba0f0779423ba1693e81b

### Terminal name/version

Version 3.44.0 for GNOME 42

**Comment by glepnir** [comment]
update your neovim version
