### ISSUE TITLE
hover_doc with lualine and cmdheight 0

### ISSUE THREAD

**Issue by pauchiner** [nvimdev/lspsaga.nvim#1277]
### Describe the bug

I have lualine as my current status line and I set cmdheight to 0 to have a more compact experience, but when I run the command `:Lspsaga hover_doc` (from a keymap) the status line has strange behavior:

https://github.com/nvimdev/lspsaga.nvim/assets/49660697/d7f4e153-9642-40a2-aab4-b63564fcb980
When I press on a property or something, the statusline flashes for a moment, and if i run the command on any partin which nothing should happen, it disappears. 
> If I set the cmdheight to 1, it works perfectly.

### Steps to reproduce

1. Run `lualine` with no config
``` lua
require('lualine').setup {}
```
2. Run `lspsaga` with no config
``` lua
require('lspsaga').setup {}
```
3. Bind the hover doc to a keymap
``` lua
vim.keymap.set("n", "K",  "<Cmd>Lspsaga hover_doc<CR>", {noremap = true, silent = true})
```
4. Set the cmdheight to 0
``` lua
vim.opt.cmdheight = 0
```

### Expected behavior

https://github.com/nvimdev/lspsaga.nvim/assets/49660697/5ac95160-395a-4603-9ed2-74844a48759b
When I press the command doesn't makes any flashes or disappearances.

### Neovim version (nvim -v)

v0.9.1

### lspsaga commit

afc72318cb69be3982a3220cc2a9fee3a628f778

### Terminal name/version

iTerm2 3.4.20

**Comment by pauchiner** [comment]
Stills flashing when i run the `hover_doc` command and the `cmdheight = 0`, but it's much less annoying than seeing it disappear.

Thanks 🤗

**Comment by glepnir** [comment]
update

**Comment by pauchiner** [comment]
i already update and stills happening:
https://github.com/nvimdev/lspsaga.nvim/assets/49660697/05355411-535c-41c2-a296-1afc80cad103

![Current Version](https://github.com/nvimdev/lspsaga.nvim/assets/49660697/b683d7e2-506e-429a-9e94-f9cb83b8c688)

**Comment by glepnir** [comment]
then it's neovim issue I remember there has some cmdheight bug. try `vim.lsp.buf.hover` if same then not relate lspsaga

**Comment by pauchiner** [comment]
``` lua
vim.keymap.set("n", "K",  vim.lsp.buf.hover, {noremap = true, silent = true})
```
This is the result:

https://github.com/nvimdev/lspsaga.nvim/assets/49660697/df2bce28-f5d5-4fc6-8d92-4b200ba2d070

It doesn't seem to be a neovim issue.

**Comment by glepnir** [comment]
because `<Cmd>` it's like `:` to command line. 

```lua
vim.keymap.set('n', 'K', function() require('lspsaga.hover'):render_hover_doc() end)
```

**Comment by pauchiner** [comment]
@glepnir You're right, that was the problem.

Thank you, now works perfectly. 😄
