### ISSUE TITLE
Idea for improving hover

### ISSUE THREAD

**Issue by scottming** [nvimdev/lspsaga.nvim#1281]
**Is your feature request related to a problem? Please describe.**

I remember in previous versions, the height of the floating window for hover was dynamic. However, now it seems to be a fixed window, which results in unnecessary blank space.

![CleanShot 2023-09-07 at 22 11 15@2x](https://github.com/nvimdev/lspsaga.nvim/assets/12830256/4a20d28d-7eab-43a4-be59-337103535c16)

and `from ...ls` is really not necessary, I think 99% of people will only use one ls for a given language.

**Describe the solution you'd like**

<img width="544" alt="CleanShot 2023-09-07 at 22 16 38@2x" src="https://github.com/nvimdev/lspsaga.nvim/assets/12830256/e7e9504a-9faf-423f-b5e5-c491fe907601">

Only show a hover window that can includes the height of the content.

**Describe alternatives you've considered**

**Additional context**

**Comment by scottming** [comment]
Same as the rename

<img width="665" alt="CleanShot 2023-09-07 at 22 22 50@2x" src="https://github.com/nvimdev/lspsaga.nvim/assets/12830256/fbd2b324-5a5b-42de-81dd-3197e25521dd">

**Comment by scottming** [comment]
Same as the diagnostics

<img width="878" alt="CleanShot 2023-09-07 at 22 24 21@2x" src="https://github.com/nvimdev/lspsaga.nvim/assets/12830256/7166591a-b00d-4147-8e9c-8a9597e7c591">

**Comment by glepnir** [comment]
hmm something wrong in your neovim config. it works as before and I can't reproduce it.

**Comment by glepnir** [comment]
can support or source should be only work when there has one more server.

**Comment by scottming** [comment]
Many people may use 2 servers, such as copilot, but copilot doesn't provide a hover function.

<img width="779" alt="CleanShot 2023-09-08 at 17 22 56@2x" src="https://github.com/nvimdev/lspsaga.nvim/assets/12830256/0fcc05fb-0a33-46f0-a01e-8d79c1c461ba">

![CleanShot 2023-09-08 at 16 26 42@2x](https://github.com/nvimdev/lspsaga.nvim/assets/12830256/dd4dedf6-03f7-408c-86b9-2f802e1922eb)

**Comment by glepnir** [comment]
filter server by method `hover` if only one should not show the source.

**Comment by glepnir** [comment]
update

**Comment by scottming** [comment]
> filter server by method hover if only one should not show the source.

hi, @glepnir I think here should be:

```elixir
if #clients ~= 1 then
```

**Comment by glepnir** [comment]
oh good catch fixed.
