### ISSUE TITLE
attempt to call field get_clients has a nil value

### ISSUE THREAD

**Issue by diegoulloao** [nvimdev/lspsaga.nvim#1282]
### Describe the bug

An error appears when doing `peek_definition` in typescript.

```
Error executing Lua callback: ...site/pack/packer/start/lspsaga.nvim/lua/lspsaga/util.lua:60: attempt to call field 'get_clients' (a nil value)
stack traceback:
        ...site/pack/packer/start/lspsaga.nvim/lua/lspsaga/util.lua:60: in function 'get_client_by_method'
        ...ack/packer/start/lspsaga.nvim/lua/lspsaga/definition.lua:207: in function 'peek_definition'
        ...e/pack/packer/start/lspsaga.nvim/lua/lspsaga/command.lua:8: in function <...e/pack/packer/start/lspsaga.nvim/lua/lspsaga/command.lua:7>
        ...e/pack/packer/start/lspsaga.nvim/lua/lspsaga/command.lua:74: in function 'load_command'
        ...m/site/pack/packer/start/lspsaga.nvim/plugin/lspsaga.lua:8: in function <...m/site/pack/packer/start/lspsaga.nvim/plugin/lspsaga.lua:7>
```

### Steps to reproduce

Go to any component call like:
```tsx
<Component {...props} />
```

And peek definition over `Component`.

Screen recording:

https://github.com/nvimdev/lspsaga.nvim/assets/45423661/0d1fead9-092c-49c1-a200-817129d3108a

### Expected behavior

See the definition modal without issues.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-673+g622ae2f53-Homebrew

### lspsaga commit

latest: c9b17bc

### Terminal name/version

iterm2 3.4.20

**Comment by adler-sudo** [comment]
I'm also seeing the same issue in Python

**Comment by glepnir** [comment]
update neovim head version .

**Comment by diegoulloao** [comment]
I've downgraded to version `9.0.1` working as expected.

**Comment by glepnir** [comment]
you build neovim with old commit . just compile with latest commit.
