### ISSUE TITLE
rename run error

### ISSUE THREAD

**Issue by CnsMaple** [nvimdev/lspsaga.nvim#1285]
### Describe the bug

when i try to rename,it seems get a error location and project rename cut a char.

https://github.com/nvimdev/lspsaga.nvim/assets/92523839/63d1c211-63ef-4643-bb02-421dd7bc7531

### Steps to reproduce

rename project

### Expected behavior

run normal.

### Neovim version (nvim -v)

windowrulev2 = float, class:^(Thunar)$

### lspsaga commit

32c1b40

### Terminal name/version

kitty

**Comment by glepnir** [comment]
I don't get what's problem is. in second `c` it give me `cc` . you get `;`? I can't reproduce it.

![image](https://github.com/nvimdev/lspsaga.nvim/assets/41671631/b4279277-835f-4b05-b11b-d02a29571113)


second. seems like you use `rename ++project` . project rename should filter lsp result file. this need improve.

**Comment by glepnir** [comment]
I tried in second c can't reproduce . problem 2 has solved.

**Comment by CnsMaple** [comment]
i know.i set the key is "cr",but i use "<leader>cr",the cursor move the next char.

**Comment by CnsMaple** [comment]
but the problem 2 no solve.

**Comment by glepnir** [comment]
problem 2 not solved ? current file still in project rename window right ?  change to other keymap will also cause problem 1 ?

**Comment by CnsMaple** [comment]
https://github.com/nvimdev/lspsaga.nvim/assets/92523839/236efcc5-0d45-4e82-bec0-250ca082f43b

**Comment by CnsMaple** [comment]
the problem 1 i solve,Because I pressed an extra space, the cursor moved to the next position.I'll just correct the buttons

**Comment by glepnir** [comment]
fixed

**Comment by CnsMaple** [comment]
ok,thanks
