### ISSUE TITLE
`symbol_in_winbar` will change another module color

### ISSUE THREAD

**Issue by CnsMaple** [nvimdev/lspsaga.nvim#1286]
### Describe the bug

the winbar,i use "heirline.nvim"

https://github.com/nvimdev/lspsaga.nvim/assets/92523839/f15d8314-7552-4144-9d54-aa98034c6111

### Steps to reproduce

no need.

### Expected behavior

normal

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1f551e0

### lspsaga commit

3df3e1d

### Terminal name/version

kitty

**Comment by glepnir** [comment]
all winbar highlight group is set with `Saga`Prefix. and you can see what stl value is .

**Comment by CnsMaple** [comment]
you are right.the reason is another module no set the color.and then it use this color.
