### ISSUE TITLE
Disable code actions in peek_definition modal

### ISSUE THREAD

**Issue by diegoulloao** [nvimdev/lspsaga.nvim#1289]
**Is your feature request related to a problem? Please describe.**
Yes, sometimes when moving along the file inside the peek_definition modal, the space between the left and the code is blinking because of the code action bulb/icon.

I want code actions with the bulb available in the main buffer/file, but not inside peek_definition. It looks very annoying for read.

**Describe the solution you'd like**
Allow an option for enable/disable code actions inside the peek_definition modal (and maybe other modals).

**Describe alternatives you've considered**
Disable code actions, but it will disable it in the main buffer too. That's not what I expect.

**Additional context*
Check the capture:

https://github.com/nvimdev/lspsaga.nvim/assets/45423661/5bfb4da5-671e-4ffc-8605-5b924e8fdcbe

**Comment by diegoulloao** [comment]
I realized that the issue is because all lines have code actions saying "move to another file". Idk why.

<img width="750" alt="Screenshot" src="https://github.com/nvimdev/lspsaga.nvim/assets/45423661/8cd043ee-26db-4643-9ee8-8749ec05e97c">

**Comment by glepnir** [comment]
did you use stc or `signcolumn` ?

**Comment by diegoulloao** [comment]
> did you use stc or `signcolumn` ?

No that I know. What is it?

**Comment by glepnir** [comment]
I mean did you set `statuscolumn` or `signcolumn` value.

**Comment by diegoulloao** [comment]
yes.

```lua
vim.opt.signcolumn = "yes"
```

**Comment by glepnir** [comment]
yep maybe can disable this local option on this peek window.

**Comment by diegoulloao** [comment]
how can this affect the code actions along the file? I don't remember why I set this to `yes`. Maybe for gitsigns or something.

**Comment by diegoulloao** [comment]
If I disable that line in my config I get the same blinking behavior in the main buffer.

**Comment by glepnir** [comment]
it's a window-local option if i remember correctly . I can disable it locally on peek window.

**Comment by diegoulloao** [comment]
Let's try.

**Comment by diegoulloao** [comment]
@glepnir fixed.
Thanks a lot 🙏🏻

**Comment by kxccc** [comment]
If you use peek_definition again within the peek_definition floating window, the problem will occur again. I found that only the first floating window has its signcolumn set to 'no', but this attribute is not set for the subsequent windows that are opened.

Here is my solution:

![image](https://github.com/user-attachments/assets/310af337-678c-4a2c-807a-02ea3af2968e)
