### ISSUE TITLE
Double action bubble icon appears on each side + when scrolling up/down it goes crazy.

### ISSUE THREAD

**Issue by Delice0** [nvimdev/lspsaga.nvim#1291]
### Describe the bug

I want to disable this icon completely.

**Screenshot**
<img width="525" alt="Screenshot 2023-09-24 at 00 16 47" src="https://github.com/nvimdev/lspsaga.nvim/assets/59118341/a987c836-a03e-45a2-8852-0dbdbe967e35">

**Video**

https://github.com/nvimdev/lspsaga.nvim/assets/59118341/9fa85254-0a3e-4d14-9129-9aae017885b3

### Steps to reproduce

I'm using LazyVim with all default configs and plugins.

### Expected behavior

I expect the icon not to go crazy.

I also expect an option to disable it completely.

### Neovim version (nvim -v)

latest

### lspsaga commit

latest

### Terminal name/version

iterm2

**Comment by glepnir** [comment]
`lightbulb.debounce = 500 or more` defualt is 10
