### ISSUE TITLE
Add option to increase width of outline preview window

### ISSUE THREAD

**Issue by Delice0** [nvimdev/lspsaga.nvim#1293]
**Is your feature request related to a problem? Please describe.**
This doesn't look nice.

I would like to center this to my window with paddings on each corner so it looks good and i can see exactly what code I have in that function without navigating to it.

Or, at least give me an option to modify it because right now, it triggers my OCD.

<img width="476" alt="Screenshot 2023-09-24 at 00 11 41" src="https://github.com/nvimdev/lspsaga.nvim/assets/59118341/4fe3e733-b028-46ca-bdbe-bc76308f0660">

**Describe the solution you'd like**
An option to increase the width of the floating window when previewing inside outline.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by glepnir** [comment]
sry that's a bug . relative win is wrong so the width not big enough.
