### ISSUE TITLE
Lspsaga code_action does not work correctly.

### ISSUE THREAD

**Issue by arafune** [nvimdev/lspsaga.nvim#1296]
### Describe the bug

When I execute "Lspsaga code_action", the following message appears.  

I think it is conflicting with another plugin, but I am not sure which plugin is the problem.　I would appreciate any guidance you could give me, including how to find out. 

Thank you in advance.

Error detected while processing CursorMoved Autocommands for "<buffer=26>":
Error executing lua callback: ...e/.local/share/nvim/lazy/guard.nvim/lua/guard/format.lua:112: CursorMoved Autocommands for "<buffer=26>": Vim(write)
:E382: Cannot write, 'buftype' option is set
stack traceback:
        [C]: in function 'nvim_command'
        ...e/.local/share/nvim/lazy/guard.nvim/lua/guard/format.lua:112: in function 'apply_text_edits'
        ...vim/lazy/lspsaga.nvim/lua/lspsaga/codeaction/preview.lua:55: in function 'get_action_diff'
        ...vim/lazy/lspsaga.nvim/lua/lspsaga/codeaction/preview.lua:141: in function 'action_preview'
        ...e/nvim/lazy/lspsaga.nvim/lua/lspsaga/codeaction/init.lua:239: in function 'set_cursor'
        ...e/nvim/lazy/lspsaga.nvim/lua/lspsaga/codeaction/init.lua:99: in function <...e/nvim/lazy/lspsaga.nvim/lua/lspsaga/codeaction/init.lua:98>

### Steps to reproduce

cmd: Lspsaga code_action

### Expected behavior

No error message appear.

### Neovim version (nvim -v)

v0.9.2

### lspsaga commit

b7873e556a5451c5febc0d46ba80767b2beea49e 

### Terminal name/version

alacrity / iterm2

**Comment by glepnir** [comment]
need more reproduce step with a min config thanks. looks like some callback through an error from `CursorMoved` . relate plugin have guard.nvim.

**Comment by glepnir** [comment]
again could you give me a reproduce step like some example language code. which servers you config on this buffer. min config is need.

**Comment by glepnir** [comment]
```lua
vim.opt.rtp:append('~/workspace/guard.nvim')
vim.opt.rtp:append('~/workspace/lspsaga.nvim')
vim.opt.rtp:append('~/workspace/guard-collection')

require('lspsaga').setup({})
---add something you need
```

and the pythong code can trigger this error.

**Comment by glepnir** [comment]
@xiaoshihou514  could you take a look at this ? I assume it's guard bug

**Comment by glepnir** [comment]
thanks for details. i will check it later.

**Comment by xiaoshihou514** [comment]
I will delve into this
