### ISSUE TITLE
Using 'Finder" with custom width+height causes the peek window to view from center view instead of left view

### ISSUE THREAD

**Issue by Delice0** [nvimdev/lspsaga.nvim#1299]
### Describe the bug

When using 'Finder', with the following custom layout config:

```
      finder = {
        max_height = 0.8, -- max_height of the finder window (float layout)
        left_width = 0.5, -- Width of the left finder window (float layout)

```

.. causes the peek window to center making it hard to read the actual code.

<img width="1465" alt="Screenshot 2023-09-30 at 01 15 17" src="https://github.com/nvimdev/lspsaga.nvim/assets/59118341/b8c81900-6bdf-4218-8f37-1cad52524654">

### Steps to reproduce

Nothing special other than changing the layout config as described in the previous section.

### Expected behavior

I expect to the peek floating window to be left aligned or at least give me an option to set it left aligned. Or, making the 'Finder" smart enough to decide if it should be left-, right- or center aligned.

### Neovim version (nvim -v)

latest

### lspsaga commit

latest

### Terminal name/version

iterm2

**Comment by glepnir** [comment]
> causes the peek window to center making it hard to read the actual code.

sry I don't understand this and `expect behavior`..

**Comment by Delice0** [comment]
> > causes the peek window to center making it hard to read the actual code.
> 
> 
> 
> sry I don't understand this and `expect behavior`..

Look at the right window which shows the code. You cannot see the left side of the code.

**Comment by glepnir** [comment]
maybe it's a bug looks like the left window cover right window

**Comment by Delice0** [comment]
> maybe it's a bug looks like the left window cover right window

Maybe :) you know your code better than I do

**Comment by Delice0** [comment]
@glepnir your latest commit [https://github.com/nvimdev/lspsaga.nvim/commit/b152b155e1855c0f386b9e34b1a15287687626ad]  didn't fix the issue.

**Comment by glepnir** [comment]
hmm update to latest ? the right window should not be cover

**Comment by Delice0** [comment]
> hmm update to latest ? the right window should not be cover

I have the latest. It hasn't been fixed

**Comment by glepnir** [comment]
wired after this patch I can't reproduce it .

**Comment by glepnir** [comment]
how about now. (update)

**Comment by Delice0** [comment]
Yes, not it works fine. Thank you!
