### ISSUE TITLE
An option to filter non-project files when using 'Finder'

### ISSUE THREAD

**Issue by Delice0** [nvimdev/lspsaga.nvim#1300]
**Is your feature request related to a problem? Please describe.**
I want to filter out everything that is inside my root dir aka my project dir when using 'Finder'.

Here you can see 'jdt://' stuff being showed when using 'Finder' which I don't care about.

<img width="1465" alt="Screenshot 2023-09-30 at 01 15 17" src="https://github.com/nvimdev/lspsaga.nvim/assets/59118341/9ed351da-b873-46ad-85e6-bf4fd59efc06">

**Comment by glepnir** [comment]
```lua
finder.filter = {
       ['textDocument/references'] = function(result)
            ...do filter
       end
}
```
