### ISSUE TITLE
Exclude some parts of the path when using 'Finder'

### ISSUE THREAD

**Issue by Delice0** [nvimdev/lspsaga.nvim#1301]
**Is your feature request related to a problem? Please describe.**
When using 'Finder', i get a long path showing the ref/impl etc. which I realy don't care about. I just want the last 3 paths. Or at least an option to declare how long the path should be e.g. if i want 2 it should be something like ../c/d/example.java or 3 ../b/c/d/example.java

Here's an example of how it currently looks like and it takes enormous much space.

<img width="1465" alt="Screenshot 2023-09-30 at 01 15 17" src="https://github.com/nvimdev/lspsaga.nvim/assets/59118341/ba92265b-1f30-4e8b-9c47-773676c7c5cd">

**Comment by glepnir** [comment]
```lua
finder.fname_sub = function(fname)
    return sub string of fname.
 end
```

**Comment by Delice0** [comment]
Where exactly do I put this code?

**Comment by glepnir** [comment]
```lua
lspsaga.setup({
      finder = {
              fname_sub = function
```

**Comment by Delice0** [comment]
Thank you. 

Here's the solution I came up with:

```
        fname_sub = function(fname)
          local NUM_URLS = 3 -- Change this number as needed
          local parts = {}

          -- Split string into parts by "/"
          for part in string.gmatch(fname, "[^/]+") do
            table.insert(parts, part)
          end

          local start_index = #parts - NUM_URLS + 1
          if start_index < 1 then
            start_index = 1
          end

          return table.concat(parts, "/", start_index)
        end,
```
