### ISSUE TITLE
[finder] Improve docs for filter config and function signature

### ISSUE THREAD

**Issue by protiumx** [nvimdev/lspsaga.nvim#1302]
**Is your feature request related to a problem? Please describe.**
The `filter` documentation currently is incorrect https://nvimdev.github.io/lspsaga/finder/#filter-search-result.
The function signature mentioned in the doc does not match what the [code ](https://github.com/nvimdev/lspsaga.nvim/blob/main/lua/lspsaga/finder/box.lua#L53) does.

The filter function signature is also not very usable since it has return a similar object `{ resul = {} }` otherwise the finder breaks.
E.g.
```lua
{
  result = { {
      range = {
        ["end"] = {
          character = 14,
          line = 24
        },
        start = {
          character = 10,
          line = 24
        }
      },
      uri = "file:///a.go"
    }, {
      range = {
        ["end"] = {
          character = 14,
          line = 25
        },
        start = {
          character = 10,
          line = 25
        }
      },
      uri = "file:///a.go"
    } }
}

```

**Describe the solution you'd like**
Fix the original documented filter config to filter each result
```lua
    filter = {
      ['textDocument/implementation'] = function(item)
         return item.uri ~= "test.go"
      end
    },
```

**Comment by glepnir** [comment]
```lua
filter = {
      ['textDocument/implementation'] = function(item)
         item now is list-like table .
      end
    },
```
