### ISSUE TITLE
Set custom `filetype` for popups

### ISSUE THREAD

**Issue by luiz00martins** [nvimdev/lspsaga.nvim#1305]
## Problem
Currently, lspsaga popups have the filetype `markdown`. 

This makes plugins such as [nvim-scrollbar](https://github.com/petertriho/nvim-scrollbar) or neovim folds activate inside of the popups, leading to the popup autofolding, or having a scrollbar (in general, being affected by a variety of effects from other plugins):

![image](https://github.com/nvimdev/lspsaga.nvim/assets/43142209/f7574917-4ccd-43da-9dd6-271ed1cf5a26)

## Desired Solution
Most plugins have the ability to filter by `filetype`.

It would be nice if lspsaga popups had its own `filetype`, so it could be excluded from these plugins (without having to exclude `markdown`).

**Comment by glepnir** [comment]
because some lsp results have markdown format. set it to markdown then use treesitter render that will have a good ui. if set to other filetype this behavior will broken . why nvim-scrollbar not provide a blacklist table or function then do detect the float window is create by lspsaga then ignore ?

**Comment by luiz00martins** [comment]
How do I detect if the current window was created by lspsaga?

**Comment by gwenyambira** [comment]
You could check the title of the window in an autocommand, then disable the undesired behaviour. 
`vim.api.nvim_win_get_config` gets you the title and its highlight (e.g. `title = { { "ERROR", "DiagnosticError" } },
`).
There must be better way though...
