### ISSUE TITLE
hey yo! glepnir wtf is this?

### ISSUE THREAD

**Issue by daUnknownCoder** [nvimdev/lspsaga.nvim#1307]
### Describe the bug

```
  Failed (1)
    ○ lspsaga.nvim  LspAttach   nvim-lspconfig
        fatal: remote error: upload-pack: not our ref 5faeec9f2508d2d49a66c0ac0d191096b4e3fa81
        fatal: remote error: upload-pack: not our ref 5faeec9f2508d2d49a66c0ac0d191096b4e3fa81
        fatal: remote error: upload-pack: not our ref 5faeec9f2508d2d49a66c0ac0d191096b4e3fa81
        fatal: remote error: upload-pack: not our ref 5faeec9f2508d2d49a66c0ac0d191096b4e3fa81
        fatal: reference is not a tree: 5faeec9f2508d2d49a66c0ac0d191096b4e3fa81

```
lazy.nvim installing with "nvimdev/lspsaga.nvim"

### Steps to reproduce

it aint installing what min.lua u will get...

### Expected behavior

it should install, it worked previously but i did a reset of `~/.config/nvim`, `~/.local/state/nvim`, `~/.local/share/nvim`, and since then i m not able to install lspsaga...

### Neovim version (nvim -v)

NVIM v0.9.2

### lspsaga commit

commit b8de5b5

### Terminal name/version

kitty 0.29.2 created by Kovid Goyal

### why am i still using this:
see i can switch to `kkharji/lspsaga.nvim` but what i like is the clean [lspsaga-finder](https://github.com/nvimdev/lspsaga.nvim/assets/41671631/e897f717-e2e1-4d28-a4d6-1d12afd707e3) and [lspsaga-outline](https://github.com/nvimdev/lspsaga.nvim/assets/41671631/a6c81350-3282-4e3a-b373-5e6216f1d83f), so if u can solve this or a way to get this type of look in `kkharji/lspsaga.nvim` coz in that there's no outline and lspsaga finder looks like this [lspsaga-lsp-finder](https://user-images.githubusercontent.com/41671631/107140076-ae77ec00-695a-11eb-8329-0b9d8361bfeb.gif)

**Comment by glepnir** [comment]
clean your local env. try remove lspsaga from lazy install dir.

**Comment by daUnknownCoder** [comment]
> clean your local env. try remove lspsaga from lazy install dir.

thanks bud that worked
