### ISSUE TITLE
Finder float window too small with vertical splits

### ISSUE THREAD

**Issue by wjdwndud0114** [nvimdev/lspsaga.nvim#1309]
**Is your feature request related to a problem? Please describe.**
When using `:Lspsaga finder` with 4 windows side by side, the window is too small to be useful:
<img width="1918" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/30526747/308b3358-6bc0-47aa-8bad-e2d1c17f042f">

**Describe the solution you'd like**
Finder should have an option to utilize the whole screen space rather than be limited by the window width where the command was run.

Like this (from `:FzfLua lsp_finder`)
<img width="1920" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/30526747/691dd155-698a-4d7a-871b-09aa7df77bb5">

**Describe alternatives you've considered**
`:FzfLua lsp_finder` :/

**Additional context**
opening from left most window:
<img width="1919" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/30526747/5eda82f9-7733-4abf-8539-46b6081f1936">

**Comment by wjdwndud0114** [comment]
that was quick 😮  thank you!
<img width="1919" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/30526747/ff82e43b-e509-493b-bb78-828bc2eac1d9">

The right most one isn't affected by the fix though:
<img width="1919" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/30526747/cd7c80a6-987e-4611-8b1e-46b38666ad79">

I'm assuming the left window ("REFERENCES") needs similar attention.

**Comment by glepnir** [comment]
how about now

**Comment by wjdwndud0114** [comment]
a little broken
<img width="1919" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/30526747/714880f6-51b6-4d18-a155-5726c9a7d7e7">
<img width="1919" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/30526747/f9f1e61d-9325-4a60-8014-c9102d3ff033">
<img width="1919" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/30526747/9d76d785-0abf-4e6b-b269-e1537a6e0e24">
<img width="961" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/30526747/735d409e-a8f1-45c2-a3dd-ba21d39c8f96">
<img width="1917" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/30526747/7e2e9588-875a-4351-8127-720810e3dca3">

**Comment by glepnir** [comment]
thanks for report it how about now.

**Comment by wjdwndud0114** [comment]
<img width="1919" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/30526747/2517a4f6-819d-4096-87ae-f567101b7f2c">
<img width="1916" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/30526747/a47d4310-e5b7-4bec-a2fb-40a60f1157d2">
<img width="1918" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/30526747/0baed012-26dd-4290-9d5c-4bf49b65d92a">

**Comment by glepnir** [comment]
except pic one other works fine i think

**Comment by glepnir** [comment]
increased.

**Comment by wjdwndud0114** [comment]
seems better than before
<img width="1915" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/30526747/40000c3d-df1e-422f-bb29-9a8f98aef65d">
<img width="1920" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/30526747/e2d02d1e-70f2-4826-8625-5cd559e5e36d">
<img width="1919" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/30526747/af15fb08-9c9f-4a45-9fb9-97be3da1eb31">
<img width="1919" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/30526747/8ad6a5bf-ce87-42fe-a9de-c14b955729e6">

**Comment by glepnir** [comment]
hardcore min is 50 maybe not good in your screen ? for me it works like this

![image](https://github.com/nvimdev/lspsaga.nvim/assets/41671631/615ee6c0-6422-4ce3-b075-bcf328fee8c9)
