### ISSUE TITLE
hierarchical structure on winbar

### ISSUE THREAD

**Issue by arafune** [nvimdev/lspsaga.nvim#1312]
It may not be an lspsaga issue, but please let me know the hint.  

Please see the screenshot.
<img width="1705" alt="スクリーンショット 2023-10-07 16 16 38" src="https://github.com/nvimdev/lspsaga.nvim/assets/6754804/73364d3c-bc04-49dd-9f48-6f6031143700">

On the left is the lua file editing and on the right is the snapthot of python file editing.
In the lua file, the winbar region shows the current line status as a hierarchical structure. It is very clear.
In python, on the other hand, this is not the case. The current line is 141, so I want "TightLayoutEngine >> __init__" to appear in the winbar area. If it is the lsp issue let me what I should check first? 

(I usually use ruff by "python-lsp/python-lsp-ruff").

**Comment by glepnir** [comment]
I use pyright for test it works fine.

![image](https://github.com/nvimdev/lspsaga.nvim/assets/41671631/c46004ed-3b37-4837-ac83-fe18a6044f17)
