### ISSUE TITLE
[Error] failed finding symbols - server may not be initialized, try again later.

### ISSUE THREAD

**Issue by bassamsdata** [nvimdev/lspsaga.nvim#1314]
### Describe the bug

Thank you for this amazing plugin.

I have an issue when I do the cmd `Lspsaga outline` it shows me this error directly and doesn't open the outline.
error:
`[lspsaga] failed finding symbols - server may not be initialized, try again later.`

Maybe the problem from my config, I don't know, but I'd like to know what might the issue be so I can fix it.

I elaborate more on the issue below.

### Steps to reproduce

I did try with nvchad fresh install, yet the same issue when I lazy loaded the plugin.
just add in the `custome/plugins.lua`

```lua
    {    'nvimdev/lspsaga.nvim',
    config = function()
      require('lspsaga').setup{}
    end,
    dependencies = {
      'nvim-treesitter/nvim-treesitter', -- optional
      'nvim-tree/nvim-web-devicons'     -- optional
    }
```
yet, when I add `lazy = false` it works.
but when I add the same thing to my config, it doesn't work.

### Expected behavior

show the outline

### Neovim version (nvim -v)

0.9.2

### lspsaga commit

b8de5b5

### Terminal name/version

Alacritty 0.12.3

**Comment by glepnir** [comment]
try outline later that mean server not initialized.

**Comment by Gogiu23** [comment]
I have the same issue. The server is initialized. When i do LspInfo it does return me 2 servers attached.
![image](https://github.com/nvimdev/lspsaga.nvim/assets/102987251/4ed30c69-c6b5-4b96-94b7-d2fd4652d5fd)
![image](https://github.com/nvimdev/lspsaga.nvim/assets/102987251/5c8cd16e-df36-4918-9878-92cadbd7f347)

**Comment by jh244212647** [comment]
I have the same issue
![image](https://github.com/nvimdev/lspsaga.nvim/assets/28759961/cec6067e-e606-4085-a2ae-3e75cebcb464)
![image](https://github.com/nvimdev/lspsaga.nvim/assets/28759961/802f0cf3-0e1c-4113-9e14-3f7cc432cb66)

**Comment by zedseven** [comment]
I can confirm that:
1. This is still an issue;
2. It's fixed by not lazy-loading the plugin.

You can see my commit above that fixed the issue for me. My LSP servers were initialised, it was just this plugin that wasn't working.
