### ISSUE TITLE
Can't close float window with `q` after pressing `ctrl-o` in `peek_definition` window.

### ISSUE THREAD

**Issue by scottming** [nvimdev/lspsaga.nvim#1325]
### Describe the bug

as title

### Steps to reproduce

1. `peek_definition`
2. press `ctrl-o`
3. press `q`

### Expected behavior

step 3 should close the window.

### Neovim version (nvim -v)

0.9.4

### lspsaga commit

c66acbdf3dd10ab42219d270d1a6b9a096e85ff8

### Terminal name/version

alacritty

**Comment by glepnir** [comment]
q is buffer-local map when you do `<C-o>` the buffer changed . q not work.

**Comment by scottming** [comment]
> q is buffer-local map when you do <C-o> the buffer changed . q not work.

ok
