### ISSUE TITLE
An option to exclude the definition(s) using command `finder`

### ISSUE THREAD

**Issue by 0x00-ketsu** [nvimdev/lspsaga.nvim#1331]
Is there a plan to add an option `includeDeclaration` to `finder` ?  see in file `finder/init.lua` is setted to `true`.

**Comment by glepnir** [comment]
only set to true when no definition method in finder.

**Comment by 0x00-ketsu** [comment]
> only set to true when no definition method in finder.

Update to latest commit, an error occurred when execute command `Lspsaga finder`, you may have a try local.

![image](https://github.com/nvimdev/lspsaga.nvim/assets/16932133/b9c9fc5a-a852-473b-8651-a6371bc3e062)

**Comment by glepnir** [comment]
emm that's a typo.

**Comment by 0x00-ketsu** [comment]
The typo is not fixed, `tbl_contains` in `finder/init.lua` line 507
![image](https://github.com/nvimdev/lspsaga.nvim/assets/16932133/5ac06e5a-258c-46a6-b21c-d611e3b5a894)
