### ISSUE TITLE
Lspsaga finder def+ref show only definitions

### ISSUE THREAD

**Issue by yannick1974** [nvimdev/lspsaga.nvim#1336]
### Describe the bug

Since commit b48b807 `Lspsaga finder def+ref` shows only the definition while `Lspsaga finder ref` correctly shows the references. Reverting the commit (including the typos associated commits) makes the finder  behaves correctly — well at least as before.

I experience this problem on Python code with pyright or pylsp as LSP servers.

### Steps to reproduce

With a Python file like using default Lspsage configuration:

```python
def test():
    print("foo")


if __name__ == "__main__":
    test()
```

Invoking  `Lspsaga finder def+ref` on the `test()` shows only the definition while `Lspsaga finder ref` shows the two references, including the definition.

### Expected behavior

`Lspsaga finder def+ref` should show both the definition and the references.

### Neovim version (nvim -v)

v0.10.0-dev bc850ba

### lspsaga commit

28051f1

### Terminal name/version

konsole

**Comment by glepnir** [comment]
In most languages, definitions same as Declaration. But some other languages such as C python are ignored. I think adding result filtering is feasible. Elements that are the same as range should be deleted.
