### ISSUE TITLE
Fix border style 

### ISSUE THREAD

**Issue by ls-devs** [nvimdev/lspsaga.nvim#1339]
### Describe the bug

Borders are kind of italic. (Only on Windows Terminal ).
How to fix them ?
![image](https://github.com/nvimdev/lspsaga.nvim/assets/58638832/9e45cf1a-31a6-4113-8e7c-55aeff7a9b63)

I tried changing hlgroup doing like this : (using catppuccin colorscheme )
```lua
          DiagnosticSource = { italic = false },
          DiagnosticPos = { italic = false },
          DiagnosticWord = { italic = false },
          DiagnosticError = { italic = false },
          DiagnosticWarn = { italic = false },
          DiagnosticInfo = { italic = false },
          DiagnosticBorder = { italic = false },
          DiagnosticNormal = { italic = false },
          DiagnosticText = {},
          DiagnosticShowNormal = { italic = false },
          DiagnosticShowBorder = { italic = false },
          SagaBorder = { italic = false },
          LspSagaDiagnosticSource = { italic = false },
          LspSagaDiagnosticPos = { italic = false },
          LspSagaDiagnosticWord = { italic = false },
          LspSagaDiagnosticError = { italic = false },
          LspSagaDiagnosticWarn = { italic = false },
          LspSagaDiagnosticInfo = { italic = false },
``` 
Bid it didnt change anything.
This problem only appear on Windows Terminal, since I've the same configuration of neovim on my Linux and I've correct borders.

### Steps to reproduce

I don't have any steps to reproduce the issue, since the only thing that changed was my OS and the terminal.
All I can share is my neovim configuration if someone wants to try it on a Windows Terminal + Fira Code Nerd Font.
Config : [ls-devs/nvim](https://github.com/ls-devs/nvim)

### Expected behavior

Borders are displayed correctly

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1438+g8405649f9-dirty Build type: RelWithDebInfo LuaJIT 2.1.1697887905

### lspsaga commit

85f7c38

### Terminal name/version

Windows Terminal

**Comment by glepnir** [comment]
output of `hi DiagnosticWarn`
