### ISSUE TITLE
Allow custom hl for winbar

### ISSUE THREAD

**Issue by qRoC** [nvimdev/lspsaga.nvim#1343]
Cannot set different background for winbar and float/popups

https://github.com/neovim/neovim/issues/26037

## Proposal

Allow set custom `Saga*` highlights for winbar (configurable prefix https://github.com/nvimdev/lspsaga.nvim/blob/283a3fc8e01191095d33c078031c577e8f9427b9/lua/lspsaga/symbol/winbar.lua#L10C23-L10C23 )

**Comment by glepnir** [comment]
can have an option to receive a background color or config `SagaWinbarxx` with a background color in your config.

**Comment by qRoC** [comment]
Same issue for borders (for example diagnostic.border_follow) :(

**Comment by glepnir** [comment]
follow to false then it will use `SagaBorder`

**Comment by qRoC** [comment]
Yes, I just report. Perhaps the best way is to create own highlights and link them to current ones.

**Comment by glepnir** [comment]
yes. `DiagnosticBorder` for use
