### ISSUE TITLE
Just show file name in winbar

### ISSUE THREAD

**Issue by uloco** [nvimdev/lspsaga.nvim#1346]
Is there a way to just show the file name in the winbar without the breadcrumbs at all?

**Comment by glepnir** [comment]
symbol_in_winbar.folder_level = 0

**Comment by uloco** [comment]
@glepnir this only disables the folders. I meant to disable the other scopes as well...

**Comment by glepnir** [comment]
only file name ?

**Comment by glepnir** [comment]
disalbe lspsaga winbar then `vim.opt.winbar='%f'` should work

**Comment by uloco** [comment]
@glepnir oh I see... makes sense. thanks!
