### ISSUE TITLE
The LSP Saga breadcrumbs line is overwritten by the Lualine winbar.

### ISSUE THREAD

**Issue by massimiliano-della-rovere** [nvimdev/lspsaga.nvim#1354]
### Self Checks

- [X] I'm using the latest lualine.
- [X] I didn't find the issue in existing issues or PRs.

### How to reproduce the problem
Install LSP Saga, see https://nvimdev.github.io/lspsaga/
In LSP Saga configuration, activate the breadcrumb module, I used the "Use event = 'LspAttach' (need latest lazy.nvim 2023-July-9)" method.
Activate both tabline, winbar and inactive_winbar.

### Actual behaviour
The LSP Saga breadcrumbs line is overwritten by the Lualine winbar.

### Minimal config to reproduce the issue
```
require('lazy').setup({
  {
    -- Set lualine as statusline
    'nvim-lualine/lualine.nvim',
    dependencies = { 'nvim-tree/nvim-web-devicons' },
    -- See `:help lualine.txt`
    opts = {
      options = {
        icons_enabled = true,
        theme = 'onedark',
        -- component_separators = { left = '', right = ''}, -- = '|',
        -- section_separators = { left = '', right = ''}, -- = '',
        section_separators = { left = '', right = '' },
        component_separators = { left = '', right = '' }
      },
      sections = {
        lualine_a = { 'mode' },
        lualine_b = { 'branch', 'diff', 'diagnostics' },
        lualine_c = { { 'filename', path = 3 } },
        lualine_x = { 'encoding', 'fileformat', 'filetype' },
        lualine_y = { 'progress' },
        lualine_z = { 'location' },
      },
      tabline = {
        lualine_a = { { 'tabs', mode = 2 } },
        lualine_b = {},
        lualine_c = {},
        lualine_x = {},
        lualine_y = {},
        lualine_z = { { 'buffers', mode = 4 } },
      },
      winbar = {
        lualine_a = { { 'windows', mode = 2 } },
        lualine_b = {},
        lualine_c = {},
        lualine_x = { 'searchcount' },
        lualine_y = {},
        lualine_z = { 'selectioncount' },
      },
      inactive_winbar = {
        lualine_a = { { 'windows', mode = 0 } },
        lualine_b = {},
        lualine_c = {},
        lualine_x = {},
        lualine_y = {},
        lualine_z = {},
      }

    },
  },
  {
    'nvimdev/lspsaga.nvim',
    config = function()
      require('lspsaga').setup({})
    end,
    dependencies = {
      'nvim-treesitter/nvim-treesitter',
      'nvim-tree/nvim-web-devicons',
    },
    event = 'LspAttach'
  },
})
```

### Expected behaviour
The LSP Saga breadcrumbs to appear after the Lualine tabline and winbar.

### Neovim version (nvim -v)

v0.10.0-dev

### lspsaga commit

 d3dfaea

### lualine commit

 2248ef2

### Terminal name/version

xfce4-terminal 0.8.10

# see
https://github.com/nvim-lualine/lualine.nvim/issues/1155

**Comment by glepnir** [comment]
emmm lualine winbar run after lspsag winbar load, some event triggered then override. winbar plugin just use one ? disable one of them.

**Comment by massimiliano-della-rovere** [comment]
> emmm lualine winbar run after lspsag winbar load, some event triggered then override. winbar plugin just use one ? disable one of them.

sorry, I didn't understand what to do.

**Comment by glepnir** [comment]
i mean just use one. or disable lualine winbar in lspattach.

**Comment by massimiliano-della-rovere** [comment]
Thanks

Il giorno gio 23 nov 2023 alle ore 13:02 Raphael ***@***.***>
ha scritto:
