### ISSUE TITLE
`:Git blame` output is misaligned when LSPSaga Breadcrumbs are enabled

### ISSUE THREAD

**Issue by amcooper** [nvimdev/lspsaga.nvim#1364]
**Is your feature request related to a problem? Please describe.**
I'm using both the [vim-fugitive](https://github.com/tpope/vim-fugitive) and [LSPSaga](https://github.com/nvimdev/lspsaga.nvim) plugins for Neovim. The Breadcrumbs module of the latter does not play nicely with the `:Git blame` command of the former. Basically vim-fugitive is unaware of the extra line slipped in by LSPSaga Breadcrumbs, and the blame line is rendered misaligned from its associated line of code. 

**Describe the solution you'd like**
The vim-fugitive blame output should line up with the code.

**Describe alternatives you've considered**
- Patch to move the LSPSaga breadcrumbs to the bottom of the window.
- Patch vim-fugitive to insert a blank line at the top of the blame output.

**Additional context**
Screenshot:
![misaligned-blame](https://github.com/nvimdev/lspsaga.nvim/assets/2553540/1b5faef1-f53d-4329-a0f0-d82a5743c9f1)

I'm posting the same issue at vim-fugitive, as I don't know what the best place to tackle this would be.

**Comment by glepnir** [comment]
emm bradcrumb just set int a buffer which attached lsp server

**Comment by penryu** [comment]
I'm also having this issue, but I can't tell what the resolution is.
