### ISSUE TITLE
Highlight group for SagaFinder Title not available or not working properly?

### ISSUE THREAD

**Issue by diegoulloao** [nvimdev/lspsaga.nvim#1365]
### Describe the bug

I'm trying to change the file location title background at the top of each sagafinder floating window, but I'm not able to find the right one, it seems like is not available, not working or something.

<img width="874" alt="Screenshot 7" src="https://github.com/nvimdev/lspsaga.nvim/assets/45423661/a8658294-2cdf-491f-b964-af7e4207ef0c">

I have tried almost all the groups listed in `:hi Saga...`
`SagaFinderFname` didn't work.

### Steps to reproduce

- Use gruvbox theme from: https://github.com/ellisonleao/gruvbox.nvim
- Open sagafinder
- Try to change the title bg of the modal

### Expected behavior

Get any hi group working for change the title bg at the top of the sagafinder float window.

### Neovim version (nvim -v)

0.9.4

### lspsaga commit

latest

### Terminal name/version

iterm2 build 3.4.22

**Comment by glepnir** [comment]
SagaTitle its link to Title

**Comment by diegoulloao** [comment]
Thanks, it works.
What about border bg hi groups and context bg for lsp diagnostics (jump)?

![Screenshot 3](https://github.com/nvimdev/lspsaga.nvim/assets/45423661/ba7ddf1c-1175-42e0-88bf-c63ffa10db30)

I'd really appreciate your help!
