### ISSUE TITLE
How to disable annoying light bulb

### ISSUE THREAD

**Issue by lzyuz** [nvimdev/lspsaga.nvim#1367]
I want to disable the light bulb.
![image](https://github.com/nvimdev/lspsaga.nvim/assets/127972121/5e849b20-b528-4c93-ac13-42b45711786a)
I tried the following ways:
- disable lightbulb
![image](https://github.com/nvimdev/lspsaga.nvim/assets/127972121/329d9686-c723-4c8b-aea8-1c2e610a46e5)
- set code_action icon to be " "
![image](https://github.com/nvimdev/lspsaga.nvim/assets/127972121/8c40ccdf-33c0-4024-8d5f-1d13e63785d2)

However, none  of them works, Can anyone help me to sovle this problem? Thanks a lot

**Comment by glepnir** [comment]
emm it should work.

**Comment by lzyuz** [comment]
@glepnir sorry for disturbing, I find I required the wrong config file (╥﹏╥)
