### ISSUE TITLE
Symbol_in_winvar - Not respecting theme "transparency"

### ISSUE THREAD

**Issue by ls-devs** [nvimdev/lspsaga.nvim#1380]
### Describe the bug

Hi,
Sometimes, the end of the winbar is not respecting my theme transparency.
Please see : 
![image](https://github.com/nvimdev/lspsaga.nvim/assets/58638832/c65cba4f-5230-4d80-b339-2e9916de930f)

But sometimes, it does : 
![image](https://github.com/nvimdev/lspsaga.nvim/assets/58638832/648f4d57-3a8d-4504-bccd-e9920230b0c5)

I tried to change the following highlights, but without success : 
```lua
SagaWinbarSep = { bg = colors.none }
SagaWinbarFileName = { bg = colors.none }
SagaWinbarFolderName = { bg = colors.none }
SagaWinbarFolder = { bg = colors.none }
```

### Steps to reproduce

Actually I don't have any steps to reproduce. All I can share is my neovim setup at : [ls-devs/nvim](https://github.com/ls-devs/nvim)

### Expected behavior

Respect my theme transparency

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2104+gfd2ed024c Build type: RelWithDebInfo LuaJIT 2.1.1703358377

### lspsaga commit

 3112b7a

### Terminal name/version

Window Terminal

**Comment by ls-devs** [comment]
Fixed, the problem was from my colorscheme and not LspSaga.

**Comment by Runner-2019** [comment]
HI，how do you fix this issue? I met same situation.
