### ISSUE TITLE
Hide this Bulb?

### ISSUE THREAD

**Issue by niksingh710** [nvimdev/lspsaga.nvim#1390]
![image](https://github.com/nvimdev/lspsaga.nvim/assets/60490474/dc3097f1-06dd-4047-93e4-bdefeef6092a)
i want it to come when i am on the line not always.

_Originally posted by @niksingh710 in https://github.com/nvimdev/lspsaga.nvim/discussions/1375_

**Comment by darricheng** [comment]
Which bulb are you referring to? The one at the line number column or at the closing brace of the struct?

**Comment by niksingh710** [comment]
> Which bulb are you referring to? The one at the line number column or at the closing brace of the struct?

to be exact the on `}` one but if possible would like to hide both.

**Comment by darricheng** [comment]
Did you checkout the [docs](https://nvimdev.github.io/lspsaga/lightbulb/) for the config options? 

You can do the following: 

```lua
require('lspsaga').setup {
  lightbulb = {
    enable = false, -- disables both
    virtual_text = false, -- disables just the one at the end of the line
  },
}
```

**Comment by niksingh710** [comment]
> ```lua
> lightbulb = {
>     enable = false, -- disables both
>     virtual_text = false, -- disables just the one at the end of the line
>   },
> ```

Sorry for late response, I was AFK.
I can ensure that this works and thanks a lot.
it was hard to find in documentation.
