### ISSUE TITLE
Code action error with diagnostic

### ISSUE THREAD

**Issue by Gitfz810** [nvimdev/lspsaga.nvim#1433]
### Describe the bug

Use 'o' to call code action with diagnostic failed.

<img width="2015" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/38970394/e24f55b5-4051-4737-abae-48f8a2c94845">

### Steps to reproduce

go version: 1.22.2
language_file: 
main.go
```go
package main

import (
	"fmt"
	"io/ioutil"
)

func mian() {
	_, err := ioutil.ReadFile("./file.txt")
	if err != nil {
		fmt.Println(err)
	}
}
```
saga.lua
```lua
return {
  "nvimdev/lspsaga.nvim",
  dependencies = {
    "nvim-treesitter/nvim-treesitter", -- optional
    "nvim-tree/nvim-web-devicons", -- optional
  },
  event = "BufReadPre",
  config = function()
    local setup, saga = pcall(require, "lspsaga")
    if not setup then
      return
    end

    saga.setup({
      -- when there has code action it will show a lightbulb
      lightbulb = {
        enable = false,
        sign = false,
      },
      beacon = {
        enable = false,
      },
      finder = {
        keys = {
          toggle_or_open = "<CR>",
          quit = "q",
          close = "<ESC>",
        },
      },
      rename = {
        in_select = false,
      },
      definition = {
        keys = {
          tabnew = "<C-c>n",
        },
      },
    })
  end,
}
```

### Expected behavior

use code action success.

### Neovim version (nvim -v)

NVIM v0.9.5

### lspsaga commit

"lspsaga.nvim": { "branch": "main", "commit": "052234296f13e2705d5d290c7bd5a36d3dd81fde" }

### Terminal name/version

terminal

**Comment by Miguerfi** [comment]
try comment this section on your lspsaga:
```
api.nvim_create_autocmd('CursorMoved', {
    buffer = self.action_bufnr,
    callback = function()
      self:set_cursor(tuples)
    end,
  })
```
/.local/share/nvim/lazy/lspsaga.nvim/lua/lspsaga/codeaction/init.lua

**Comment by glepnir** [comment]
please update plugin first... your version too old

**Comment by Gitfz810** [comment]
I update lspsage to the newest version, commit 59d4648c3d4b40f316c3db852b3758c66ff6ca03; but it still error.

Use action number to execute is ok; but jump to the float window and use 'o' to execute action failed.

**Comment by Gitfz810** [comment]
> try comment this section on your lspsaga:
> 
> ```
> api.nvim_create_autocmd('CursorMoved', {
>     buffer = self.action_bufnr,
>     callback = function()
>       self:set_cursor(tuples)
>     end,
>   })
> ```
> 
> /.local/share/nvim/lazy/lspsaga.nvim/lua/lspsaga/codeaction/init.lua

thx, but it's not the codeaction  error, error message show the diagnostic's `close_win` method is nil.

**Comment by Gitfz810** [comment]
I found the `close_win` method is not implemented for the `diag` variable, and comment the `close_win` method at 161 still error.

<img width="1664" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/38970394/149788c2-bd6f-4781-b1a7-11a0ab71b948">
