### ISSUE TITLE
How to cancel the shadow of the floating frame

### ISSUE THREAD

**Issue by renjinxi** [nvimdev/lspsaga.nvim#1436]
<img width="1788" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/48796935/6c97d1f0-c297-448e-8be0-f719605c0a33">

**Comment by zennolux** [comment]
That needs your colorscheme's support, nothing about itself

**Comment by renjinxi** [comment]
> That needs your colorscheme's support, nothing about itself

Thank you for your reply. I am new to neovim. I have no shadow on another plug-in (the following is a screenshot). Does it mean that my theme supports canceling the shadow? I hope I can cancel the shadow in the configuration options of the plugin. , I did not find the corresponding configuration option
![image](https://github.com/nvimdev/lspsaga.nvim/assets/48796935/b8d7d318-5cfd-4f38-9658-84eab9adfbdb)

**Comment by zennolux** [comment]
Maybe you can try these before setting your colorscheme
```
vim.cmd([[
 autocmd ColorScheme * highlight NormalFloat guibg=NONE ctermbg=NONE
 autocmd ColorScheme * highlight Float guibg=NONE ctermbg=NONE
 autocmd ColorScheme * highlight FloatBorder guibg=NONE ctermbg=NONE
 autocmd ColorScheme * highlight FloatShadow guibg=NONE ctermbg=NONE
]])
vim.cmd.colorscheme("your colorscheme")
```

**Comment by renjinxi** [comment]
>Maybe you can try these before setting your colorschemeMaybe you can try these before setting your colorscheme
>
> ```
> vim.cmd([[
> autocmd ColorScheme * highlight NormalFloat guibg=NONE ctermbg=NONE
> autocmd ColorScheme * highlight Float guibg=NONE ctermbg=NONE
> autocmd ColorScheme * highlight FloatBorder guibg=NONE ctermbg=NONE
> autocmd ColorScheme * highlight FloatShadow guibg=NONE ctermbg=NONE
> ]])
>vim.cmd.colorscheme("your colorscheme")
> ```

Thank you very much for your answer. It worked, but it also changed the behavior of my other plugins. I just want to change the shadow of the floating window of this plugin, but I think the plugin itself does not provide such a configuration, but I Still thank you very much for your answer
