### ISSUE TITLE
Q: latest diangostic style is deifferent with older

### ISSUE THREAD

**Issue by 0x00-ketsu** [nvimdev/lspsaga.nvim#1442]
### Describe the bug

Compared with the latest diangostic style, I personally feel that the previous version (`45be478ddeac8c0b60153acc826ec5e30feeb15d`) is more elegant.

### Steps to reproduce

```python
# python
if __name__ == "__main__":
    s = 'foo
```

Execute with command `Lspsaga diagnostic_jump_next`

### Expected behavior

**latest**

<img width="517" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/16932133/56a9c6e8-8e5f-4606-8a14-5f6d7b8f2cb0">

**previous version** `45be478ddeac8c0b60153acc826ec5e30feeb15d`

<img width="495" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/16932133/f9f2c06f-a0d7-466f-a790-1d538c873e0e">

### Neovim version (nvim -v)

0.10.0

### lspsaga commit

ac2720450a940cc306ce495dd06a92e253d91f09

### Terminal name/version

xterm2

**Comment by glepnir** [comment]
the new implementation is based on neovim original diagnostic jump .

**Comment by 0x00-ketsu** [comment]
> the new implementation is based on neovim original diagnostic jump . it support show many diagnostic informations. so what the expect behavior then ? border color ?

- border color
- move tips `Diagnostics:` to border line, like screenshot below
   <img width="339" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/16932133/487eeeab-5f96-4d8e-9066-de1d8c918998">

**Comment by glepnir** [comment]
that's easy but if the position have many diangostic informations like E W the border still use ERROR a bit wired.

**Comment by 0x00-ketsu** [comment]
> that's easy but if the position have many diangostic informations like E W the border still use ERROR a bit wired.

Understand, this is just a personal suggestion

**Comment by glepnir** [comment]
I have update an ui improve it works like this now. 

<img width="932" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/41671631/0c16d70f-5efc-4adf-9e23-43e5197295bc">

**Comment by 0x00-ketsu** [comment]
> I have update an ui improve it works like this now.
> <img alt="image" width="932" src="https://private-user-images.githubusercontent.com/41671631/331842926-0c16d70f-5efc-4adf-9e23-43e5197295bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwODU2NjIsIm5iZiI6MTcxNjA4NTM2MiwicGF0aCI6Ii80MTY3MTYzMS8zMzE4NDI5MjYtMGMxNmQ3MGYtNWVmYy00YWRmLTllMjMtNDNlNTE5NzI5NWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDAyMjI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhNjJmNWI1NjJmM2Q4NWQ4NDc1NjEyODA1YTUwNWUzZWIxZGI1OWUxMzFjNTUyODBjMGQxNzQ3ODRlYzdmM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CzUjXj2AYmUre-ZmH-1mYVRmrIgJ8xVPg4xOO7Eojh4">

👍

But, the new UI when works with plugin `ellisonleao/gruvbox.nvim` enable `transparent_mode`, diangostic sign E W background color is gone, like below

<img width="710" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/16932133/8efb74fc-4a7f-4650-b2e8-666c16c60a67">

**min config**

```lua
local api = vim.api

api.nvim_command('set nu')
api.nvim_command('set relativenumber')

vim.opt.signcolumn = 'yes'

-- Plugins
local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    'git',
    'clone',
    '--filter=blob:none',
    'https://github.com/folke/lazy.nvim.git',
    '--branch=stable', -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

-- Example using a list of specs with the default options
vim.g.mapleader = ',' -- Make sure to set `mapleader` before lazy so your mappings are correct

require('lazy').setup({
  {
    'ellisonleao/gruvbox.nvim',
    config = function()
      require('gruvbox').setup({
        transparent_mode = true,
      })
    end,
  },
  {
    'hrsh7th/nvim-cmp',
    event = 'InsertEnter',
    config = function()
      ---@diagnostic disable-next-line: missing-fields
      require('cmp').setup({})
    end,
    dependencies = {
      { 'hrsh7th/cmp-nvim-lsp' },
    },
  },
  {
    'neovim/nvim-lspconfig',
    config = function()
      require('lspconfig').lua_ls.setup({})
      require('lspconfig').gopls.setup({})
      require('lspconfig').pyright.setup({})
      require('lspconfig').rust_analyzer.setup({})
    end,
  },
  {
    'williamboman/mason.nvim',
    config = function()
      require('mason').setup({})
    end,
  },
  { 'williamboman/mason-lspconfig.nvim' },
  {
    'nvimtools/none-ls.nvim',
    config = function()
      local null_ls = require('null-ls')
      local code_actions = null_ls.builtins.code_actions
      local diagnostics = null_ls.builtins.diagnostics
      null_ls.setup({
        sources = {
          code_actions.gitsigns,
          diagnostics.golangci_lint,
        },
      })
    end,
    dependencies = { { 'nvim-lua/plenary.nvim' } },
  },
  {
    'lewis6991/gitsigns.nvim',
    lazy = true,
    event = { 'BufRead', 'BufNewFile' },
    config = function()
      require('gitsigns').setup({})
    end,
    dependencies = { 'nvim-lua/plenary.nvim' },
  },
  {
    'glepnir/lspsaga.nvim',
    event = 'BufRead',
    config = function()
      require('lspsaga').setup({
        implement = { enable = true },
      })
    end,
    dependencies = { { 'nvim-tree/nvim-web-devicons' }, { 'nvim-treesitter/nvim-treesitter' } },
  },
})

vim.cmd('colorscheme gruvbox')
```

**Comment by glepnir** [comment]
what's the output of `hi DiagnosticError ` ?

**Comment by 0x00-ketsu** [comment]
> hi DiagnosticError

```vim
DiagnosticError xxx links to GruvboxRed
GruvboxRed     xxx guifg=#fb4934
```

**Comment by glepnir** [comment]
update now should work i guess

**Comment by 0x00-ketsu** [comment]
> update now should work i guess

update to latest, background still not work

<img width="1345" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/16932133/fb4706fc-f742-4a77-af73-0e038975a7a9">

**Comment by glepnir** [comment]
`:hi DiagnosticErrorReverse` output is what

**Comment by 0x00-ketsu** [comment]
> `DiagnosticErrorReverse`

```vim
DiagnosticERRORReverse xxx guifg=Black
```

**Comment by glepnir** [comment]
should be works .I ignore it still need get color again when it's a link

**Comment by 0x00-ketsu** [comment]
> should be works .I ignore it still need get color again when it's a link

works fine now 👏
