### ISSUE TITLE
Add option to disable action preview on diagnostic jumps

### ISSUE THREAD

**Issue by taketwo** [nvimdev/lspsaga.nvim#1446]
**Is your feature request related to a problem? Please describe.**

Until recently, jumping between diagnostic messages displayed a float window with diagnostic text and available code actions. This float window was anchored above or below the problematic code line. Therefore, after a jump, I had a clear view of the problematic code line, a bit of context above or below, and available actions:

![image](https://github.com/nvimdev/lspsaga.nvim/assets/1241736/3fafc32d-c9b3-48a2-bf36-757edc99c91f)

With current `HEAD` version, I started getting action preview diff as well, which is anchored on the opposite side of the problematic code line. As a result, I see neither the code line itself, nor any context around it. This makes it hard to comprehend where I jumped and what is the issue:

![image](https://github.com/nvimdev/lspsaga.nvim/assets/1241736/1192780c-74eb-4de4-b299-48b356bec7ce)

**Describe the solution you'd like**

Personally, I don't need to see action preview, so I'd like to have an option to disable it. For those who find the action preview useful, I guess it would be more convenient if the floating windows were attached above/below the problematic code line such that the line itself is not occluded by the floats.

**Comment by glepnir** [comment]
because it default to select first action. i think we can add an option to do it

**Comment by glepnir** [comment]
add `diagnsotic.auto_preview` default true you can set false to disable and you can still use `<C-f>` and `<C-b>` to show aciton preview

**Comment by glepnir** [comment]
Tip. you can set FloatBorder color

**Comment by taketwo** [comment]
Not sure I understand what you mean :smile:

**Comment by glepnir** [comment]
`:hi FloatBorder guifg=blue` give it a try then

**Comment by taketwo** [comment]
Oh, I see what you mean, thanks :+1:
