### ISSUE TITLE
Compact with neovim@0.10.0

### ISSUE THREAD

**Issue by JiuRanYa** [nvimdev/lspsaga.nvim#1448]
### Describe the bug

Today I update neovim version.

Some features not work. 

Eg: This is the rename error screenshot:

![image](https://github.com/nvimdev/lspsaga.nvim/assets/58846658/ad53da9a-ec28-43cd-a972-f694bad8d6c1)

### Steps to reproduce

none

### Expected behavior

work

### Neovim version (nvim -v)

0.10.0

### lspsaga commit

latest

### Terminal name/version

kitty@latest

**Comment by glepnir** [comment]
emmm there does not have this function try update

**Comment by JiuRanYa** [comment]
@glepnir Hi, I'm using the latest lspsaga. Is there anything I can do ?

**Comment by JiuRanYa** [comment]
@glepnir Hi, I'm using the latest lspsaga, is there anything I can do? 

Here is the keymap function: 

```lua
keymap("n", "rn", ":Lspsaga rename<CR>", { silent = true })
```

**Comment by glepnir** [comment]
which commit you used of this plugin?

**Comment by JiuRanYa** [comment]
![image](https://github.com/nvimdev/lspsaga.nvim/assets/58846658/ace39092-cabd-48bf-99d1-680e1b338db0)

I don't how to check the commit.

![image](https://github.com/nvimdev/lspsaga.nvim/assets/58846658/7e4bcfaa-5853-483e-8026-67fc0bb663f5)


All things work before i update neovim 0.10.0

**Comment by glepnir** [comment]
your commit is too old update the plugin

**Comment by JiuRanYa** [comment]
I update the latest version , other error here, sadly :(

![image](https://github.com/nvimdev/lspsaga.nvim/assets/58846658/3f0a8806-7787-4cba-b89b-dc3223e53026)

**Comment by JiuRanYa** [comment]
Sry about that. I solved that by passing config in setup with {}. Thanks a lot!
