### ISSUE TITLE
Option show_code_action from diagnostic jump window not working

### ISSUE THREAD

**Issue by diegoulloao** [nvimdev/lspsaga.nvim#1455]
### Describe the bug

It just doesn't work. I am missing something?

```lua
require('lspsaga').setup({
  diagnostic = {
    show_code_action = false -- doesn't work
  },
})
```

<img width="938" alt="Screenshot 7" src="https://github.com/nvimdev/lspsaga.nvim/assets/45423661/a75e0e19-f3f6-4e1c-8265-51ce0cc2b044">

### Steps to reproduce

Just jump by diagnostic to diagnostic

### Expected behavior

-

### Neovim version (nvim -v)

0.10.0

### lspsaga commit

200256d

### Terminal name/version

iterm2 3.5.0

**Comment by diegoulloao** [comment]
BTW how I can remove the corner label `H:1`?

**Comment by glepnir** [comment]
did you install diff ts parser. title  can be improve if there is only one diagnostic.

**Comment by diegoulloao** [comment]
> did you install diff ts parser. title can be improve if there is only one diagnostic.

Sorry I didn't get you. If is the treesitter error what are you referring to that's resolved.
Finally I was able to hide the action preview at the top of the jump diagnostic window by setting `auto_preview = false,` (I think the web doc isn't updated).

About the title `H:1`, I understand that's not a option to disable it yet, right?
I'd like to.

Thanks!

**Comment by glepnir** [comment]
currently no option to disable it. so it can be improve.  about tresitter error it's hard to find out why i mean the error from neovim. for me i don't get this error in diff action preview window

<img width="863" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/41671631/8faace21-1323-49eb-81d0-12427785eb18">

**Comment by diegoulloao** [comment]
> currently no option to disable it. so it can be improve. about tresitter error it's hard to find out why i mean the error from neovim. for me i don't get this error in diff action preview window
> 
> <img alt="image" width="863" src="https://private-user-images.githubusercontent.com/41671631/335570354-8faace21-1323-49eb-81d0-12427785eb18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxODc0MzAsIm5iZiI6MTcxNzE4NzEzMCwicGF0aCI6Ii80MTY3MTYzMS8zMzU1NzAzNTQtOGZhYWNlMjEtMTMyMy00OWViLTgxZDAtMTI0Mjc3ODVlYjE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDIwMjUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwYzI5NjdmNDFkYTYxMmIxODEwZDFkNzg5ODdkMTczMmI1NDdlY2NlNmJhMjY2M2MxNTNlMDA5MzdlMTIzOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2MCyntSFqC2gZ5yUrVb7sQOLeE5PVu2jEfPgqaLhqEo">

Now it looks like this:
<img width="838" alt="Screenshot" src="https://github.com/nvimdev/lspsaga.nvim/assets/45423661/568b3031-4a8b-41db-8369-d306123c3ed2">

Before remove the diff action preview window, I fixed the treesitter error, I was able to see the diff with highlighted colors all working good.

About the corner label/title, it would be good to provide an option to hide it, I'm using a very clean "ui" looking and for sure other users do it too, so in this case is better for us to just have the floating window with clean borders.

Thanks for replying.

**Comment by glepnir** [comment]
yup you can use ui.button to change the type of button arrow cube etc. and i has been update yesterday if only one diagnostic titile will not shown.

**Comment by diegoulloao** [comment]
Thanks!

**Comment by diegoulloao** [comment]
Marked as completed: ba6b071
