### ISSUE TITLE
attempt to call field '_trim' (a nil value)

### ISSUE THREAD

**Issue by SamiAlsubhi** [nvimdev/lspsaga.nvim#1459]
### Describe the bug

lspsaga used to work before I updated neovim to latest and all plugins to latest.
now i get this error:
'''
E5108: Error executing lua ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/window.lua:158: attempt to call field '_trim' (a nil value)
stack traceback:
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/window.lua:158: in function 'create_win_with_border'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/rename.lua:68: in function <...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/rename.lua:45>
        ...e/pack/packer/start/lspsaga.nvim/lua/lspsaga/command.lua:40: in function 'load_command'
        [string ":lua"]:1: in main chunk
'''
lsp saga setup:
'''lua
lspsaga.setup {
  debug = false,
  use_saga_diagnostic_sign = true,
  -- diagnostic sign
  error_sign = "",
  warn_sign = "",
  hint_sign = "",
  infor_sign = "",
  diagnostic_header_icon = "   ",
  -- code action title icon
  code_action_icon = " ",
  code_action_prompt = {enable = true, sign = true, sign_priority = 40, virtual_text = true},
  finder_definition_icon = "  ",
  finder_reference_icon = "  ",
  max_preview_lines = 10,
  finder_action_keys = {
    open = "o",
    vsplit = "s",
    split = "i",
    quit = "q",
    scroll_down = "<C-f>",
    scroll_up = "<C-b>"
  },
  code_action_keys = {quit = "q", exec = "<CR>"},
  rename_action_keys = {quit = "<C-c>", exec = "<CR>"},
  definition_preview_icon = "  ",
  border_style = "single",
  rename_prompt_prefix = "➤",
  server_filetype_map = {},
  diagnostic_prefix_format = "%d. "
}
'''
OS: MACOS

### Steps to reproduce

I get the error whenever lspsaga needs to display a popup

[my dot files](https://github.com/SamiAlsubhi/nvim)

### Expected behavior

displayin the popup

### Neovim version (nvim -v)

0.10

### lspsaga commit

latest

### Terminal name/version

iTerm2 3.4.19

**Comment by glepnir** [comment]
did you update plugin ?

**Comment by glepnir** [comment]
which commit  ? there is no _trim method used.

**Comment by SamiAlsubhi** [comment]
My bad it was another fork that i was using "tami5/lspsaga.nvim". I just noticed that. now it is working switch to this repo.
