### ISSUE TITLE
Manually have to start LSPServer via LSPRestart to make Lspsaga work

### ISSUE THREAD

**Issue by aleyrizvi** [nvimdev/lspsaga.nvim#1460]
### Describe the bug

https://github.com/aleyrizvi/nvim-config

I am new to neovim. Everything else is working fine, but for lazysaga, I receive error :

```
[lspsaga] failed finding symbols - server may not be initialized, try again later.
```
I have to restart my LSP by `LSPRestart` and then everything works fine such as symbol outline.

Can you help please?

### Steps to reproduce

Use my config and try <leader>lo (which is lsp saga outline)

### Expected behavior

LSP server should be started automatically, no?

### Neovim version (nvim -v)

v0.10.0

### lspsaga commit

no idea

### Terminal name/version

iterm2

**Comment by glepnir** [comment]
this mean server not initilized just wait for a while and do it again.

**Comment by aleyrizvi** [comment]
Sorry, it was my bad it seems.
For reference if someone is facing same issue: I was missing `event = "LspAttach",` in my config.
