### ISSUE TITLE
expected number, got string in make_given_range_params

### ISSUE THREAD

**Issue by alextrastero** [nvimdev/lspsaga.nvim#1507]
### Describe the bug

Going to next diagnostic throws error:

```
Error executing vim.schedule lua callback: vim/shared.lua:0: bufnr: expected number, got string                                         │
stack traceback:                                                                                                                        │
        [C]: in function 'error'                                                                                                        │
        vim/shared.lua: in function 'validate'                                                                                          │
        vim/shared.lua: in function '_resolve_bufnr'                                                                                    │
        /opt/nvim-linux64/share/nvim/runtime/lua/vim/lsp/util.lua:1977: in function 'make_given_range_params'   
```

### Steps to reproduce

Open a file with a diagnostic error and go to next, error appears at bottom, I have the latest neovim from this morning and just updated lsp_saga with lazy

Not sure if related but when I do hover on error it shows a warning:
`position_encoding` param is required in `vim.lsp.util.make_position_params. Defaulting to position encoding of the first client.`

### Expected behavior

Shows error nicely :-)

### Neovim version (nvim -v)

NVIM v0.11.0-dev-1325+g30726c778c

### lspsaga commit

aa1a9ef

### Terminal name/version

kitty

**Comment by sawinjer** [comment]
got same

**Comment by alextrastero** [comment]
Thanks @glepnir this error seems to have disappeared, is this in anyway related to the issue appearing when using `goto-definition` I added a comment here https://github.com/neovim/nvim-lspconfig/pull/3449#issuecomment-2531033061

**Comment by alextrastero** [comment]
> Not sure if related but when I do hover on error it shows a warning:
position_encoding param is required in vim.lsp.util.make_position_params. Defaulting to position encoding of the first client.

**Comment by sawinjer** [comment]
Same, after updating to the latest version, the issue is gone. Thank a lot!
