### ISSUE TITLE
Bring back the move_in_saga config

### ISSUE THREAD

**Issue by MatheusNSantiago** [nvimdev/lspsaga.nvim#713]
**Is your feature request related to a problem? Please describe.**
The config to remap the hjkl keys for moving in saga was removed. Since my keyboard layout is different, this is a must for me

**Describe the solution you'd like**
A config that does the same as the old "move_in_saga={prev={}, next={}}" did

**Comment by glepnir** [comment]
I think you can do it in your local 

```lua

vim.api.nvim_create_autocmd("Filetype", {
 pattern = 'lspasgafinder',
 callback = function()
    vim.keymap.set('n', your key , '<Down>', { buffer = true, nowai =true})
 end
```
