### ISSUE TITLE
Renaming with live previews as with IncRename

### ISSUE THREAD

**Issue by xyven1** [nvimdev/lspsaga.nvim#798]
**Is your feature request related to a problem? Please describe.**
When renaming variables in a editor is is helpful to see a live update of the edited name as it makes locations where the name is being edited even more clear. Plugins such as [inc-rename](https://github.com/smjonas/inc-rename.nvim/) add this to Neovim, but only implements basic renaming.

**Describe the solution you'd like**
The underlying functionality of [inc-rename](https://github.com/smjonas/inc-rename.nvim/) would be merged into `:Lspsaga rename`

**Describe alternatives you've considered**
Continue using `:IncRename` while missing out on features of `:Lspsaga rename`

**Comment by tsakirist** [comment]
@glepnir This is not supported. LspSaga merely highlights references, what the OP asked was an enhancement like [inc-rename.nvim](https://github.com/smjonas/inc-rename.nvim/) in which each key-press **live** updates/renames the references.

This would make renaming more complete.
