### ISSUE TITLE
Show "implementations" and "parent/interface" signs in the signcolumn

### ISSUE THREAD

**Issue by mortymacs** [nvimdev/lspsaga.nvim#805]
**Is your feature request related to a problem? Please describe.**
I configured my LSP, and it works fine. I'm looking for a way to show these kinds of icons in my `signcolumn` for Golang. If it could work for other programming languages, that would be great.

![image](https://user-images.githubusercontent.com/1261448/215786882-5338bc53-eba2-4771-9a89-55daebeb171a.png)

It helps me to get it quickly that this is an interface implementation or this interface has implementation somewhere.

**Describe the solution you'd like**
Showing `implementations` and `parent/interface` icons in the sign column. 

**Describe alternatives you've considered**

**Additional context**

**Comment by glepnir** [comment]
i know this and you can click this sign I remember.

**Comment by glepnir** [comment]
maybe can use lsp semantic token to implement this . not sure but can give it a try

**Comment by mortymacs** [comment]
I was trying to use Treesitter to fetch all definitions of the current buffer and then looking up for their types. I'd like to contribute for this feature, but I'm not sure the way I'm implementing is the correct way. Would you please guide me what should I do?

**Comment by glepnir** [comment]
if you are using treesitter you need write  s-expression to match the word is interface or not . about lsp semantic token  .I am not sure it can parse node to interface type .need some check

**Comment by glepnir** [comment]
gopls doc said it have interface type . that you can use i think. and this feature only for go. so I think ask in some go relate plugin will be better ? if i have time i will try implement it and put code in there thanks.

https://github.com/golang/tools/blob/master/gopls/doc/semantictokens.md

**Comment by mortymacs** [comment]
Thank you @glepnir 

I hope I can help to implement this feature, but, I'm not that fast in Neovim Lua plugin development. This feature is for more than Golang. It can be used in other languages as well. This is the C++ one:
![image](https://user-images.githubusercontent.com/1261448/216788083-3055f3ee-cbd9-4a23-9e95-4af7455b762b.png)

**Comment by glepnir** [comment]
interesting for this. but the priority is  a little lower.

**Comment by mortymacs** [comment]
> I got an idea implement this and try write a min code that it works . so I plan to add this support in 0.3 version

Great news of the day! Thanks a million!

**Comment by glepnir** [comment]
a draft

![image](https://github.com/nvimdev/lspsaga.nvim/assets/41671631/6a35f304-fc14-4df9-ad23-004bed69d5f4)

**Comment by mortymacs** [comment]
yaaaay! :tada: Awesome!
Is it also clickable? I have a suggestion: if there's only one way to implement it, we can jump right into it. But if there are multiple options, we can show a list of them and let you choose the one you prefer before diving in.

**Comment by glepnir** [comment]
I want make a menu with a keymap .   also can support clickable .but just full keyboard is better

**Comment by mortymacs** [comment]
Awesome! Thank you so much!
After your merge, I'll start implementing the icon for "jump-to-interface" for methods based on your implementation.
Something like this:
![image](https://github.com/nvimdev/lspsaga.nvim/assets/1261448/b7ecd307-dcd5-475a-96d1-53a37dfd5c88)

**Comment by glepnir** [comment]
`ui.imp_sign ` to config it like this . about arrow . nerd font doesn't have a icon combine I and arrow.  

![image](https://github.com/nvimdev/lspsaga.nvim/assets/41671631/2ddd2acb-ac08-4fed-98c6-d2fb3465f137)

**Comment by mortymacs** [comment]
Awesome! :star_struck:
