### ISSUE TITLE
Hover Doc does not disappear in tsx

### ISSUE THREAD

**Issue by nbili** [nvimdev/lspsaga.nvim#865]
### Describe the bug

In `tsx` or `ts` files, Hover Doc does not disappear.

![image](https://user-images.githubusercontent.com/22109673/218302021-b6258933-2f9f-415f-9add-c706edd0284b.png)

### Steps to reproduce

`vim.keymap.set('n', 'K', '<Cmd>Lspsaga hover_doc<CR>')`

### Expected behavior

When my cursor moved, the Hover Doc disappeared.

### Neovim version (nvim -v)

0.9.0

### lspsaga commit

lastest

### Terminal name/version

term2

**Comment by glepnir** [comment]
IDK but before have same issue then he tell me the reason is `typescript.nvim`

**Comment by jovanovicbogdan** [comment]
I'm experiencing the same issue, I can only close hover_doc by clicking with mouse first then `:q`. @nbili did you find the fix maybe? Thanks!

**Comment by glepnir** [comment]
can you reproduce it with a min config ?

**Comment by llllvvuu** [comment]
I have this issue, but it seems to be caused by `tsconfig.json`, not by any vim plugins. TS sample:
```
export interface Repro {
  /**
   * minimal repro
   */
  minimal: number
}
```
It works fine without `tsconfig.json`. But now put in the following `tsconfig.json`:
```
{
  "compilerOptions": {
    "target": "es6",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules", "services"]
}
```
Then this issue will repro (press "K" on `minimal`)

I removed all my nvim config and all but the following plugins:
```
lspsaga.nvim
nvim-lspconfig
nvim-treesitter
nvim-web-devicons
```
and config:
```
local keymap = vim.keymap.set
require("lspsaga").setup({})
keymap("n", "K", "<cmd>Lspsaga hover_doc<CR>")
```

I'll try to see if I can trim down the `tsconfig.json` to find the problematic line.

**Comment by glepnir** [comment]
I am not sure you run it with clean flag . `nvim --clean - u min.lua a.ts` . I can't reproduce.

min.lua 

```lua
vim.opt.rtp:append('~/Workspace/lspsaga.nvim')
vim.opt.rtp:append('~/Workspace/nvim-lspconfig')
vim.opt.rtp:append('~/.local/share/nvim/lazy/nvim-treesitter/')
require('nvim-treesitter').setup({})

local lspconfig =require('lspconfig')
lspconfig.tsserver.setup({})

local keymap = vim.keymap.set
require("lspsaga").setup({})
keymap("n", "K", "<cmd>Lspsaga hover_doc<CR>")
```

![image](https://github.com/nvimdev/lspsaga.nvim/assets/41671631/4032cc8d-101a-4cba-bf30-0b3112abc2c3)

give it a test

![Untitled](https://github.com/nvimdev/lspsaga.nvim/assets/41671631/d4aefa62-6570-43d9-8149-9fe51ab9b3b4)

**Comment by llllvvuu** [comment]
^Using those steps I was able to isolate it to two changes from your `min.lua`

Add, after
```
lspconfig.tsserver.setup({})
```
this line:
```
lspconfig.custom_elements_ls.setup({})
```
then it repros.

Maybe there is something wrong with `custom_elements_ls` language server. It's not too important to me, so I can just disable it :+1:. Hopefully this helps others

**Comment by llllvvuu** [comment]
So I think what's happening is when you have two language servers responding, `hover_doc` will open 2 hover windows and close only one.

**Comment by glepnir** [comment]
okay add that line reproduced.

**Comment by glepnir** [comment]
oh I think I know what happen. two servers both have response

**Comment by glepnir** [comment]
as a trace I will create a new issue for this and fix in next version
