### ISSUE TITLE
Open finder in a horizontal split

### ISSUE THREAD

**Issue by defr0std** [nvimdev/lspsaga.nvim#985]
**Is your feature request related to a problem? Please describe.**

When performing elaborate analysis of references, the floating window UI of the finder is not always convenient. In this scenario you need to jump to the code, navigate around, then move back to the finder results and continue with the next reference. If you lose the floating window in the meantime, it's frustrating as you need to start over.

**Describe the solution you'd like**

- Have a config option to render the finder in the horizontal split.
- The horizontal split should have two columns - one for finder results, and one for preview (e.g. `:sp` for finder results and `:vs` for preview).
- The split should take the full width (in case you have vertical splits), e.g. `<C-w>J` or `<C-w>K`. This could also be configurable, by default it should be bottom.
- Add a config option to leave the finder open after opening the code link. In this case, the finder should be closed manually by the user.
- If the finder stays open after opening the link, the next reference search should reuse the open split.

**Describe alternatives you've considered**

An alternative could be sending the finder results to the quickfix list. But that is not as convenient, since now you have a different UI and without previews. The sending to the quickfix could be implemented as a separate feature though.

**Additional context**

Here is a quick prototype:

https://user-images.githubusercontent.com/16953692/229222320-39afea47-642c-4b72-82da-8bc0c84f895a.mov

**Comment by glepnir** [comment]
recently i also discussed with some people about finder ui and I decide to add a field layout for finder

**Comment by defr0std** [comment]
Thanks. Is the field layout the horizontal split like in the example above?

And also, is it possible to have such layout for the incoming/outgoing calls too?

**Comment by glepnir** [comment]
a new layout like this.  
![image](https://user-images.githubusercontent.com/41671631/229277271-179bcff8-8285-4313-9f67-bf9e4ef8a307.png)

**Comment by defr0std** [comment]
Oh, I see. And what do you think about the window split layout? The field layout is still modal floating window, so it's still possible to lose context as described above.

**Comment by glepnir** [comment]
you mean missing `definition` `references` ?

**Comment by defr0std** [comment]
By losing context I mean this. Imagine you work in a large codebase. You search for references and get lots of hits in the code you are not familiar with. 

Now I want to go carefully through many of these references. I want to open the link in the regular buffer, navigate around, search for incoming calls etc. 

When I am done with analyzing one such reference, I need to repeat the same process with the _next_ reference. This is why I would like the finder UI to stay open all the time. I will close it myself when it's no longer needed. In this case it's not very convenient that the UI is a floating window.

**Comment by glepnir** [comment]
so that's why there has peek window. it's a normal buffer. you can jump into it and do edit like a normal buffer and close peek window you will back to the finder main window.

**Comment by defr0std** [comment]
The peek window is not convenient for doing the "serious" work in it:
- It's too small, at least smaller than other regular splits on the screen.
- It appears in different locations depending on where you opened the finder from. So it feels strange to work in it.
- You can't navigate from the preview window to other open splits and then back. For example, on the big screen I have 4 different splits. While analyzing the references, I need to go to one of the existing splits to check more context, and then back to the preview window (which is not possible). 

If the finder is displayed in a regular vim split, then you can do all the usual vim navigation anywhere in the tab, and then jump back to the finder when ready to move on.

**Comment by defr0std** [comment]
Let me know if you need any help with this one. I already have the dirty prototype as you can see in the initial comment video. It does need a lot of polishing though. Also, if this split UI is reused across finder and call hierarchy, that would need some more design changes to share the logic.

**Comment by alextrastero** [comment]
WOW, this is exactly what I want!

**Comment by glepnir** [comment]
new idea is add `layout` interface. support `native` `float`.

**Comment by alextrastero** [comment]
I just need some sort of ui options, right now it's so hard to see what's going on...
![image](https://user-images.githubusercontent.com/4152819/230045072-e2fedc6b-3a19-4f52-bb1e-add8490e8d14.png)

**Comment by glepnir** [comment]
`ui.border` add a border ,  highlight of `SagaNormal`  change the float window background color

**Comment by defr0std** [comment]
@glepnir, would you accept a PR for this feature? I had it almost implemented as you can see in the initial comment video. If you accept, we can discuss the configuration options here and some basic design proposal.

**Comment by glepnir** [comment]
yep but there already have a process on .
