### ISSUE TITLE
Custom filtering of references and incoming/outgoing calls 

### ISSUE THREAD

**Issue by defr0std** [nvimdev/lspsaga.nvim#988]
**Is your feature request related to a problem? Please describe.**

When analyzing references or incoming/outgoing calls, not all results are equally valuable to the user. The two common examples are:

1. References in tests. It often happens that your function is referenced 5 times in production code, and 47 times in tests. When you are analyzing the production code, seeing all the test references just stands in the way.
2. References in generated code. Some projects have generated code in their sources. The close analogy is tree-sitter parser - it's C code which is fully generated from the grammar. When you search for references, the usages in the generated code are not usually of interest.

**Describe the solution you'd like**

It would be cool to let the users define custom filter functions for references and incoming/outgoing calls. 

There are 2 possible implementation options:

**Option A: Custom predefined filters.**

1. In the config, the user defines custom filter functions:
```lua
require("lspsaga").setup({
  finder = {
    filters = {
      {
        name = "Tests",
        fn = function(entry)
          return entry.file_name ends with "_test.ts"
        end
      },
      {
        name = "Generated code",
        fn = function(entry)
          return entry.file_name ends with "_generated.ts"
        end
      }
    }
  }
})
```

The entry to the filter `fn` could be whatever object is returned by the LSP server. 

2. In the finder window, add a function to apply a filter to the results. There should be two types of filters: `include` and `exclude`. 
For example:
- The user presses `<Leader>fe` (filter exclude)
- The plugin presents the list of available filters in the menu ("Tests", "Generated code"), e.g. like code actions.
- The user chooses "Tests" from the menu.
- The finder results are re-rendered accordingly, taking the filters into account - all references in tests will now be hidden
- The user could apply more filters like this, including and excluding various results. 

Option A pros: quick filtering on commonly used expressions.
Option A cons: not possible to filter dynamically. Let's say at some point you need to filter on all files under `/src/backend`. You'd need first to define such a filter, and restart neovim.

**Option B: Dynamic file path filters**

Instead of defining the static filter functions in the config, the UI can support dynamic filtering on the file paths based on some regex.

For example:
- The user presses `<Leader>fe` (filter exclude)
- The plugin shows the text input for the filter expression. 
- The user types `_test.ts|_generated.ts`. This means exclude all files which end with _test.ts or _generated.ts.
- The finder results are re-rendered accordingly, taking the filters into account.
- The user can edit the filters as needed.

Option B pros: dynamic filtering on anything.
Option B cons: for commonly filters (e.g. _test.ts) need to re-type the same filter each time. This could be mitigated by preserving the filters when the UI is closed, or by adding shortcuts to define custom filter strings.

**Applicable to both options**

* The filters should be saved when closing and reopening the UI (possibly with a config option to disable).
* The current filter selection can be shown in the winline of the finder, for example:
   
   ```
   Filters: include "Tests", exclude "Generated code"
   ```

**Describe alternatives you've considered**

Not sure there is anything.

**Comment by glepnir** [comment]
does this filter should also work on `references` or `implement` ?

**Comment by defr0std** [comment]
Ah yes, that would be helpful too. Maybe then the filters in the config can be global (not per `finder` as in my example). Then any UI with references would be able to use them. It's a question though what should the `entry` in the `fn` be. I imagine that LSP server returns different response messages to different calls. Maybe the `entry` can then be a custom object defined in the lspsaga layer, which contains file name, function name, etc.

**Comment by glepnir** [comment]
I will thinking about how to implement this two issues. in my first look both make sense. but I am busy on a project . so I will check these after two days later.

**Comment by defr0std** [comment]
Thanks! These are not issues, just some feature requests, and there is no rush at all. Thanks for the great plugin!

**Comment by defr0std** [comment]
FYI. Added Option B in the initial comment. Instead of the static filter functions in the config, the plugin could also offer a dynamic filter on the file path. The user would type something like `_test.ts|_generated.ts` in the filter text input to apply the filter.
